### ISSUE TITLE
conditional_probability_alive in ModifiedBetaGeoFitter and BetaGeoFitter

### ISSUE THREAD

**Issue by aprotopopov** [CamDavidsonPilon/lifetimes#103]
It's strange but there are different code realization for `conditional_probability_alive` for `ModifiedBetaGeoFitter` and `BetaGeoFitter` with the same link on [Computing P(alive) Using the BG/NBD Model](http://www.brucehardie.com/notes/021/palive_for_BGNBD.pdf):
```
class BetaGeoFitter(BaseFitter):

    def conditional_probability_alive(self, frequency, recency, T):
        """
        Compute the probability that a customer with history (frequency, recency, T) is currently
        alive. From http://www.brucehardie.com/notes/021/palive_for_BGNBD.pdf

        Parameters:
            frequency: a scalar: historical frequency of customer.
            recency: a scalar: historical recency of customer.
            T: a scalar: age of the customer.

        Returns: a scalar

        """
        r, alpha, a, b = self._unload_params('r', 'alpha', 'a', 'b')
        return 1. / (1 + (frequency > 0) * (a / (b + frequency - 1)) * ((alpha + T) / (alpha + recency)) ** (r + frequency))

class ModifiedBetaGeoFitter(BetaGeoFitter):

    def conditional_probability_alive(self, frequency, recency, T):
        """
        Compute the probability that a customer with history (frequency, recency, T) is currently
        alive. From http://www.brucehardie.com/notes/021/palive_for_BGNBD.pdf

        Parameters:
            frequency: a scalar: historical frequency of customer.
            recency: a scalar: historical recency of customer.
            T: a scalar: age of the customer.

        Returns: a scalar

        """
        r, alpha, a, b = self._unload_params('r', 'alpha', 'a', 'b')
        return 1. / (1 + (a / (b + frequency)) * ((alpha + T) / (alpha + recency)) ** (r + frequency))
```

[conditional_probability_alive BetaGeoFitter](https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/estimation.py#L622)

[conditional_probability_alive ModifiedBetaGeoFitter](https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/estimation.py#L777)

**Comment by aprotopopov** [comment]
I think for BetaGeoFitter it's a right equation according to [Computing P(alive) Using the BG/NBD Model](http://www.brucehardie.com/notes/021/palive_for_BGNBD.pdf). 
However for MBG/NBD may be not as I understand from  original paper [Empirical validation and comparison of models for customer base analysis](https://www.researchgate.net/publication/247219660_Empirical_validation_and_comparison_of_models_for_customer_base_analysis).   
Equation for probability alive/active is in Appendix A, number (5).

**Comment by CamDavidsonPilon** [comment]
Hm, it _looks_ different, but the gamma ratios will simplify to the correct values - am I missing something?

**Comment by aprotopopov** [comment]
Yes, you're right. Probably just need to delete 'http://www.brucehardie.com/notes/021/palive_for_BGNBD.pdf'  from description for conditional_probability_alive for MBG/NBD
