### ISSUE TITLE
Optimizer for fit method

### ISSUE THREAD

**Issue by aprotopopov** [CamDavidsonPilon/lifetimes#107]
I found, that optimizer for `_fit` was changed from `minimize` to `fmin` in utils with [that commit](https://github.com/CamDavidsonPilon/lifetimes/commit/bc06a6c73932e888c034df1c6a596ca28375e728#diff-48a7adefd56b3316f39206b07dadd6f5). I have some questions: 
- why *Nelder-Mead* algorithm was finally chosen?
- why `minimize` was changed to `fmin` while there are some notes about that in [scipy docs](https://docs.scipy.org/doc/scipy-0.19.0/reference/optimize.html):
> The specific optimization method interfaces below in this subsection are not recommended for use in new scripts; all of these methods are accessible via a newer, more consistent interface provided by the functions above

I'm also interesting in increasing training speed for model (BetaGeoFitter) because in my case I need to wait about 45 minutes to train (~15 mln records). On sample I saw that [SLSQP](https://docs.scipy.org/doc/scipy-0.19.0/reference/optimize.minimize-slsqp.html) was faster. Could it be used for training model or the are any pitfalls with that?

**Comment by CamDavidsonPilon** [comment]
I remember we were having trouble getting convergence with very small datasets, hence the change. Your recent changes fix this problem for all parties 👍
