### ISSUE TITLE
Save models

### ISSUE THREAD

**Issue by lrargerich** [CamDavidsonPilon/lifetimes#124]
Hi, is there a quick way to save the models that take a long time to fit? The idea is to just save them and then use them...
Thanks!

**Comment by aprotopopov** [comment]
Hmm... What about fitters methods `save_model` and `load_model`?

**Comment by lrargerich** [comment]
I didn't found them in the documentation. My fault.

**Comment by aprotopopov** [comment]
We'll add that info later to docs.

**Comment by stochastic1** [comment]
For any others who need to know how to call these:

## create the fitter object and fit the model
from lifetimes import ModifiedBetaGeoFitter
mbg = ModifiedBetaGeoFitter()
mbg.fit(f_, r_, t_)

## save the model and data
mbg.save_model("./save_name",True)

## import the model and data
mbg_ = ModifiedBetaGeoFitter()
mbg_.load_model("./save_name")

Note this is from Python 2.7. With the removal of unbound methods in Python 3, I don't know what needs to be done to work around these, if anything.

**Comment by CamDavidsonPilon** [comment]
^^ we should add this to docs.

**Comment by aprotopopov** [comment]
Yeah, I'll add that soon. Probably we need extra section for routines with models? 
I'm also thinking adding saving model like `to_json` or `to_yaml` only parameters, because even without data I had heave dill file... (for 15 mln records about 900Mb with data and 150Mb without.)

**Comment by stochastic1** [comment]
FWIW, saving 0.8M records required 26Mb with the BetaGeo and Modified BetaGeo models, and 39Mb with the ParetoNBD model. Would it make more sense to create a json or yaml object for the model but keep the data in .csv (which is more familiar)? 

Lastly, what would you think of adding a column for monetary to the save file because it's part of the data used in calling CLTV methods? Currently the data file is only recency, frequency and T.

**Comment by CamDavidsonPilon** [comment]
Whoah why are the pickle objects so big? I like the to_json and to_yaml suggestions 👍 

> Lastly, what would you think of adding a column for monetary to the save file because it's part of the data used in calling CLTV methods? Currently the data file is only recency, frequency and T.

the save file?

**Comment by aprotopopov** [comment]
I'm also thinking about separate `save_model` and `load_model` from methods to functions. For example they could be placed in `utils.py` or some other file. It'll allow load models without first initializing them. @CamDavidsonPilon  what do you think?

**Comment by CamDavidsonPilon** [comment]
What about static methods on the classes, so we don't have to initialise them?

**Comment by aprotopopov** [comment]
@CamDavidsonPilon. But you'll still need to import fitter class like `BetaGeoFitter.save_model(bgf, path)` instead something like `save_model(bgf, path)` and `load_model(path)`..

**Comment by aprotopopov** [comment]
I think I found out why saved model is so heavy. It's due to `generate_new_data`:
```python
        self.generate_new_data = lambda size=1: beta_geometric_nbd_model(
            T, *self._unload_params('r', 'alpha', 'a', 'b'), size=size)
```
`T` have length as initial data. After assign it to None the final size is pretty. 
Probably it's also could be an option for saving as  `data` already have. Something like `save_generate_data_method`.

**Comment by aprotopopov** [comment]
[Docs for saving and loading model](http://lifetimes.readthedocs.io/en/latest/Saving%20and%20loading%20model.html#).
