### ISSUE TITLE
Memory exhaustion running lifetimes package for over 1 million transactions

### ISSUE THREAD

**Issue by harrisong** [CamDavidsonPilon/lifetimes#132]
I was fiddling with the lifetimes package and tried to look into why it took so long when the number of transactions increases significantly. I could not get 1 million transactions to work, so I started to use less number of transactions. (around 100k)

And when I try to do cProfile over the method calls, this is what I get.

<img width="845" alt="screen shot 2017-08-15 at 10 24 02 am" src="https://user-images.githubusercontent.com/182082/29480048-87b9676a-842a-11e7-9624-f218c9b2ba36.png">

I realised that if I ran the BetaGeoFitter.fit and BetaGeoFitter.fit, the method took 50 seconds to compute, which is a big issue if the number of transactions get high enough.

Is there anyway we can improve the performance of minimize() (line 308) in utils.py?

P.S. I already tried to reduce maxiter from 2000 to 400. It helps a little but it does not help much in the context of 1 million transactions.

Thanks loads!

**Comment by CamDavidsonPilon** [comment]
Thanks for profiling this - a few thoughts:

1) I've found a series bottleneck is in the transformation from transactions -> summary data (one row per customer) using the built in `summary_data_from_transactions_data` - are you using this? If so, I would avoid this and try to do the transformation in SQL database or a Spark job instead. 

2) We at Shopify treat shops with large number of customers by subsampling ~50k. We noted that the time-perf increased linearly with number of customers, but parameters became stable "enough" beyond that. 

3) You can also try setting `iterative_fitting=1` in the call to `fit`, but this may run the risk of bad parameters being found (though less likely with more data).

**Comment by aprotopopov** [comment]
We are fitting BG/NBD model for about 15mln customers with pandas DataFrame. Fitting from scratch takes about 45 minutes with a Nelder-Mead algorithm (which is default) and about 5-6 from a warm start (with setting `initial_params` from first fit). SLSQP is used as minimizing algorithm for a warm start, because for Nelder-Mead you need to also pass initial simplex.

**Comment by stochastic1** [comment]
Due to the size of our data, we also transform the data from transaction to customer using SQL. FWIW, we found that fitting time increases by ~6 minutes per 1 million additional customers.

**Comment by CamDavidsonPilon** [comment]
I think v0.11.0 will sign. improve performance for large datasets. Let me run some perf tests.

**Comment by CamDavidsonPilon** [comment]
For ~50k rows in BetaGeoFitter, it's about 3x faster in v0.11.0. 
For 236k rows, it's about 5x faster in v0.11.0. 

And v0.11.0 has by default smaller `tol` parameter. The major speedup is being about to drop Neader-Mead and instead use BFGS.
