### ISSUE TITLE
Extra Hyperparameters to tweak for better model fit

### ISSUE THREAD

**Issue by Adnation** [CamDavidsonPilon/lifetimes#136]
Other than penalizer coef is there any other parameter to tweak to achieve better model fitting?

Because I am not getting a good model fit for my use case.
I've also tried BGF with penalizer_coef=0.3/0.2 and result was better than 0.1 albeit not satisfying. So in documentation I found that the good range should be 0.001 to 0.1 so why is that so? and is there anything wrong in using penalizer_coef out of that range?

**Comment by stochastic1** [comment]
How are you measuring your model fit? We've had satisfactory results when validated against holdout without using a penalty.
