### ISSUE TITLE
Different Time Units for the Model and the CLV Estimation

### ISSUE THREAD

**Issue by phthomas** [CamDavidsonPilon/lifetimes#137]
**Background:**
in the following [docs](http://lifetimes.readthedocs.io/en/latest/Quickstart.html#estimating-customer-lifetime-value-using-the-gamma-gamma-model
)
The example shows the following code:

```python
# refit the BG model to the summary_with_money_value dataset
bgf.fit(summary_with_money_value['frequency'], summary_with_money_value['recency'], summary_with_money_value['T'])

print(ggf.customer_lifetime_value(
    bgf, #the model to use to predict the number of future transactions
    summary_with_money_value['frequency'],
    summary_with_money_value['recency'],
    summary_with_money_value['T'],
    summary_with_money_value['monetary_value'],
    time=12, # months
    discount_rate=0.01 # monthly discount rate ~ 12.7% annually
).head(10))
```

**Issues**
The `summary_with_money_value` refers to CDnow dataset which has the `T` in the unit of weeks. However, the `t` parameter in  `ggf.customer_lifetime_value` is using months as the default unit. This is showed by `ggf.customer_lifetime_value` has a `time*30` (*the 30 is hardcoded*) in the function. That would lead to the mixing of time used in the examples. In the examples, calling the `ggf.customer_lifetime_value(bgf,...)` will lead to the following code executed:

```python
bgf.conditional_expected_number_of_purchases_up_to_time(i, frequency, recency, T) - bgf.conditional_expected_number_of_purchases_up_to_time(i - 30, frequency, recency, T).  
```
I am not sure about this, but shouldn't be the time units for `i` and   `T` used in the `bgf.conditional_expected_number_of_purchases_up_to_time` should have the same units? 

Thanks a lot for enlightening me, and sorry for the long post.

**Comment by vivienneyang** [comment]
I have the same confusion. If I'm using days as the unit of time for my data and I want to predict the CLV for next 6 month. What is the number shall I put here. Should I put 6 or 180?
