### ISSUE TITLE
Getting probability of staying alive

### ISSUE THREAD

**Issue by Adnation** [CamDavidsonPilon/lifetimes#138]
Is there any way we can get the customer's probability of staying alive using BG/NBD model? Right now it gives us a plot but how about getting a number for each user?

**Comment by aprotopopov** [comment]
Do you mean [`conditional_probability_alive`](https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/fitters/beta_geo_fitter.py#L199)? You could set `frequency`, `recency`, and `T` for each users and get probabilities.

**Comment by jasminesethi11** [comment]
can you tell me the syntax for find the probabilities? I can also see plots only.
