### ISSUE TITLE
summary_data_from_transaction_data() misses lots of users

### ISSUE THREAD

**Issue by foreveryang0208** [CamDavidsonPilon/lifetimes#139]
Have anybody encountered the issue when after applying lifetimes.utils. summary_data_from_transaction_data function, the resulting rfm dataset only has parts of user being analysed, e.g.
![lifetimes](https://user-images.githubusercontent.com/9613154/31012915-907bb9be-a50b-11e7-92e8-1a6c8a6cff08.png)

I couldn't figure out why this has happened. I've checked the users who have been missed - their data doesn't look different from the captured ones. Is there something I've missed? 

Thanks

**Comment by aprotopopov** [comment]
As I tested with `load_transaction_data` there all users in summary which are in the raw transactions:

```python
from lifetimes.datasets import load_transaction_data
from lifetimes.utils import summary_data_from_transaction_data
import pandas as pd

transactions  = load_transaction_data()
transactions.date = pd.to_datetime(transactions.date)
observation_period_end = transactions.date.max()
transactions_summary = summary_data_from_transaction_data(transactions, 'id', 'date', 
                                                          observation_period_end=observation_period_end)

print('transactions length:', len(transactions))
print('unique users:', transactions.id.nunique())
print('unique users summary:', transactions_summary.index.nunique())

"""
transactions length: 15273
unique users: 5000
unique users summary: 5000
"""
```

**Comment by foreveryang0208** [comment]
Thanks Anton! Just realised I indeed miss something. If the observation_period_end is set to the last day of dataset, like you did, then every sampled users will be included. Yet I set the date somewhere in the middle of full date range, so the users who haven't got any transactions before that day surely would get missed out.
