### ISSUE TITLE
palive

### ISSUE THREAD

**Issue by jasminesethi11** [CamDavidsonPilon/lifetimes#141]
How to calculate Palive in python?
 In r it used to be done like this pnbd.PAlive(params, cal.cbs[, 1], cal.cbs[, 2], cal.cbs[, 3]). What is the similar syntax in python for this?

**Comment by aprotopopov** [comment]
Probably you could find an answer in issue #138 Could you elaborate a bit what you want? What model are you using? IIUC you need to use function [`conditional_probability_alive(self, frequency, recency, T)`](https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/fitters/beta_geo_fitter.py#L199). And you need to pass `frequency`, `recency` and `T` for each customer.

**Comment by aprotopopov** [comment]
As I understand you also post a question on StackOverflow. I'll answer on [SO](https://stackoverflow.com/a/46903478/4542359) with example. Probably it should be added to docs.

**Comment by jasminesethi11** [comment]
Hey aprotopopov,
Thank you for your help. I have one more doubt when my b parameter value is very high I cant generate Palive values. It says NaN it only gives me value when the parameters are pretty low. In many cases my parameters are very high and I cant generate the values.
Could you please advise on this too?

**Comment by jasminesethi11** [comment]
Also my palive is coming Nan if i get parameters value as 
df['palive'] = 0.0
results = {}
results_pnbd_p	= {}
for i in prodname:
    temp= df[df["PL"]==i]   ##PL is product line and i find parameters for product lines
    pnbd = ParetoNBDFitter()
    mod = pnbd.fit(temp['x'], temp['t_x'], temp['T'])
    results[i] = mod.params_.values()   
    try:
      temp['predicted'] = mod.conditional_probability_alive(temp['x'], temp['t_x'], temp['T'])
    except:
      continue
    print i
    print results
    for j in temp.index:
      df.ix[j,'palive'] = temp['predicted'][j]


These are the patameters for various products
[0.37539907966456781, 12.408974858640757, 166.24896295496771, 16707.485609765685]
[0.47937779134704839, 15.881807005920486, 168.14497995830808, 31673.942334769028]
[1.2677477405348565, 56.675615773629673, 254.74561364576181, 22412.80994031002]
[0.61994617392998186, 29.649668459922051, 196.74448655037014, 10320.644896684935]

**Comment by aprotopopov** [comment]
@jasminesethi11 could you format your code properly and provide a sample of your data?

**Comment by jasminesethi11** [comment]
@aprotopopov  This is the sample data I was trying on 
[palive_error.xlsx](https://github.com/CamDavidsonPilon/lifetimes/files/1483728/palive_error.xlsx)

Below is the code I use. I try to find parameters for my each product line as I have different products and PL means the products and then corresponding to those PL i fond p alive for customers.

df['palive'] = 0.0
results = {}
results_pnbd_p	= {}
for i in prodname:
    temp= df[df["PL"]==i]
    pnbd = ParetoNBDFitter()
    mod = pnbd.fit(temp['x'], temp['t_x'], temp['T'])
    results[i] = mod.params_.values()   
    try:
      temp['predicted'] = mod.conditional_probability_alive(temp['x'], temp['t_x'], temp['T'])
    except:
      continue
    print i
    print results
    for j in temp.index:
      df.ix[j,'palive'] = temp['predicted'][j]

**Comment by aprotopopov** [comment]
You didn't provide any info about `prodname`. There are just 44 rows in you file and you also have several products. I think it's insufficient for model stability and predictive power will be low. If I fitting Pareto with all products I have parameters like below and `palive` are not `NaNs`

```python
import pandas as pd
from lifetimes import ParetoNBDFitter

temp = pd.read_excel('/tmp/palive_error.xlsx')
pnbd = ParetoNBDFitter()
mod = pnbd.fit(temp['x'], temp['t_x'], temp['T'])
print(mod)
print(mod.conditional_probability_alive(temp['x'], temp['t_x'], temp['T']))

<lifetimes.ParetoNBDFitter: fitted with 44 subjects, alpha: 2.92, beta: 0.00, r: 0.13, s: 0.00>
0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
29    1.0
30    1.0
31    1.0
32    1.0
33    1.0
34    1.0
35    1.0
36    1.0
37    1.0
38    1.0
39    1.0
40    1.0
41    1.0
42    1.0
43    1.0
dtype: float64

```

**Comment by jasminesethi11** [comment]
prodname = df["PL"].unique()

It takes parameters for each PRODUCT line
