### ISSUE TITLE
Can anyone help me to calculate PALIVE(the probability that they are still alive at the end of the calibration period.) in Python?

### ISSUE THREAD

**Issue by jasminesethi11** [CamDavidsonPilon/lifetimes#142]
I know R has a Pareto negative binomial distribution function pnbd.PAlive(params, r, s, apha, beta) but what is similar to it in Python?

**Comment by CamDavidsonPilon** [comment]
Hey, this is a duplicate of the other issue you created (not good to duplicate). I may be able to help, but I’m on vacation atm

**Comment by jasminesethi11** [comment]
I am sorry but I cant see in the lifetimes documentation. it only shows plot but not just the calculations syntax
