### ISSUE TITLE
Divide by zero in BGBB fit

### ISSUE THREAD

**Issue by mtlotfizad** [CamDavidsonPilon/lifetimes#143]
While fitting my model I encountered this error:
.../beta_geo_beta_binom_fitter.py:71: RuntimeWarning: divide by zero encountered in log
  betaln(gamma + 1, delta + tx + j) - beta_gd)))

I call fit method with this code snippet: 
`summary = summary_data_from_transaction_data(transaction_data, 'customer_id', '_date')`
`bgbf = BetaGeoBetaBinomFitter(penalizer_coef=0.1)`
`summary_bgbf = summary.reset_index().summary_bgbf.groupby(['frequency', 'recency', 'T'])['customer_id'].agg(['count']).reset_index().astype(int)`
`bgbf.fit(summary_bgbf['frequency'], summary_bgbf['recency'], summary_bgbf['T'], summary_bgbf['count'])`

**Comment by CamDavidsonPilon** [comment]
Are you able to provide the dataset as well?

**Comment by aprotopopov** [comment]
Fixed in #158
