### ISSUE TITLE
My clv is coming wrong. It comes negative for many customers. Can you please suggest.

### ISSUE THREAD

**Issue by jasminesethi11** [CamDavidsonPilon/lifetimes#146]
```python
from lifetimes import GammaGammaFitter
ggf = GammaGammaFitter(penalizer_coef = 0)
ggf.fit(df['x'], df['Margin'])
df['clv'] = 0.0
results = {}
results_pnbd_p	= {}
for i in prodname:
    temp= df[df["PROD_MODEL"]==i]
    ggf = GammaGammaFitter(penalizer_coef = 0)
    ggf.fit(temp['x'], temp['Margin'])
    pnbd = ParetoNBDFitter()
    mod = pnbd.fit(temp['x'], temp['t_x'], temp['T'])
    results[i] = mod.params_.values()
   
    try:
      temp['clv'] = ggf.customer_lifetime_value(mod, #the model to use to predict the number of future transactions
                                                      temp['x'], temp['t_x'], temp['T'], temp['Margin'],
                                                      time=12, # months
                                                      discount_rate=0.1)
    except:
      continue
    print i
    print results
    for j in temp.index:
      df.ix[j,'clv'] = temp['clv'][j]
```

**Comment by CamDavidsonPilon** [comment]
Are you able to provide the dataset as well?

**Comment by stochastic1** [comment]
Is there anything in common for the customers evaluated with a negative CLV? I've run into problems when Tenure = Recency on the BGF model.

**Comment by jasminesethi11** [comment]
i was trying on this dataset.
[clv_error.xlsx](https://github.com/CamDavidsonPilon/lifetimes/files/1472769/clv_error.xlsx)

**Comment by jasminesethi11** [comment]
@CamDavidsonPilon any suggestions

**Comment by stochastic1** [comment]
@jasminesethi11, your data is very irregular. What are you using for your time periods?

**Comment by stochastic1** [comment]
@jasminesethi11 , the gammagammafitter and other parts of the codebase have since been updated. Can you try again with the updated codebase?

**Comment by Trollgeir** [comment]
I'm encountering the same problem. 

It occurs when the GammaGammaFitter's fitted parameter `q < 1`, causing the `population_mean` to be negative.

```
<lifetimes.GammaGammaFitter: fitted with 86725 subjects, p: 15.20, q: 0.58, v: 17.24>

population_mean = v * p / (q - 1)

-631.1499946276026
```

**Comment by vruvora** [comment]
I am having a similar issue -- what's the intuition behind `q < 1` which is going to break the Gamma-Gamm model.

**Comment by CamDavidsonPilon** [comment]
Though I don't know a fix right now, I'll make some changes to be added to #220 v0.10.0

**Comment by CamDavidsonPilon** [comment]
@vruvora are you able to supply a dataset I can test against?

**Comment by vruvora** [comment]
@CamDavidsonPilon Unfortunately not. But since `scipy.minimize` accepts constraint arguments, does it make sense to have a constraint for `q > 1`?

**Comment by CamDavidsonPilon** [comment]
Maybe? That means inference elsewhere would suffer. That may be the solution I go with though. I'll do  some testing.

**Comment by vruvora** [comment]
Do you think is there a more elegant way to design the API so that you can just hardcode the constraints as `kwargs`?

**Comment by CamDavidsonPilon** [comment]
Do do you want to _sometimes_ allow q < 1, and othertimes not? And setting that flag in `fit`?

**Comment by vruvora** [comment]
Actually, so looking more into it, I think giving hard-constraints might be a bit harder because you have to fiddle with `scipy` source code so I like the idea of blowing up negative log likelihood if it's `q < 1`. I just updated and it gives sensible results.

**Comment by CamDavidsonPilon** [comment]
Feel free to PR for branch `v0.10.0` if you want it in the latest release - otherwise I'll add something later this week.

**Comment by vruvora** [comment]
Perfect -- will do that today. Btw, @CamDavidsonPilon  I would be curious if there is any interesting in re-writing `lifetimes` in TFP or Pyro. Would love to help with that project.

**Comment by eromoe** [comment]
Add  `q_constraint=True` got 
```
gamma_gamma_fitter.py:156: RuntimeWarning: divide by zero encountered in double_scalars
  population_mean = v * p / (q - 1)
```
