### ISSUE TITLE
expected_cumulative_transactions will calculate actual transactions incorrectly

### ISSUE THREAD

**Issue by patng323** [CamDavidsonPilon/lifetimes#152]
While I am using plot_cumulative_transactions, I think I found a bug in utils.expected_cumulative_transactions.

Let's say I want to build a beta_geo_fitter model, and freq='D'.  First I will call utils.summary_data_from_transaction_data to summarize my transaction.  That function will treat transactions which happened on the **same** day as one transaction when it calculates _frequency_.  

Later on, when I call plot_cumulative_transactions, I see that it calls utils.expected_cumulative_transactions, but that function will treat multiple transactions happening on the same day as multiple transactions (see the line below).

`act_transactions = (transactions_current.groupby(customer_id_col).size() - 1).sum()`

As a result, the actual and expected lines I got from plot_cumulative_transactions look very different.  I worked around this by calling df.drop_duplicates([customer_id_col, date_col]) on my transaction dataframe first before I call plot_cumulative_transactions.

**Comment by aprotopopov** [comment]
@patng323 Nice catch. I'll fix that soon and will add a test for that function `utils.expected_cumulative_transactions`

**Comment by aprotopopov** [comment]
@patng323  IIUC you are talking about [that line](https://github.com/CamDavidsonPilon/lifetimes/blob/24ca372f7d75e2fb2b624e16c6f16a5eb3024a52/lifetimes/utils.py#L464) in function `expected_cumulative_transactions`. [Some lines before](https://github.com/CamDavidsonPilon/lifetimes/blob/24ca372f7d75e2fb2b624e16c6f16a5eb3024a52/lifetimes/utils.py#L446-L449) there is reindexing which leads to one record per `freq` period. So it seems now that there are no any bugs...
 Could you provide an example dataset?

**Comment by patng323** [comment]
@aprotopopov I tried and I am afraid the reindexing [line](https://github.com/CamDavidsonPilon/lifetimes/blob/24ca372f7d75e2fb2b624e16c6f16a5eb3024a52/lifetimes/utils.py#L446-L449) you mentioned will **not** reduce the data to one record to `freq` period.  

Please note that back in `summary_data_from_transaction_data`, it is actually this [line](https://github.com/CamDavidsonPilon/lifetimes/blob/24ca372f7d75e2fb2b624e16c6f16a5eb3024a52/lifetimes/utils.py#L161) which did that reduction trick.

**Comment by CamDavidsonPilon** [comment]
The `expected_cumulative_transactions` is a bit strange: everywhere else we deal with a summary dataset, but here we ask for the raw transactions. 

Anyways, the function is broken, but I have a fix like what @patng323 suggests.

**Comment by aprotopopov** [comment]
@CamDavidsonPilon raw transactions are needed to get actual values. That cannot be extracted from final summary matrix. Only if you calculate summary for each time period.
P.S. I'm in process of writing tests for that function to get the same values as in BTYD walkthrough.
