### ISSUE TITLE
BetaGeo Fitter conditional_probability_alive() variants for case when frequency = 0

### ISSUE THREAD

**Issue by adsmaniotto** [CamDavidsonPilon/lifetimes#165]
I'm running into a situation where the results of my BGF probability score defaults to 1 for users that have no frequency (one-time purchasers). Like most companies, I have customers who have been "alive" for years, but haven't made a second purchase. In their case, I'd rather assume that their probability is near-zero than follow the model's assumption.

The [Bruce Hardie paper](http://www.brucehardie.com/notes/021/palive_for_BGNBD.pdf) that's referenced in the code for `beta_geo_fitter.py` addresses this assumption and suggests two potential variants:

> We note that P(alive) = 1 for a customer who made no purchases in the interval (0, T]; this follows from the model’s assumptions that death occurs after a purchase and that customers are alive at the beginning of the observation period. Those interested in the P(alive) metric may view this as a shortcoming of the model.

Have you considered adding these variants to account for customers with no frequency? I feel like both of the ones he offers up would involve fairly minor additions to the function (a couple optional arguments and slight tweaks to the formula), but wanted to get your thoughts on whether I'm thinking about this wrong, or if there are other approaches I should consider before I submit a PR.

**Comment by rhydomako** [comment]
The Modified Beta-Geometric model might be what you're looking for:

https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/fitters/modified_beta_geo_fitter.py

Some model details, as they relate to P(alive) for customer who have only made one purchase: http://www.brucehardie.com/notes/021/palive_for_BGNBD.pdf

**Comment by adsmaniotto** [comment]
Got it, thanks for pointing that model out! I'm already familiar with Hardie's work but didn't realize that's what the Modified Beta-Geometric was for.

@aprotopopov and @CamDavidsonPilon have done a great job of documenting within the fitter functions, but it would also be great to have a reference in the actual `docs` folder that contains descriptions of each model, what the use cases are, why you might use one over the other, etc. I might be able to contribute something like that as a good way to get to know the models a bit better.

**Comment by psygo** [comment]
> (...) but it would also be great to have a reference in the actual `docs` folder that contains descriptions of each model, what the use cases are (...)

Agreed.

**Comment by miao8829** [comment]
Is that ok to mix models for analysis? like using BG/NBD for predicting frequency but use MBG/NBD for probability of alive? Or should it be using one model only? Thanks!
