### ISSUE TITLE
How to increase accuracy for CLTV prediction

### ISSUE THREAD

**Issue by laurahy172** [CamDavidsonPilon/lifetimes#166]
Hi,

I've run the Pareto/NBD model to fit the data. from what i expected is the model tends to overestimate the transaction count. 

negative log likelihood from the fit function is positive, around 61. I've played with the panelizer coef from 0 to 1 and this yield similar LL value around 61 to 62

Is it as expected? How should i improve the fitness?

**Comment by stochastic1** [comment]
@laurahy172 , is the period you are using to train the model consistent with the expected lifecycle of repurchasing? In other words, if your anticipated inter-purchase interval is 3 months, are you training on at least a 6-month period? Is the period unusually high (ie, does it include a product launch that rewarded a second transaction within n days)?

**Comment by psygo** [comment]
Please give us graphs and perhaps a sample of your dataset so we *can* help you.
