### ISSUE TITLE
calibration_and_holdout_data(), monetary_value_holdout not grouping by freq 

### ISSUE THREAD

**Issue by simenstrand** [CamDavidsonPilon/lifetimes#167]
In `calibration_and_holdout_data()`, `monetary_value_holdout` is currently the mean transaction value per customer, without regard for the chosen aggregation period. This is problematic when a customer has multiple transactions in the chosen aggregation period:

```python
if monetary_value_col:
    holdout_summary_data['monetary_value_holdout'] = \ 
        holdout_transactions.groupby(customer_id_col)[monetary_value_col].mean() 
```

**Comment by mkbldn** [comment]
Wouldn't this little tweak work to resolve this?

```
    if monetary_value_col:
        holdout_summary_data["monetary_value_holdout"] = holdout_transactions.groupby(customer_id_col)[
            monetary_value_col
        ].sum() / holdout_summary_data["frequency_holdout"] 
```

**Comment by psygo** [comment]
I'm not sure if I understand what you people mean...

Do you mean that the `mean()` operation is not taken *only* inside the *holdout* set? If that's the case, I don't know if I agree because the `groupby()` operation *is* taken on top of the *holdout* transactions only (`holdout_transactions`).
