### ISSUE TITLE
Penalizing parameters for being too small?

### ISSUE THREAD

**Issue by DataNeel** [CamDavidsonPilon/lifetimes#168]
I realize that it is typical to penalize model coefficients/parameters for being too large. When training the CLV models implemented by this library, would it ever make sense to penalize coefficients for being too small in addition to penalizing them for being too large?

In my experimentation, I've come across instances where the distribution parameters end up being very small, and it can result in wacky values for the probability that a customer is alive. It almost seems like it would be valuable to make sure that these parameters fall within an ideal range rather than only preventing them from being too large. Perhaps somebody who knows more can tell me why that would be ill-advised.

**Comment by rhydomako** [comment]
Hi @DataNeel,

It sounds like you have some prior information about valid parameter ranges for your fits. This information is super useful for making sure your predictions make sense, but it can be a bit tricky to incorporate into the MLE optimization framework that lifetimes uses. 

I suggest that you might take a look at some MCMC approaches. For example https://github.com/datascienceinc/pydata-seattle-2017/blob/master/lifetime-value/pareto-nbd.ipynb implements the Pareto-NBD model using pymc3. The advantage here is that you would have the flexibility to specify prior distributions for your model parameters which deemphasize small parameter values.

**Comment by DataNeel** [comment]
Thanks! I'll take a closer look at that link.

I'd still love to hear any related thoughts or experiences, if people have them.

**Comment by psygo** [comment]
It should be possible to incorporate a "minimum enough parameter values" contraint inside the loss optimization equation.

If you have any references, please post them here.
