### ISSUE TITLE
BetaGeoFitter.conditional_probability_alive returns 0D-array, not float

### ISSUE THREAD

**Issue by mszep** [CamDavidsonPilon/lifetimes#169]
The docstring mentions that the return type of `BetaGeoFitter.conditional_probability_alive` is `float`, but when passing values from DataFrames, the result is actually a 0-dimensional `ndarray`:

```
In [101]: bgf = BetaGeoFitter()

In [102]: df = load_cdnow_summary()

In [103]: bgf.fit(df['frequency'],df['recency'],df['T'])
Out[103]: <lifetimes.BetaGeoFitter: fitted with 2357 subjects, a: 0.79, alpha: 4.41, b: 2.43, r: 0.24>

In [104]: bgf.conditional_probability_alive(df.iloc[0]['frequency'],df.iloc[0]['recency'
     ...: ],df.iloc[0]['T'])
Out[104]: array(0.7266095443377226)

In [105]: 
```

The same method in other fitters seem to all have forms that would indeed return `float`s, but I haven't tested that explicitly.

I can make a PR where either the docstring is altered, or the return value is wrapped with `float()`; any thoughts on which would be preferable?

**Comment by CamDavidsonPilon** [comment]
Hah, good catch. I'm guessing it's because `df.iloc[0]['frequency']` and co. are not floats (or are they...). If you'd like to PR something, I think changing the return value is 😗👌

**Comment by mszep** [comment]
They are floats! I had the same thought but passing literal floats doesn't change the result type. The cause is returning the result of a call to `np.where`:
```
In [13]: np.where(1==1, 2, 3)
Out[13]: array(2)
```
Anyway, PR incoming.
