### ISSUE TITLE
Data generation method for BetaGeoBetaBinomFitter?

### ISSUE THREAD

**Issue by zscore** [CamDavidsonPilon/lifetimes#171]
Is there a reason why no data generation method has been implemented yet aside from lack of interest? If not, I can code something up.

**Comment by CamDavidsonPilon** [comment]
No reason - feel free to add something!

**Comment by zscore** [comment]
nice I have the method written. I guess the next steps are to make sure that it's imported in all the correct places and to add testing for it?

**Comment by CamDavidsonPilon** [comment]
Yup you got it. If you can PR something as a work-in-progress, I can help add details about what's needed.

**Comment by zscore** [comment]
Added new pull request #183 with datagen methods.
