### ISSUE TITLE
Negative values for monetary_value?

### ISSUE THREAD

**Issue by nuochen** [CamDavidsonPilon/lifetimes#172]
Is there a reason why the monetary_value cannot take negative values? With cost of marketing and production factored in, some customers indeed generate negative monetary values. Thanks!

**Comment by zscore** [comment]
I think the models here are based on a Gamma Distribution, which has a lower bound of 0. You can always try transforming your data so all of the values are positive.

**Comment by nuochen** [comment]
@zscore Thank you. That makes sense. I am thinking of just adding a constant to the entire dataset. Is there any potential harm in doing that? Any other data transformation techniques that you would recommend?

**Comment by zscore** [comment]
hmm I would look at the conditional distributions of prices for individuals matches the prices observed in a holdout period. Really though this model is pretty flexible so will probably fit your data fine. The original paper has some guidance on page 7: http://www.brucehardie.com/notes/025/gamma_gamma.pdf

**Comment by nuochen** [comment]
@zscore Just want to make sure that I am understanding you correctly. You are saying that you would refer to the conditional distributions of prices across all customers (as mentioned in the paper) when selecting a constant for data transformation, correct? Because that distribution should give you a sense of skewness and range of values 

In my dataset, many customers generate negative revenues. I am trying to understand how/if that would work on a gamma distribution-based model. All the other examples that I have seen contain only positive profits.

**Comment by CamDavidsonPilon** [comment]
> I am thinking of just adding a constant to the entire dataset. Is there any potential harm in doing that? Any other data transformation techniques that you would recommend?

I _think_ that would work fine... It's just a shift of the underlying distribution, and probably shouldn't effect inference since we have no priors on the parameters of the Gamma. 

If you try this, let us know if it works out!
