### ISSUE TITLE
Interpretation of P(alive) for one-time customers

### ISSUE THREAD

**Issue by mszep** [CamDavidsonPilon/lifetimes#173]
I've noticed a strange behaviour in the behaviour of the `conditional_probability_alive` method of the `ModifiedBetaGeoFitter` class. I'm not sure if it's a shortcoming in the model or implementation, a data issue or a mistake I'm making, but I'm hoping someone has seen this type of result before and can help me along.

The problem lies in the distributions I'm getting for the values of P(alive) across customers. The following plot illustrates the issue:
![screenshot from 2018-03-16 23-58-16](https://user-images.githubusercontent.com/734695/37549237-f71d4194-2975-11e8-8f4b-51e8401118d8.png)

The fairly smooth behaviour for high values of P(alive) is intuitively understandable, but the bulge around P(alive)=0.3 and the sharp cutoff is unexpected. Inspection reveals that the bulge is composed of customers who have made a single purchase, since it disappears when plotting only repeat customers:
![screenshot from 2018-03-16 23-58-25](https://user-images.githubusercontent.com/734695/37549243-fcbb16ee-2975-11e8-827c-e1f4e34447fa.png)

The cliff on the left side of the bulge is composed of customers who made their single purchase near the beginning of the observation period, and the customers get more recent as you move right within the bulge.

This distribution of P(alive) for one-time customers doesn't seem to me to be an accurate or useful representation of these customers' probability of being alive, but the issue crops up across datasets so I'm wondering if:

- There is anything incorrect or implausible about my interpretation
- This is a known issue with this type of model
- There are any known workarounds or fixes

Any other thoughts or suggestions would be very welcome.

**Comment by CamDavidsonPilon** [comment]
👋 this is the expected behaviour in fact. Let's first talk about the original BetaGeo model. It has a short coming that when a customer has a single purchase, it will always predict P(alive | freq=1 ) = 1. This is a consequence of the model "story":

<img width="361" alt="screen shot 2018-03-18 at 10 38 36" src="https://user-images.githubusercontent.com/884032/37567134-ccda93ae-2a98-11e8-9e59-e9f3813e04f4.png">

The ModifiedBetaGeo model "fixes" this by giving a non trivial probability to those with a single purchase. We can see what this means by looking at the code for `conditional_probability_alive`:

```python
    def conditional_probability_alive(self, frequency, recency, T):
        """
        Conditional probability alive.

        Compute the probability that a customer with history (frequency,
        recency, T) is currently alive.
        From https://www.researchgate.net/publication/247219660_Empirical_validation_and_comparison_of_models_for_customer_base_analysis
        Appendix A, eq. (5)

        Parameters
        ----------
        frequency: float
            historical frequency of customer.
        recency: float
            historical recency of customer.
        T: float
            age of the customer.
        ln_exp_max: int
            to what value clip log_div equation

        Returns
        -------
        float
            value representing a probability

        """  # noqa
        r, alpha, a, b = self._unload_params('r', 'alpha', 'a', 'b')
        return 1. / (1 + (a / (b + frequency)) *
                     ((alpha + T) / (alpha + recency)) ** (r + frequency))
```

Specifically focusing on the last line, we can set `frequency=1`, and when we have a single order, then `recency == T`

```python
1. / (1 + (a / (b + 1)) *  ((alpha + T) / (alpha + T)) ** (r + 1))
```

simplifying to see the relationship easier:

```python
1. / (1 + (a / (b + 1))
```

So when `freq=1` it's just a scalar. If I've done everything correct, there's still a problem:  _why_ you see different probabilities for customers with a single purchase. Can you confirm that `recency == T`  for them?

**Comment by CamDavidsonPilon** [comment]
Actually my assumption that when `frequency=1`, then `recency == T`, is wrong. So it doesn't simplify  so well. But `T >= recency`, so `(alpha + T) / (alpha + recency) >= 1`, and so  

```python
1. / (1 + (a / (b + 1)) * ((alpha + T) / (alpha + recency)) ** (r + 1))
```

has a lower bound of `1. / (1 + (a / (b + 1))`. In your case, it is about 0.30.

**Comment by mszep** [comment]
Thanks very much for your response, and apologies for my delay in getting back to you.

You are absolutely right, my results above are from a limited time period, which leads to the sharp cutoff around P(alive)=0.25 corresponding to the least recent one-time customers. I guess the conclusion is that even with the fix implemented in the `ModifiedBetaGeoFitter`, the model struggles when presented with too many one time customers and the P(alive) for those customers needs to be taken with a pinch of salt.

This actually jives with another thing I've observed, namely that when including too many one-time customers, the model sometimes converges to very low values of `a` and `b`, meaning that it thinks all customers either drop out right away, or live forever. Setting initial values of 0.5 or 1.0 (instead of the default Normally distributed values) helps mitigate this.

I'll close this issue now; thanks for building this great little library!
