### ISSUE TITLE
There's no way in git to determine what code was in prior releases.

### ISSUE THREAD

**Issue by barrywhart** [CamDavidsonPilon/lifetimes#175]
Could you create a git tag or branch for each release? Often, it is helpful to know what code makes up a particular release (e.g. to know if a release contains a particular issue and/or fix).

**Comment by CamDavidsonPilon** [comment]
👍 totally - I do this for other repos I own, but not this. I'll start doing it.

**Comment by barrywhart** [comment]
Thanks so much!!
