### ISSUE TITLE
Please continue offering source packages (.tar.gz) in addition to .whl

### ISSUE THREAD

**Issue by barrywhart** [CamDavidsonPilon/lifetimes#177]
Wheels are definitely better when they are supported. I have run across a situation where they apparently aren't supported: When I try and use Lifetimes on [Google Cloud DataFlow](https://cloud.google.com/dataflow/), it apparently ignores wheels, so I have to use Lifetimes 0.8.0.0 or earlier. I tried to install wheel before installing Lifetimes, but was unable to get it to work. (Because DataFlow is serverless, the options for customizing the environment are pretty limited.)

For now, I think I can work around this by building a source package myself and uploading it with the job.

If you can give me a little guidance on the packaging process for Lifetimes, I will be happy to submit a PR for this.

**Comment by CamDavidsonPilon** [comment]
Hey, I think you can do it using pulling the repo locally and using the python `twine` package. However, for 0.8.0, I'll add `.tar.gz` to PyPI now.

**Comment by CamDavidsonPilon** [comment]
Done! I'll add this to the "new version" checklist along with #175 

https://pypi.python.org/pypi/Lifetimes

**Comment by barrywhart** [comment]
Thanks so much!

I found this as a workaround in the meantime -- in `requirements.txt`, instead of `lifetimes==0.9.0.0`, do this:
```
-e git+git://github.com/CamDavidsonPilon/lifetimes@7fd24b85b137aab73addbf98f302992278497a97#egg=lifetimes
```

**Comment by barrywhart** [comment]
In using the source package, I noticed a mistake. This function in `lifetimes/fitters/modified_beta_geo_fitter.py` has a hardcoded breakpoint (`set_trace()`) in it:

```
    def conditional_probability_alive(self, frequency, recency, T):
        """
        Conditional probability alive.

        Compute the probability that a customer with history (frequency,
        recency, T) is currently alive.
        From https://www.researchgate.net/publication/247219660_Empirical_validation_and_comparison_of_models_for_customer_base_analysis
        Appendix A, eq. (5)

        Parameters
        ----------
        frequency: float
            historical frequency of customer.
        recency: float
            historical recency of customer.
        T: float
            age of the customer.
        ln_exp_max: int
            to what value clip log_div equation

        Returns
        -------
        float
            value representing a probability

        """  # noqa
        import pdb
        pdb.set_trace()
        r, alpha, a, b = self._unload_params('r', 'alpha', 'a', 'b')
        return 1. / (1 + (a / (b + frequency)) *
                     ((alpha + T) / (alpha + recency)) ** (r + frequency))
```

You can confirm this as follows:
```
pip download --no-binary :all: --no-dependencies lifetimes==0.9.0.0
tar xvf Lifetimes-0.9.0.0.tar.gz
```

Then look at the file `Lifetimes-0.9.0.0/lifetimes/fitters/modified_beta_geo_fitter.py`

**Comment by CamDavidsonPilon** [comment]
oof! how embarrassing!

**Comment by CamDavidsonPilon** [comment]
let me fix this in the new version being released (tonight I'll update)

**Comment by barrywhart** [comment]
No worries, we've all done something like this. :-)

Fixing it in the new version sounds fine. IIRC, it is difficult or impossible to replace a library version in PyPI once you've uploaded it.
