### ISSUE TITLE
How to calculate expected lifetime length?

### ISSUE THREAD

**Issue by limziwang** [CamDavidsonPilon/lifetimes#178]
I am following the example in the [readthedocs link](http://lifetimes.readthedocs.io/en/latest/Quickstart.html#the-gamma-gamma-model-and-the-independence-assumption), and I noticed that the 'time = 12' parameter is up to us to decide. How is this usually calculated?

Can someone please teach me how I should go about deriving this number?

Thank you!

```python
pd.DataFrame(
    ggf.customer_lifetime_value(
        transaction_prediction_model= bgf, #the model to use to predict the number of future transactions
        frequency= data['frequency'],
        recency= data['recency'],
        T= data['T'],
        monetary_value = summary_with_money_value['monetary_value'],
        time=12, # the lifetime expected for the user in months. Default: 12
        discount_rate=0.01 #  the monthly adjusted discount rate. Default: 0.01
))
```

**Comment by Tobiasv-b** [comment]
The time equals how long "lifetime" is for you to decide. Some authors, such as Blattberg, Malthouse and Neslin talk a bit about how many months in the future you should take into account. Kumar (2008) suggest a 36 month period, with some arguments as to why you should not have an actual lifetime timeperiod. It all comes down to the buying behavior of your industry.

See below source:
Blattberg, R.C., Malthouse, E.C. and Neslin, S.A., 2009. Customer Lifetime Value: Empirical Generalizations and Some Conceptual Questions. Journal of Interactive Marketing, 23(2), pp.157–168.

Kumar, V., 2008. Managing Customers for Profit: Strategies to Increase Profits and Build Loyalty. Prentice Hall Professional.

**Comment by limziwang** [comment]
can someone share how s/he went about calculating this? I mean, sounds like a chicken and egg problem to me: I'm using lifetimes to have a sense of a customer's lifetime spending, but I need to decide a number for a customer's expected lifespan.

**Comment by Tobiasv-b** [comment]
I don't believe there are any calculations to help you decide on what a "lifetime" is in months/years. Think about your industry - how long is a purchase cycle? once per day? once weekly? Once every 10 years? For instance car sales should have a much longer lifetime duration than say flight ticket sales in order to capture at least 2-3 purchase cycles. 

If the purchase cycle is fairly short, 36 months is probably a good expected lifespan as proposed by Kumar (2008, see above).
