### ISSUE TITLE
How does Customer_lifetime_value work?

### ISSUE THREAD

**Issue by Tobiasv-b** [CamDavidsonPilon/lifetimes#180]
Hi, I'm having trouble understanding the GammaGammaFitter function **customer_lifetime_value**.

In the [Lifetimes documentation](http://lifetimes.readthedocs.io/en/latest/Quickstart.html#estimating-customer-lifetime-value-using-the-gamma-gamma-model), the CLV of customer_id 1 is calculated to 1      140.096211 for time = 12 and discount_rate=0.01 used in the documentation.

Given that the conditional average expected profit is 24.658619, doesn't that assume that customer 1 will make ~140/25 = 5.6 purchases in the 12 coming months? Given that the customer made 2 repeat purchases in the calibration period, doesn't 5.6 seem too high?

Shouldn't CLV simply be equal to expected number of transaction in holdout period * conditional average expected profit, if ignoring the discount rate?

**Comment by stochastic1** [comment]
The 5.6 expected transactions is an accurate interpretation of the value and profit (discount rate doesn't have that much effect here). If I'm reading the example correctly, your expectation may not be that far off, what seems cognitively dissonant is how many transactions you'd expect. The holdout period is 121 days but the prediction is for the leading 12 months, or just over 2 months between transactions, which isn't far off from 2 transactions in the 4 months following the first transaction. 

Remember also that this is a GammaGamma model, which means we're explicitly rejecting the assumption that customers will follow a strictly-linear trend.

**Comment by Tobiasv-b** [comment]
Thanks for a quick reply @stochastic1, but isn't the holdout period of the cdnow-dataset 39 weeks?

**Comment by Tobiasv-b** [comment]
I've narrowed down my issue to the following:

The CDNOW dataset is split into 39 week calibration and 39 week holdout. In the [BTYD Walkthrough](https://cran.r-project.org/web/packages/BTYD/vignettes/BTYD-walkthrough.pdf), the actual purchases of customer 1 in the holdout period of 39 weeks is 1 purchase (x.star) as calculated in chapter 2.3 (page 8). The Pareto/NBD model gives an expected number of transactions of 1.455349, which is almost exactly what I get with the Lifetimes implementation of Pareto/NBD. 

39 weeks is 9.75 months, so if I use 10 (closest integer) in the lifetimes customer_lifetime_value function, I should presumably get a CLV value which is close to the gamma-gamma model * expected number of transactions (24.65 usd * 1.22 future purchases with bgf)? 

Using the below code, the customer_lifetime_value results in a CLV of 132 which can't possibly be correct? 

```
from lifetimes import BetaGeoFitter, ParetoNBDFitter
from lifetimes import GammaGammaFitter
import pandas as pd
from lifetimes.datasets import load_cdnow_summary_data_with_monetary_value
pd.set_option('expand_frame_repr', False)



summary_with_money_value = load_cdnow_summary_data_with_monetary_value()
summary_with_money_value.head()
returning_customers_summary = summary_with_money_value[summary_with_money_value['frequency']>0]

print(returning_customers_summary.head())

#GammaGammaFitter
ggf = GammaGammaFitter(penalizer_coef = 0)
ggf.fit(returning_customers_summary['frequency'],
        returning_customers_summary['monetary_value'])
#Adding a column with predicted monetary value
summary_with_money_value['monetary_value_gg'] = ggf.conditional_expected_average_profit( summary_with_money_value['frequency'],summary_with_money_value['monetary_value'])

#BetaGeoFitter
bgf = BetaGeoFitter(penalizer_coef=0.0)
bgf.fit(summary_with_money_value['frequency'], summary_with_money_value['recency'], summary_with_money_value['T'])
#Adding a column with expected number of transactions according to the BetaGeoFitter
summary_with_money_value['condexp_bgf'] = bgf.conditional_expected_number_of_purchases_up_to_time(39, summary_with_money_value['frequency'], summary_with_money_value['recency'], summary_with_money_value['T'])


#CLV
summary_with_money_value['CLV'] =	ggf.customer_lifetime_value(
									    bgf, #the model to use to predict the number of future transactions
									    summary_with_money_value['frequency'],
									    summary_with_money_value['recency'],
									    summary_with_money_value['T'],
									    summary_with_money_value['monetary_value'],
									    time = 10, # months
									    discount_rate=0.0 # monthly discount rate ~ 12.7% annually
									)

summary_with_money_value.head(6)

```

**Comment by CamDavidsonPilon** [comment]
I think the problem was that `customer_lifetime_value` assumed the `bgf` model was trained on days, but in the example above the frequency was weeks. I've added functionality to correct this:

```python
summary_with_money_value['CLV'] =   ggf.customer_lifetime_value(
                                        bgf, #the model to use to predict the number of future transactions
                                        summary_with_money_value['frequency'],
                                        summary_with_money_value['recency'],
                                        summary_with_money_value['T'],
                                        summary_with_money_value['monetary_value'],
                                        time = 10, # months
                                        discount_rate=0.0, # monthly discount rate ~ 12.7% annually
                                        freq="W" # This is new
                                    )
```

The CLV is now 33.11, which is more reasonable.
