### ISSUE TITLE
Advice for inverse frequency distribution

### ISSUE THREAD

**Issue by EamonKeane** [CamDavidsonPilon/lifetimes#189]
Thanks again for an excellent library. Works a charm on taxi trip customer data for customer loyalty.

I'm hoping to use this for a second purpose of predicting driver loyalty and after trying a few different fitters it doesn't seem to work. So if this is the wrong use of the data please let me know or if you could point me in the right direction that would be great.

I have a population of 1500 drivers over 20 months with the following distribution of trips.

<img width="410" alt="screen shot 2018-05-10 at 13 06 33" src="https://user-images.githubusercontent.com/1946655/39868931-a84b34b4-5453-11e8-9a0d-61d12c3d6135.png">

The models all fit some variety of this (penalizer_coef=0 for bgf, pNBD, mbgf):

<img width="400" alt="screen shot 2018-05-10 at 13 08 53" src="https://user-images.githubusercontent.com/1946655/39868936-aceb338e-5453-11e8-8e5c-72059559697f.png">

Thanks in advance.

**Comment by CamDavidsonPilon** [comment]
hm, interesting. At the surface, I don't know what might be happening. Are you able to share the data, even privately? If not, can you post the code you are using, and the parameters of a fitted model (for simplicity, can you just try BGF?)

**Comment by EamonKeane** [comment]
Thanks for helping. I've emailed you a link to a Jupyterlab instance with the data loaded up, maybe you can spot something.
