### ISSUE TITLE
Train/Test/Validate with BetaGeoFitter

### ISSUE THREAD

**Issue by lexykassan** [CamDavidsonPilon/lifetimes#192]
I am looking to do a train/test/validate on subsets of my data. Is there a means of using the existing functions for this? Maybe a variant of calibration_and_holdout_data?

**Comment by CamDavidsonPilon** [comment]
Hey @lexykassan, `calibration_and_holdout_data` does the train/test, so you may have to do some manual pre-processing on the original dataset to also include validate

**Comment by lexykassan** [comment]
Hey. Thanks for the quick response. To be clearer, I have already used the time-based validation on the training set. What I am looking for is cross-validation of different subsets of customers summarized in the same time period. e.g. how extensible is this model across the same time period but different observations? Is there a built-in capability for this?

**Comment by CamDavidsonPilon** [comment]
ah I see. You could hash & mod k the customer_ids from the original dataset into K subsets of the original dataset, and use that for k-fold validation. Ex: hash all ids, partition the ones that are 0 mod K. Put that smaller subset into `calibration_and_holdout_data` to get a split. Train on the K-1 other dataset using `summary_data_from_transaction_data`, and then predict on the smaller subset. Is that clear?

**Comment by lexykassan** [comment]
So are you saying that there is no way in the lifetimes package to apply the model to new data? Do you have to completely retrain the model every time you have a new customer? This seems like a substantial limitation.

**Comment by lexykassan** [comment]
I likely am confused. The examples I see in the docs are for the same set of customers with a train and test time period. How would one call the model itself to predict on a different set of data? For instance, in the docs there is self.predict that calls conditional expected purchases but it appears to only allow for predicting on one customer at a time. Could this be used to score an expected purchase count for all customers in a different data set? Theoretically the math wouldn't change - just the scale of calculation.

**Comment by CamDavidsonPilon** [comment]
For example:
```
bgf.fit(train['t'], train['freq'], train['r'])

# predict new orders on unseen customers, up to time 10
bgf.conditional_expected_number_of_purchases_up_to_time(10, test['t'], test['freq'], test['r'])
```

**Comment by lexykassan** [comment]
Ah, OK. It was not clear that the index value could be omitted there. Thank you. I will try that.
