### ISSUE TITLE
Trying to understand data used in the Quickstart example

### ISSUE THREAD

**Issue by jasper7zlh** [CamDavidsonPilon/lifetimes#193]
Hi there, 

Based on definitions of the three features &mdash; `frequency`, `recency` and `T` &mdash; for the data used in the example, the data should be focusing on customers who have made at least one purchase. But by looking at the DataFrame `summary_with_money_value` in the example:

![lifetimes data](https://user-images.githubusercontent.com/8279388/40077540-cc32a560-5836-11e8-91f5-6b02153d9c3c.PNG)

It looks that `frequency = 0`, `recency = 0` and `monetary_value = 0` happen at the same time. `monetary_value = 0` means such customer has not purchased yet to me, then `frequency = 0` makes sense, but how can I explain `recency = 0` and the value in `T` when `monetary_value = 0` given that first purchase is mentioned in definitions for both `recency` and `T`?

General questions below:

- Is `summary_with_money_value` the data for (A) **any customer** (definition will be registered user) no matter if they actually purchased or not, or is it only for (B) **true customers who actually purchased** at least once?
    - I guess it is (B), then what is `monetary_value = 0` in such case? Is the definition of `monetary_value` the monetary value coming from repeat purchases only (total value - value of 1st purchase)?

Thank you in advance.

**Comment by psygo** [comment]
This seems related to Issue #208.

We apparently don't use the first purchase when calculating the monetary value.

I think that having `monetary_value = 0` is actually a problem of the dataset. There might be purchases registered with `0.00` monetary value. Try getting a count of how many customers you have with `monetary_value = 0.00`, maybe that will help.
