### ISSUE TITLE
CLV calculation assumes underlying data uses "day" as period

### ISSUE THREAD

**Issue by cliffordlyon** [CamDavidsonPilon/lifetimes#194]
It seems as if here:

https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/utils.py#L417

that the CLV calculation is assuming the underlying summary information uses "day" as a time unit, and so makes adjustments to transform from days to months in the sum by incrementing by steps of 30. However, if the underlying data used "week", e.g., as in the CDNOW example, the CLV for 12 months would instead be calculated for 12 * 30 weeks or 7 years. Wouldn't it make more sense to have `t` simply be the periods, and let the user specify whether it is 12 months, or 52 weeks, or whatever they need?

**Comment by aprotopopov** [comment]
Hello @cliffordlyon.
I think there are no any restrictions to change it with flexible periods (day, month, etc..)
