### ISSUE TITLE
monetary_value

### ISSUE THREAD

**Issue by biaodianfu** [CamDavidsonPilon/lifetimes#196]
Hello, I don't quite understand how `monetary_value` is calculated in `summary_data_from_transaction_data()`.

```python
if monetary_value_col:

        # create an index of all the first purchases
        first_purchases = repeated_transactions[repeated_transactions['first']].index

        # by setting the monetary_value cells of all the first purchases to NaN,
        # those values will be excluded from the mean value calculation
        repeated_transactions.loc[first_purchases, monetary_value_col] = np.nan
        customers['monetary_value'] = repeated_transactions.groupby(customer_id_col)[monetary_value_col].mean().fillna(0)
        summary_columns.append('monetary_value')
```

Is there anyone who can help to explain why setting the `monetary_value` cells of all the first purchases to `NaN`? 

Why not use this:

```sql
SUM(PRICE_TOTAL)/COUNT(distinct TRANS_DATE) AS monetary_value

(CASE 
    WHEN COUNT(distinct TRANS_DATE)-1=0 THEN 0 
    ELSE SUM(PRICE_TOTAL)/COUNT(distinct TRANS_DATE) END) AS monetary_value
```

**Comment by andrewng88** [comment]
Apologies borrowing this thread to clarify about Monetary Value. I read that it can be the total ( sum of qty x unit price ) but for lifetimes we're using mean instead . Meaning total sales divided by unique date assuming date is not NULL. I tried to do a manual calculation but I was not able to tally the Monetary Value as per image. 

![image](https://user-images.githubusercontent.com/44232530/59824081-b7214600-9362-11e9-818b-9f65b4f18121.png)

May I trouble you guys to help explain? Thanks in advance.
