### ISSUE TITLE
Is there any plan to develop new models in the package?

### ISSUE THREAD

**Issue by snaillians** [CamDavidsonPilon/lifetimes#198]
Since there are several variants later despite of four models listed in the package.  For example,  the hierarchical bayes  extension to Pareto/NBD model,  which can leverage MCMC to estimate individual parameters for lambda and mu and use customer's label.  Do you have plan to add these new model in the package in the future?

**Comment by CamDavidsonPilon** [comment]
Hey there, I have no immediate plans, but I am open to PRs that add new models.

**Comment by zscore** [comment]
@snaillians if you have some papers, I think it would be nice to implement some of these models.

**Comment by nathaniel-md** [comment]
Hi, models like the implementations in BTYD in R would be super cool! It would be great to be able to take covariates into account.
https://github.com/mplatzer/BTYDplus#implemented-models

Especially the paper by Makoto Abe 2009: "Counting your customers one by one: A hierarchical Bayes extension to the Pareto/NBD model." Marketing Science 28.3 (2009): 541-553.

Thanks so much!

**Comment by nathaniel-md** [comment]
https://cran.r-project.org/web/packages/BTYDplus/vignettes/BTYDplus-HowTo.pdf

**Comment by psygo** [comment]
Boy, I wish I have some time someday to implement this...

**Comment by nathaniel-md** [comment]
Haha! I could have taken the initiative to implement it as well! 😂 Maybe I still will!

**Comment by ZhenoSan** [comment]
I'm probably really late but has there been a successor to this that has implemented models with covariates like Abe's Pareto NBD ?

**Comment by wallshadow179** [comment]
Following up on Zheno's and nathaniel's comment has anybody had a chance to implement covariates into the library? Specifically "Counting your customers one by one: A hierarchical Bayes extension to the Pareto/NBD model." Marketing Science 28.3 (2009): 541-553."

**Comment by wallshadow179** [comment]
> Haha! I could have taken the initiative to implement it as well! 😂 Maybe I still will!

Please do! You'd be doing me a solid one I don't want to go down the R route.
