### ISSUE TITLE
Confidence/prediction intervals?

### ISSUE THREAD

**Issue by zscore** [CamDavidsonPilon/lifetimes#201]
Let's say you want to compare CLV across two different populations. It'd be nice to do this! Or get confidence intervals for predicted purchases in the future. Are there any papers out there that show how to do this?

**Comment by rhydomako** [comment]
One option is to bootstrap your CLV metrics. There are also some MCMC implementations that I think can accommodate prediction intervals (see #123).

**Comment by zscore** [comment]
Cool thanks for this! Yeah there are also some routines in BTYD https://cran.r-project.org/web/packages/BTYDplus/index.html that do this, but it doesn't scale to the amount of data  have.

**Comment by zscore** [comment]
Cool I have some code written that bootstraps prediction intervals for the models, so I might open up a pull request for this. :)

**Comment by zscore** [comment]
hey @CamDavidsonPilon  wanted to ping you again about the bootstrapping

**Comment by CamDavidsonPilon** [comment]
I think I have another solution using `autograd`: we (fingers-crossed) can autodifferentiate the log-like and get the hessian - this will give us std. errors for the parameters. We can then use the delta-method to get std. errors for any transformations of the parameters.

**Comment by CamDavidsonPilon** [comment]
see #251 for a start to this. Getting the hessian information out is an obvious next step.
