### ISSUE TITLE
Should we be fitting parameters in the log space?

### ISSUE THREAD

**Issue by zscore** [CamDavidsonPilon/lifetimes#202]
In the R version of the BGBB fitter, they log the parameters before using L-BFGS-B to estimate it: https://github.com/cran/BTYD/blob/master/R/bgbb.R#L79-L84

**Comment by CamDavidsonPilon** [comment]
huh, interesting, this could make estimation more stable....

**Comment by zscore** [comment]
yeah, I don't know how we would answer the question of which of these would be better though outside of some simulation work? I will say in practice though I frequently have parameters go into invalid regions. or we could ask the R developers on BTYD why they chose to use log parameters.

**Comment by CamDavidsonPilon** [comment]
This is being implemented as part of #251, I think it does improve convergence generally.
