### ISSUE TITLE
ValueError: level name Customer Number is not the name of the index

### ISSUE THREAD

**Issue by BadrulAlom** [CamDavidsonPilon/lifetimes#204]
For some reason my transaction_data worked with the first data extraction example, but when I tried the hold out method it failed with the error: **ValueError: level name Customer Number is not the name of the index**

My ID is 'customer number' and this is a text field.
For reference, here is the line of code that worked fine
summary = summary_data_from_transaction_data(transaction_data, 'Customer Number', 'DAXDate', observation_period_end='2018-01-01')

**Error output:**
```
 line 76, in ProcessSalesData
    summary_cal_holdout = calibration_and_holdout_data(transaction_data, 'Customer Number', 'DAXDate',calibration_period_end='2017-10-01',observation_period_end='2017-07-01' )
  
line 91, in calibration_and_holdout_data
    .groupby(level=customer_id_col).agg(['count'])
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\core\generic.py", line 6659, in groupby
    observed=observed, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\core\groupby\groupby.py", line 2152, in groupby
    return klass(obj, by, **kwds)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\core\groupby\groupby.py", line 599, in __init__
    mutated=self.mutated)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\core\groupby\groupby.py", line 3177, in _get_grouper
    'index' % level)
ValueError: level name Customer Number is not the name of the index
```

**Comment by extrospective** [comment]
Your comment has customer number in lower case and your code in upper case.  It would be helpful if it were consistent.  Can you add in the dataframe.info() results to confirm?

**Comment by ariisio** [comment]
Hello, was there solution for this? Struggling with a similar issue and can't find a solution

**Comment by BadrulAlom** [comment]
No I don't think I did solve it though I can't remember as I've moved on from it. I normally post solutions if I do solve something though. Definitely try doing a simple test with two rows of data or something.

**Comment by ariisio** [comment]
My guess is that it has something to do related to way the column names are handled. I have two similar solutions side by side. Solution A is working just fine. In solution A we're getting the transaction data by using Pandas read_sql.
Solution B has this error, but we're not using the read_sql here. I guess read_sql automatically fetches the column names when reading from DB. I'm adding those column manually using:
df.columns = ['customer_id', 'datetime']

**Comment by CamDavidsonPilon** [comment]
I looked at the source code, and couldn't understand a way for this to occur. @ariisio if you find a solution or any more evidence, please report back and I'll merge a fix!

**Comment by ariisio** [comment]
Problem solved. Even though the error message was related to indexes, the error itself was caused by invalid datetime values in calibration- and observation_period_end parameters.
So no issues in the code!

**Comment by ariisio** [comment]
Problem solved. At least in my case, issue was related to the date value in the observation_period_end parameter.
I had a script which imported data between two different dates and I used this "end" date to also define the observation_period_end.
However, if the latest timestamp in the data set was less (earlier) than the observation_period_end, I received the error. So in my case, I just didn't have any data from the time observation period should end.
Thank you for your support.

**Comment by CamDavidsonPilon** [comment]
A better error will be raised in v0.11.0
