### ISSUE TITLE
plot_period_transactions with low "s" parameter 

### ISSUE THREAD

**Issue by JJDS0** [CamDavidsonPilon/lifetimes#207]
Hello,
I have problem with plot_period_transactions for estimated Pareto/NBD parameters. 
Parameters:
```
OrderedDict([('r', 1.2264068998969124),
             ('alpha', 12.16294151917949),
             ('s', 4.6377925306795664e-10),
             ('beta', 32.52434379061591)])
```

I get this error message:
```
C:\ProgramData\Anaconda3\lib\site-packages\lifetimes\generate_data.py:105: RuntimeWarning: divide by zero encountered in double_scalars
  time_of_death = stats.expon.rvs(scale=1. / mu)
```

I think this issue comes with "s" parameter, which is extreamly low. Could you confirm it? Is it bug or I do something wrong?

**Comment by JJDS0** [comment]
I've used [UCI online retail](https://archive.ics.uci.edu/ml/datasets/online+retail)

I aplied it to cohort - customer which buy first time durring first 3 months. 
I tried also other range of date but always s is low.

The same date was used in [here](https://www.keetan.me/clv/) and in R 
The author also get low s. (2.29118710^{-5})

**Comment by CamDavidsonPilon** [comment]
Are you truncating the transactions at 3 months? Or summarizing the customers, and then truncating?

**Comment by JJDS0** [comment]
I choose customers which buy first time durring first 3 months.
Next step is filtring dataset by customerID of them.
Methodology like in CDNOW dataset
> "dataset contains the entire purchase history up to the end of June 1998 of the cohort of 23,570 individuals who made their first-ever purchase at CDNOW in the first quarter of 1997."


I tried also other cohort or just all data but always s is very low

I upload notebook:
https://github.com/JJDS0/training/blob/master/lifetimes.ipynb

**Comment by JJDS0** [comment]
@CamDavidsonPilon  any ideas?

**Comment by CamDavidsonPilon** [comment]
the `s` parameter controls how fast people die, so I would do some summary statistics on your training data. Perhaps there is something wrong there.

**Comment by albrzykowski** [comment]
Hi, @CamDavidsonPilon
Do you have any conclusions why CLV is wrongly calculated for this dataset. Have you made any statistics that can explain the low value of **s**?

Kind regards,
Leszek
