### ISSUE TITLE
question about "Conditional expected number of purchases up to time"

### ISSUE THREAD

**Issue by yanwu0105** [CamDavidsonPilon/lifetimes#209]
in this function "BetaGeoFitter.conditional_expected_number_of_purchases_up_to_time"

if  t =1,  result = 0.7
How to explain the result?
is 0.7 times will buy in the next period?
or 
 the next period have 0.7 probability will buy ?

and how to explain  the t= 2 ?

**Comment by CamDavidsonPilon** [comment]
0.7 is the expected value. If you had an infinite pool of customers (with the same characteristics), and you watched them for 1 unit of time, then the average purchases per person would be ~0.7.

**Comment by yanwu0105** [comment]
@CamDavidsonPilon  thank you to answer me. 
but what is an infinite pool of customers?
and what is with the same characteristics?

is this function to measure one customer's expected purchasing value?

**Comment by Trollgeir** [comment]
What he means is that if you had 1.000 customers and they all behaved in the same way, you'll most likely get 700 purchases between now and 24 hours ahead (if t is days). 

If you want to estimate the number of purchases for all your customers within the 24 hours, simply sum up all their expected purchases.
