### ISSUE TITLE
Monetary value estimation

### ISSUE THREAD

**Issue by luke14free** [CamDavidsonPilon/lifetimes#21]
Hi @CamDavidsonPilon I am working on implementing a few monetary values estimations as described in http://www.essec.edu/faculty/showDeclFileRes.do?declId=8555&key=Publication-Content (Gamma/Gamma submodel and Pareto/Independent). Anyways to fit your framework these models require a few relevant changes (e.g. adding monetary values for transaction/summaries, changing a few fitting methods etc..). So before doing too much work on the current structure of the library I wanted to know what was your take on the idea of adding monetary models to lifetimes.

**Comment by CamDavidsonPilon** [comment]
:+1: love it. Can you do it in smaller PRs rather than one larger one?

**Comment by luke14free** [comment]
Sure, I will try my best. Will keep you posted.
