### ISSUE TITLE
SQL operations based on ('r', 'alpha', 'a', 'b')

### ISSUE THREAD

**Issue by Trollgeir** [CamDavidsonPilon/lifetimes#210]
I already have the RFM generation streamlined in my database. However I'm interested in taking it to the next level..

Does anyone know how feasible it is to do SQL table updates based on the parameters derived from the BetaGeoFitter? I'm aiming to do daily updates of predictions on customer data in standard SQL operations to avoid hassle with python/container jobs in my ETL.

Specifically I'm referring to the function `conditional_expected_number_of_purchases_up_to_time()` for the `BetaGeoFitter`.

**Comment by CamDavidsonPilon** [comment]
That's an interesting question. A lot of the code in `conditional_expected_number_of_purchases_up_to_time` is there for stability reasons in the general case. If have _reasonable_ parameters and your distribution of data is also _reasonable_ (I am leaving it up to you to define that, but no/few outliers, moderately sized values, etc.), then the code can be simplified quite a but. However, you still need to implement `hyp2f1` in SQL, or approximate it somehow. I haven't seen that done.
