### ISSUE TITLE
Can I use negative monetary_value  to fit GammaGammaFitter & calculate CLV?

### ISSUE THREAD

**Issue by yanwu0105** [CamDavidsonPilon/lifetimes#211]
In my project, I will use the net profit to be monetary_value .
So monetary_value  have some negative, but it will be error.
how can I use negative monetary_value  to fit GammaGammaFitter & calculate CLV?

**Comment by CamDavidsonPilon** [comment]
I don't think so - an underlying Gamma distribution assumes positive random variables. One hack could be to shift all your observations by the minimum profit value plus some epsilon (so everything is positive), fit the model, and then "reverse" the shift when you predict new profits (subtract by the minimum and epsilon).

**Comment by Trollgeir** [comment]
Are you able to get the raw profits for monetary_value instead? I think it could be cleaner to calculate the net profit by post-processing the CLV.

**Comment by yanwu0105** [comment]
Yes, I use raw net profits. 
In our office, we will use raw cost to calculate profits.
so, the net profit will have negative. 
so can i use it to calculate  CLV?

**Comment by yanwu0105** [comment]
@CamDavidsonPilon  @Trollgeir  thank you to answer me .
I want to check the `customer_lifetime_value` the CLV is average CLV?
so if t=12, the total CLV will be *12 ?

**Comment by Trollgeir** [comment]
`t=12` for `customer_lifetime_value` is 12 months, so 30*12 days. 
The CLV result is how much money you expect the customer to spend over those 12 months.

**Comment by yanwu0105** [comment]
@Trollgeir Thanks you, I have a new question.
`conditional_expected_average_profit` 
This is to calculate the profit in the period?
this is average or total?

**Comment by Trollgeir** [comment]
From what I understand it, it is an estimate of the average monetary value for transactions on a customer level. In other words, for each customer, you can estimate how much money they will give per transaction.

This is all under the assumption that there is no correlation between frequency and monetary value for transactions: https://lifetimes.readthedocs.io/en/master/Quickstart.html#the-gamma-gamma-model-and-the-independence-assumption

**Comment by prabhathn** [comment]
Is there an alternative model recommended for when there may be a correlation between frequency and monetary value?

**Comment by vincent-lange** [comment]
you can try to learn your own relationship, most of the time linear or some simple exponential term will do, and update the distributions that way, it's not perfect though

**Comment by psygo** [comment]
If you want more information about the Gamma-Gamma Model, you can check out Prof. Bruce Hardie's notes, especially [this one](http://brucehardie.com/notes/025/).

**Comment by tamirbennatan** [comment]
@vincent-lange 

> you can try to learn your own relationship, most of the time linear or some simple exponential term will do..

What relationship are you describing? Between something like: `avg_transaction_profit ~ frequency + monetary_value` ? 

Or something else?
