### ISSUE TITLE
The two function have any different??

### ISSUE THREAD

**Issue by yanwu0105** [CamDavidsonPilon/lifetimes#214]
In BG/NBD or Pareto/NBD have two function ：
1、conditional_expected_number_of_purchases_up_to_time
2、expected_number_of_purchases_up_to_time 
have any different？

If I want to check the models' error about "frequency" between actual and prediction.
which function should I use?

**Comment by CamDavidsonPilon** [comment]
Hello, the conditional one accepts information like frequency, recency and age to get a more accurate estimate.

**Comment by yanwu0105** [comment]
@CamDavidsonPilon  So can I use `conditional_expected_number_of_purchases_up_to_time` this function to measure the past period's frequency?

**Comment by CamDavidsonPilon** [comment]
@yanwu0105 I'm not sure what you mean, can you provide an example?

**Comment by yanwu0105** [comment]
Just like this:
frequency recency T monetary_value
customer_id
1 2 30.43 38.86 22.35
2 1 1.71 38.86 11.77
6 7 29.43 38.86 73.74
7 1 5.00 38.86 11.77
9 2 35.71 38.86 25.55

In `conditional_expected_number_of_purchases_up_to_time` assume t = T ,  Can I use that to measure the past period's frequency?
