### ISSUE TITLE
in utils, _customer_lifetime_value is assuming the model is always a daily model

### ISSUE THREAD

**Issue by aggie13** [CamDavidsonPilon/lifetimes#215]
```python
    for i in range(30, (time * 30) + 1, 30):
        # since the prediction of number of transactions is cumulative, we have to subtract off the previous periods
        expected_number_of_transactions = transaction_prediction_model.predict(i, frequency, recency, T) - transaction_prediction_model.predict(i - 30, frequency, recency, T)
        # sum up the CLV estimates of all of the periods
        df['clv'] += (monetary_value * expected_number_of_transactions) / (1 + discount_rate) ** (i / 30)
```
This seems assumes the  transaction_prediction_model is a daily model (as freq=D)? so if my model is using freq=M then the whole calculation would be wrong. Am I right?

**Comment by yanwu0105** [comment]
I have the same question!!!

**Comment by CamDavidsonPilon** [comment]
I guess not - yea, I'm open to accepting PRs if you want to update the code :)

**Comment by xingzhex** [comment]
If you do not care about the 'discount_rate', you could simply calculate clv as the product of the adjusted monetary value and the transaction number prediction. This has no reliance on days.
`adjusted_monetary_value = GammaGammaFitter.conditional_expected_average_profit(
            frequency, monetary_value)
clv = transaction_prediction_model.predict(t, frequency, recency, T).multiply(adjusted_monetary_value
)

**Comment by Kara035** [comment]
is there any ways to adjust the discounted value function, so that I can use it for weekly or monthly model?

**Comment by CamDavidsonPilon** [comment]
Not with a change in the source code, I think. 

> I guess not - yea, I'm open to accepting PRs if you want to update the code :)
