### ISSUE TITLE
expected_cumulative_transactions hardcodes datetime_col as 'date'

### ISSUE THREAD

**Issue by mps-ds** [CamDavidsonPilon/lifetimes#217]
I think there's a bug in the function `expected_cumulative_transactions` that prevents causes an error if the datetime_col in the transactions dataframe is not 'date'. It also comes up if you try to run the `plot_cumulative_transactions` function. You can generate the error by running the following:

```
from lifetimes import ModifiedBetaGeoFitter
from lifetimes.datasets import load_transaction_data
import lifetimes.plotting as ltplt
from lifetimes.utils import summary_data_from_transaction_data, expected_cumulative_transactions

transactions = load_transaction_data().rename(columns={'date':'Date'})
summary = summary_data_from_transaction_data(transactions,'id','Date')
mbg = ModifiedBetaGeoFitter()
mbg.fit(summary['frequency'],summary['recency'],summary['T'])
expected_cumulative_transactions(mbg, transactions, 'Date', 'id', 100)
```

This returns the error "Key Error: 'date'", which is triggered by line 487 in utils.py:
```
first_trans_size = first_transactions.groupby('date').size()
```

It looks to me as though 'date' is hardcoded on lines 487 and 499. I think in both cases it should use datetime_col instead, although I am not certain about line 499.

The function works fine if you run:
```
expected_cumulative_transactions(mbg,
                                 transactions.rename(columns={'Date':'date'}),
                                 'date', 'id', 100)
```

**Comment by jchao12** [comment]
this indeed looks like a bug, ran into the same issues
