### ISSUE TITLE
Add model name used in generated plots

### ISSUE THREAD

**Issue by Samanvay96** [CamDavidsonPilon/lifetimes#222]
## Context 
Currently, I'm using three models for CLV analysis and generating `calibration_purchases_vs_holdout_purchases` for comparison. I thought that it might be a good idea to display the model name in the chart title for additional differentiation. Any thoughts?

If this sounds good. I will go ahead and make the necessary changes.

**Comment by CamDavidsonPilon** [comment]
Heya, I think I know what you mean, but do you have a screenshot of your idea?

**Comment by psygo** [comment]
We could and might do that in the future, but you already can kind of do that by customizing the title of the plot. You could also use `label`s and `plt.legend()`.

**Comment by nicknelson1021** [comment]
I am interested in this as well. I forked the library and made the update in my own copy. @psygo, could you provide an example of how we can customize the title of the plot through the lifetimes library as-is? Thank you.

**Comment by nicknelson1021** [comment]
@Samanvay96 , I got it to work with the following code: 
```
plot_calibration_purchases_vs_holdout_purchases(
    model=bgf_monthly_train,
    calibration_holdout_matrix=cal_holdout_monthly).title.set_text('hi')
```
