### ISSUE TITLE
Scaling models?

### ISSUE THREAD

**Issue by Benski3030** [CamDavidsonPilon/lifetimes#223]
I had a question about training and applying these models to larger sets of customer data.  In the examples and cited papers, the model is trained on a given cohort of customers, typically defined by customers acquired during a set unit of time (i.e. all customers who made their first purchase during the month of December 2014 etc.)  However, is the expectation then that a trained model with good performance is then applied to all future cohorts? or does each new cohort need to have its own model fit?

**Comment by CamDavidsonPilon** [comment]
Up to you! Both are applicable - the latter option is more flexible of course, but requires more management of models. However, with the latter option can also use https://andrewgelman.com/2005/03/07/the_secret_weap/ to observe how parameters are changing over time.
