### ISSUE TITLE
weekly example code for plot_incremental_transactions

### ISSUE THREAD

**Issue by Kara035** [CamDavidsonPilon/lifetimes#224]
Hi,
When I try to use `plot_incremental_transactions` in weekly frequency, the plot doesn't look right.
The transaction data that I put in is daily.
Does the transaction data need to be grouped as weekly frequency before I put it into the function?
The calibration period is 101 week, and the test period is another 101 week.
Below is the code I use for the plot:
```python
plot_incremental_transactions(bgd, transaction_data,'date', 'id', 101, 101, freq='W',
                              title='Tracking Weekly Transactions',
                              xlabel='week', ylabel='Transactions'):
```

**Comment by aprotopopov** [comment]
Hi, @Kara035 
Could you show your plot and what is incorrect on it?

**Comment by Kara035** [comment]
Hi,
first thing that I figured out in the function is the t in the function needs to be the calibration+holdout, not just the calibration period. 
However, I still get quite different results based on the incremental plot evaluation, using the same data. Would you please help?
The attachments are the two incremental plots I have from the two aggregation models.
![dailyplot](https://user-images.githubusercontent.com/43381551/49044460-d58fdc00-f19b-11e8-9f27-5c71c677fbee.JPG)
![weeklyplot](https://user-images.githubusercontent.com/43381551/49044461-d58fdc00-f19b-11e8-9a3a-a488e028cf50.JPG)

**Comment by aprotopopov** [comment]
@Kara035 sorry for the long response. On your first plot predicted transactions line looks fine as far as I understand your data. Does the issue occur with the second one? Are you using the same model for both plots?

**Comment by psygo** [comment]
Check out PR #287, by @isaachaberman, maybe that will help.
