### ISSUE TITLE
Intuition/theory behind assuming max(T) in `conditional_probability_alive_matrix `

### ISSUE THREAD

**Issue by clausherther** [CamDavidsonPilon/lifetimes#227]
I noticed the calculation for `conditional_probability_alive_matrix` uses the maximum customer age for parameter `T` in `conditional_probability_alive`. I couldn't find any reference to that in the various papers and don't really grasp the intuition behind that. Are we saying here, calculate P(alive) for all combinations of recency and frequency, assuming all customers have been with us from the beginning?

```python
max_frequency = max_frequency or int(self.data['frequency'].max())
max_recency = max_recency or int(self.data['T'].max())

return np.fromfunction(
    self.conditional_probability_alive,
    (max_frequency + 1, max_recency + 1),
    T=max_recency
).T
```

**Comment by CamDavidsonPilon** [comment]
Heya, it's there so the matrix is finite, that is, if the user leaves it blank in the args, then we have some "sensible" max value. Does that make sense?

**Comment by clausherther** [comment]
Hey! (Happy US Thanksgiving!)
It makes sense why need the parameter to be constant for the calculation. I'm having a hard time understanding how to interpret the results (and the plot from `plot_probability_alive_matrix`) given that we don't plot the effect of customer age as well. 
In practice,  calculating `conditional_probability_alive` using actual customer ages leads to very different results.

**Comment by TomasKeller** [comment]
Hi
As clausherther is asking, are we assuming that all customers have been with us from the beginning? And does this mean that we will filter out all customers with time < max time? 
Can we draw any conclusion on new customers in this plot or are there other ways to get p(alive) for new customers?

**Comment by psygo** [comment]
I think the way that function is coded now *does* make sense, but we should give the user the opportunity of specifying the `T` parameter also, shouldn't we?
