### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe Error

### ISSUE THREAD

**Issue by tejaser** [CamDavidsonPilon/lifetimes#230]
I am trying to follow the "A Tutorial Using Probabalistic Programming and PyMC" tutorial.  my environment is as below:
OS: Windows 10
Python: 3.6.7
I am using Anaconda Distribution and when running the Jupyter notebook I am getting

"BrokenPipeError: [Errno 32] Broken pipe" error.

I tried turning off the firewall, changing the sample size, but the error still remains.  Any suggestions?

**Comment by CamDavidsonPilon** [comment]
Does this have anything to do with _lifetimes_?

**Comment by tejaser** [comment]
sorry @CamDavidsonPilon  my bad.  The issue was with pymc3 and not lifetimes.
