### ISSUE TITLE
Can anybody explain the 'plot_calibration_purchases_vs_holdout_purchases' plots ?

### ISSUE THREAD

**Issue by QaisarRajput** [CamDavidsonPilon/lifetimes#232]
I have been trying to understand the following plot in the [docs](https://lifetimes.readthedocs.io/en/master/Quickstart.html)

![bg-plot](https://user-images.githubusercontent.com/11134951/49371468-58271700-f719-11e8-81d6-d1886621709c.png)

What are these "Purchases in the calibration period"(x-axis). and how are they in [0, 5] scale. same goes for the (y-axis). is it an aggregated form of the data?

Additionally, there is a [article ](https://towardsdatascience.com/whats-a-customer-worth-8daf183f8a4f) which also discusses the same example, and states 

> In this plot, we separate the data into both a in-sample (calibration) and validation (holdout) period. The sample period consists the beginning to 2011–06–08; the validation period spans from 2011–06–09 to 2011–12–09. **The plot groups all customers in the calibration period by their number of repeat purchases (x-axis) and then averages over their repeat purchases in the holdout period (y-axis)**. 

Please simplify it for my understanding hopefully with an example

**Comment by aprotopopov** [comment]
On x-axis you have your periods which you could set via `n` argument to [`plot_calibration_purchases_vs_holdout_purchases`](https://github.com/CamDavidsonPilon/lifetimes/blob/fa58e1a99e6fd1fe8a21b7a2a7502a605b514cf9/lifetimes/plotting.py#L73). Try to copy-paste code from documentation and play a bit in jupyter notebook.  Probably that plot is cut on 5 with old matplotlib version and should be updated in docs. Below I attached what I've got for matplotlib=2.1.2
![image](https://user-images.githubusercontent.com/6563045/52460448-6b23f080-2b7b-11e9-9e28-dfac81cb1ff7.png)

**Comment by QaisarRajput** [comment]
Great. i answers my question. Thanks
