### ISSUE TITLE
calculate_alive_path() function needs to be changed

### ISSUE THREAD

**Issue by arkahome** [CamDavidsonPilon/lifetimes#234]
The line :- 
customer_history['transactions'] = customer_history['transactions'].apply(lambda t: int(t > 0))

 in calculate_alive_path needs to be changed to :- 

customer_history['transactions'] = customer_history['transactions']

 Otherwise multiple transactions for a days are also getting computed as 1. Thus skewing the alive probability.

Thanks!!

**Comment by CamDavidsonPilon** [comment]
I think that's the expected behaviour - if you wanted more granular purchases, the way to do that is to change the `freq` to hourly (for example)
