### ISSUE TITLE
Conditional Probability  Alive is Wrong when frequency = 0, recency = 0.

### ISSUE THREAD

**Issue by vruvora** [CamDavidsonPilon/lifetimes#239]
This seems wrong to me because this will output 1 for customers who have had one purchase a long time ago, but get 0 frequency due to one purchase given how `summary_df_from_transaction_data` is designed. 
https://github.com/CamDavidsonPilon/lifetimes/blob/2504445ba7125fe7179daf05f2700c5e38673aac/lifetimes/fitters/beta_geo_fitter.py#L252

**Comment by alexzzkk** [comment]
This is the shortcoming of the model.

[Computing P(alive) Using
the BG/NBD Model
](http://www.brucehardie.com/notes/021/palive_for_BGNBD.pdf)

> We note that P(alive) = 1 for a customer who made no purchases in
> the interval (0, T]; this follows from the model’s assumptions that death
> occurs after a purchase and that customers are alive at the beginning of the
> observation period. Those interested in the P(alive) metric may view this
> as a shortcoming of the model.
