### ISSUE TITLE
Historical CLV plots

### ISSUE THREAD

**Issue by sophia-wright-blue** [CamDavidsonPilon/lifetimes#242]
thanks for releasing this amazing repo! I'd greatly appreciate any help/guidance making Historical CLV plots for the users. So make a plot of the change in CLV over time from a dataset for each user. Thanks,

**Comment by CamDavidsonPilon** [comment]
Once you've fitted a CLV model (likely GammaGamma model), you could replicate the logic that is used in [`plot_history_alive`](https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/plotting.py#L313), which calls [`calculate_alive_path`](https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/utils.py#L265). There would be need to be some data munging beforehand, but the call here: https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/utils.py#L311 would be changed to call the CLV function here: https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/fitters/gamma_gamma_fitter.py#L178

Does that make sense?

**Comment by sophia-wright-blue** [comment]
thanks so much @CamDavidsonPilon , i'm gonna give that a shot,
