### ISSUE TITLE
Incorrect Frequency

### ISSUE THREAD

**Issue by rushdishams** [CamDavidsonPilon/lifetimes#244]
Hi. In my transactions data, I have the following purchase history for a user with id `4125`

```
4125, 2018-04-24  7:19:25 PM
4125, 2018-04-24  8:13:28 PM
4125, 2018-05-24  4:00:01 AM
```
When I am using 
`summary = summary_data_from_transaction_data\
(df, 'user_id', 'created_at', observation_period_end='2019-01-31')`, I get:
```
user_id | frequency | recency | T
4125 | 1.0 | 30.0 | 282.0
```
Shouldn't be the frequency 2 in this case although the user purchased twice in her first day?

**Comment by vincent-lange** [comment]
it's about capturing *repeat* purchases I guess

**Comment by rushdishams** [comment]
Hi @vincent-lange , Thank you. In that case, is there any reference that addresses this issue of omitting all first-day purchases and its effect (if any)?

**Comment by CamDavidsonPilon** [comment]
Specifically, we measure a binary purchases per unit time, and drop the first observation (so as to measure repeat purchases). This is assuming that your time units are granular enough. In your case, you probably want a smaller unit of time (like hours).


I don't think there are any references, an analysts inference is identical, given you satisfy the above.
