### ISSUE TITLE
Issue in summary_data_from_transaction_data function

### ISSUE THREAD

**Issue by abhtpt** [CamDavidsonPilon/lifetimes#245]
function summary_data_from_transaction_data is not working for new Pandas version 0.24.0 and 0.24.1,  It is having difficulty in calculation of Recency and T , basically it is not  able subtract  between series data type and date type, It works well with the version 0.23.4

**Comment by CamDavidsonPilon** [comment]
Thanks for the heads up. Can you post the stack trace too?

**Comment by CamDavidsonPilon** [comment]
This is fixed in master: 
```
   pip install --upgrade --no-deps git+https://github.com/CamDavidsonPilon/lifetimes.git
```
