### ISSUE TITLE
Issue in plot_history_alive 

### ISSUE THREAD

**Issue by hmikelee** [CamDavidsonPilon/lifetimes#249]
Dear Cameron,

It looks like there is another casting issue for newer version of python/pandas

plot_history_alive failed with TypeError : can't multiply sequence by non-int of type 'numpy.float64'
```
Traceback as follows:
TypeError                                 Traceback (most recent call last)
/mnt/efs0/CLV/quickstart/qt.py in <module>()
    223     best_T = data.ix[i]['T']+31 #add a month
    224     best_trans = trans_data[trans_data[customer_id_column_name] == i]
--> 225     plot_history_alive(bgf, best_T, best_trans, date_column_name, freq='D', ax=ax)
    226     ax.set_title('ID: '+str(i))
    227     plt.xticks(rotation=25)

~/anaconda3/lib/python3.6/site-packages/lifetimes/plotting.py in plot_history_alive(model, t, transactions, datetime_col, freq, start_date, ax, **kwargs)
    357
    358     # plot alive_path
--> 359     path = calculate_alive_path(model, transactions, datetime_col, t, freq)
    360     path_dates = pd.date_range(start=min(transactions[datetime_col]), periods=len(path), freq=freq)
    361     plt.plot(path_dates, path, '-', label='P_alive')

~/anaconda3/lib/python3.6/site-packages/lifetimes/utils.py in calculate_alive_path(model, transactions, datetime_col, t, freq)
    300
    301     extra_columns = t + 1 - len(purchase_history)
--> 302     customer_history = pd.DataFrame(np.append(purchase_history, [0] * extra_columns), columns=['transactions'])
    303     # add T column
    304     customer_history['T'] = np.arange(customer_history.shape[0])

TypeError: can't multiply sequence by non-int of type 'numpy.float64'

the version of python and pandas as follows:

In [1]: pd.show_versions(as_json=False)
   ...:
```

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.93-41.60.amzn1.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.1
pytest: 3.3.2
pip: 19.0.2
setuptools: 39.2.0
Cython: 0.27.3
numpy: 1.15.1
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.6.6
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.2.2
openpyxl: 2.4.10
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml.etree: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.9
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

Thank you very much for your help

**Comment by zbazanowski** [comment]
The issues is closed without any solution? Not even a comment?

**Comment by CamDavidsonPilon** [comment]
Yea not sure why I closed this. Is the problem still happening?

**Comment by zbazanowski** [comment]
Yes, I have encountered the issue yesterday. 

Let me tell you I appreciate very much everything you do for this community. 


Yours Sincerely
Zbynek Bazanowski

**Comment by zbazanowski** [comment]
Yes, the issue still persists even  after I've reinstalled my environment.

**Comment by CamDavidsonPilon** [comment]
Can you provide a reproducible example?

**Comment by zbazanowski** [comment]
First, l have verified that a single command
`plot_history_alive(bgf, cust.T, cust_transd, 'Date', freq='D')`
displays the plot I've expected. **Conclusion 1**: Printing a single plot works.

And now, before presenting the real issue, I should reveal a snippet of data I am using (source: http://kpei.me/blog/?p=659):
```
cust_id = 10920
trans_data.loc[trans_data['Customer ID'] == cust_id].head(4)
```

```
Customer ID	Date	Subtotal	State	Country
14237	10920	2013-10-21	133.22	NaN	Canada
14396	10920	2013-11-01	35.66	NaN	Canada
14421	10920	2013-11-04	21.64	NaN	Canada
14545	10920	2013-11-11	86.61	NaN	Canada
```
and
`data.loc[cust_id]`
yields
```
frequency               19.000000
recency                757.000000
T                      801.000000
monetary_value          61.354211
pastness                44.000000
predicted_purchases      0.593733
Name: 10920, dtype: float64
```

This is the code causing troubles:
```
fig = plt.figure(figsize=(12,12))
for ind, i in enumerate(best_projected_cust.index.tolist()):
    ax = plt.subplot(4, 2, ind + 1)
    best_T = data.loc[i]['T'] + 31 #add a month
    best_trans = trans_data[trans_data['Customer ID'] == i]
    plot_history_alive(bgf, best_T, best_trans, 'Date', freq='D', ax=ax)
    ax.set_title('ID: '+str(i))
    plt.xticks(rotation=25)
fig.tight_layout()
```
And this is what it spits out:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-66-e03bd817e063> in <module>
      4     best_T = data.loc[i]['T'] + 31 #add a month
      5     best_trans = trans_data[trans_data['Customer ID'] == i]
----> 6     plot_history_alive(bgf, best_T, best_trans, 'Date', freq='D', ax=ax)
      7     ax.set_title('ID: '+str(i))
      8     plt.xticks(rotation=25)

~\AppData\Local\Continuum\anaconda3_i2\envs\lifetimes\lib\site-packages\lifetimes\plotting.py in plot_history_alive(model, t, transactions, datetime_col, freq, start_date, ax, **kwargs)
    376 
    377     # plot alive_path
--> 378     path = calculate_alive_path(model, transactions, datetime_col, t, freq)
    379     path_dates = pd.date_range(start=min(transactions[datetime_col]), periods=len(path), freq=freq)
    380     plt.plot(path_dates, path, "-", label="P_alive")

~\AppData\Local\Continuum\anaconda3_i2\envs\lifetimes\lib\site-packages\lifetimes\utils.py in calculate_alive_path(model, transactions, datetime_col, t, freq)
    336 
    337     extra_columns = t + 1 - len(purchase_history)
--> 338     customer_history = pd.DataFrame(np.append(purchase_history, [0] * extra_columns), columns=["transactions"])
    339     # add T column
    340     customer_history["T"] = np.arange(customer_history.shape[0])

TypeError: can't multiply sequence by non-int of type 'numpy.float64'

```
**Conclusion 2**: Using `plot_history_alive()` as **subplot fails**.

**Comment by adityaagarwal2001** [comment]
Hi, I am new to this.
Trying to get p_alive (for each user_id) as of today.

Business case: users are born on different dates for last 6 years. I am able to spit out the expected transactions in next time period 't' for all using-
`bgf.conditional_expected_number_of_purchases_up_to_time(t, data['frequency'], data['recency'], data['T'])`

Would like to calculate p_alive for each user as a metric in similar fashion.
