### ISSUE TITLE
Pareto_NBD overflow

### ISSUE THREAD

**Issue by Ozzerov** [CamDavidsonPilon/lifetimes#25]
When we have customers with frequency > 300 _A_0 function returns 0, because both denominators (max_alpha_beta + rec) *\* r_s_x and (max_alpha_beta + age) *\* r_s_x return Inf.
But in _negative_log_likelihood we only need log of that value, which can be achieved by logsumexp function from scipy.misk.
Suppose we have to calculate log(a/A^r - b/B^r) when r is so large that A^r and B^r overflows to Inf.
In that case we can do the following: log(A_0) = log(a/A^r - b/B^r) = log(a_B^r - b_A^r) - r_log(A_B) = 
log(exp(a + r_log(B)) - exp(b + r_log(A))) - r_log(A_B)
now we can use logsumexp for first term to get correct result.

Same problem occurs in calculating conditional_probability_alive:
(alpha + T) *\* (r + x) \* A_0 overflows to Inf \* 0 and returns NaN
In contrast to _A_0 where we need to be fast for optimization routines, usually conditional_probability_alive executes just once, and we can avoid overflow by using mpmath from sympy which allows precise calculations without overflowing.

And i would also recommend to add an option for differential evolution solver from scipy.optimize  

Adding some functions here:

```
def _log_a_0(r, alpha, s, beta, freq, rec, age):
    min_ab, max_ab, t = (alpha, beta, r + freq) if alpha < beta else (beta, alpha, s + 1)
    abs_ab = max_ab - min_ab
    rsx = r + s + freq
    p_1, q_1 = hyp2f1(rsx, t, rsx + 1., abs_ab / (max_ab + rec)), (max_ab + rec)
    p_2, q_2 = hyp2f1(rsx, t, rsx + 1., abs_ab / (max_ab + age)), (max_ab + age)
    sign = ones(len(freq))
    return logsumexp([log(p_1) + rsx * log(q_2), log(p_2) + rsx * log(q_1)],
        axis=0, b=[sign, -sign]) - rsx * log(q_1 * q_2)
```

import sympy.mpmath as mp

```
def p_alive_precise(self, freq, rec, age):
    freq, rec, age = check_inputs(freq, rec, age)
    r, alpha, s, beta = self.pars
    log_a_0 = self._log_a_0(r, alpha, s, beta, freq, rec, age)

    def precise(freq_, age_, log_a_0_):
        return float(mp.power(alpha + age_, r + freq_) * mp.exp(log_a_0_))

    p = array(list(map(precise, freq, age, log_a_0)))
    return 1. / (1. + (s / (r + s + freq)) * (beta + age) ** s * p)
```

**Comment by CamDavidsonPilon** [comment]
Awesome, thanks @Ozzerov!

**Comment by CamDavidsonPilon** [comment]
Half resolved in https://github.com/CamDavidsonPilon/lifetimes/commit/7bc816dabb2c621db7408a3a8986cbb27af8bedb

**Comment by achiru** [comment]
guess this is easier to write here, instead of pull request.

I think instead of trying the computational approach, if we use the alternative and more simplified expression for P_Alive which is Eq. 34 in the reference:  http://brucehardie.com/notes/009/pareto_nbd_derivations_2005-11-05.pdf, this problem will be fixed.

I tried it , and it eliminates the overflow for high values of R,F, and T (verified for range of values >300). 

below is the function with expression in 34. Note that parts of this equation as indeed present in conditional expected number of purchases.

```
def conditional_probability_alive_2(model, frequency, recency, T):
        params=model.params_.values()
        r,alpha,s,beta= params
        x, t_x = frequency, recency
        likelihood = -model._negative_log_likelihood(params, x, t_x, T,0.0) 
        first_term = gammaln(r + x) - gammaln(r) + r * log(alpha) + s * \
            log(beta) - (r + x) * log(alpha + T) - s * log(beta + T) 
        return exp(first_term - likelihood)
```


Thank you very much for the package. 
AravindChiruvelli.
