### ISSUE TITLE
Add conda support [Help Wanted]

### ISSUE THREAD

**Issue by spiritofpigeon** [CamDavidsonPilon/lifetimes#250]

**Comment by sophia-wright-blue** [comment]
@spiritofpigeon , i don't think you can install this library with `conda`, `conda install` is available for `lifelines` though, 

do `pip install lifetimes` in your conda environment, hope that helps,

**Comment by CamDavidsonPilon** [comment]
In the next release, I'll set up conda

**Comment by CamDavidsonPilon** [comment]
I don't use conda, so I'm uncomfortable doing this. If someone else would like to, I would appreciate that very much!

**Comment by psygo** [comment]
I don't know if this is what you mean, but isn't it possible to install it on top of the `Python` version being used by `Anaconda` by using the `--user` option? Something like `pip install --user lifetimes`.

**Comment by Arnoldosmium** [comment]
Hi @CamDavidsonPilon , I'm trying to add the publish of `lifetimes` to conda-forge channel. Let me know if you are okay with this. https://github.com/conda-forge/staged-recipes/pull/10871

**Comment by CamDavidsonPilon** [comment]
okay with me :)

**Comment by Arnoldosmium** [comment]
Could be helpful to merge #359 before the next release. I can change the conda package recipe to include correct LICENSE by then. Not blocking though
