### ISSUE TITLE
My Pareto NBD Model "Sucks"

### ISSUE THREAD

**Issue by mkbldn** [CamDavidsonPilon/lifetimes#252]
I've been running the Pareto NBD model against a various cohorts of our customers and they all display the same behavior in the plot_period_transactions (top left labeled 'Frequency of Repeat Transactions') graph that compares our data versus artificially simulated data with the fitted model's parameters.  In each case, simulated data is over estimating the 1 repeat customers and underestimating the amount of 2 or more repeat purchases. I've been re-running the models exploring different frequencies and penalizer coefficients but neither is improving the fit. 

Are there any "dials" I should be turning that I haven't already?... or any strategies to determining why the fit is so poor? I'm extremely new to these types of models and any assistance in improving the them would be greatly appreciated.

### 2Q 2008 
![xv_graphs_prt_0_200802_all_products](https://user-images.githubusercontent.com/8095617/53833446-8570a480-3f56-11e9-9a97-cd69a2a40ded.png)

### 2Q 2014
![xv_graphs_prt_0_201402_all_products](https://user-images.githubusercontent.com/8095617/53833807-6cb4be80-3f57-11e9-90ed-a86c9030212b.png)

**Comment by CamDavidsonPilon** [comment]
Hi @mkbldn,
To be more accurate than sucks, your model fits poorly. Is there any reason why you are using the Pareto model? I prefer the BetaGeoBetaBinom model personally, as it's easier to interpret and has better convergence. 

If you stick with the Pareto, some diagnostics to check: are your parameters unreasonably large or small? Does using the BetaGeo model fit better? If not, maybe your dataset has some properties that these models can't capture.

**Comment by mkbldn** [comment]
@CamDavidsonPilon thanks for the help! I'm working through using the BGBB. We also discovered what was going on with the plot_period_transactions graph (aka Frequency of Repeat Transactions). One of my coworker noticed that the pareto_nbd_fitter was passing the un-scaled parameters to pareto_nbd_model(). We made the small change below at line 134 and the graph looks much better:

#### Original
`        self.generate_new_data = lambda size=1: pareto_nbd_model(T, *params,
                                                                 size=size)
`
#### Updated
`        self.generate_new_data = lambda size=1: pareto_nbd_model(T,
																 *self._unload_params('r', 'alpha', 's', 'beta'),
                                                                 size=size)`

### 2Q 2014

![xv_graphs_prt_0_201402_all_products](https://user-images.githubusercontent.com/8095617/53976744-9e539400-40d5-11e9-8712-9ef5b77d90ce.png)

**Comment by CamDavidsonPilon** [comment]
holy that's a pretty serious bug! Thanks for mentioning this. I'll fix for v0.11.0 and double check for the other models

**Comment by CamDavidsonPilon** [comment]
Give your coworker a 👍 for spotting that

**Comment by Harsharajuu** [comment]
Hi @mkbldn 

I know its pretty old to ask this question, by any chance you have the codes which we can use to get the above 4 graphs for validating BG/NBD model
