### ISSUE TITLE
calibration_and_holdout_data "attribute .n"

### ISSUE THREAD

**Issue by jethard** [CamDavidsonPilon/lifetimes#253]
On line 126 of lifetimes/lifetimes/utils.py there appears to be an extraneous .n at the end of the line 

" delta_time = (to_period(observation_period_end) - to_period(calibration_period_end)).n"

This is personally throwing an error for my data, as well as the quick start sample data. 

Thank you

**Comment by CamDavidsonPilon** [comment]
👋 @jethard 

Thanks for bringing this up - it reminded me of an oversight in my latest v0.11.0 branch. Let me fix that and get back to you. For now, either upgrade pandas or downgrade to lifetimes 0.10.1

**Comment by CamDavidsonPilon** [comment]
A new v0.11.1 was just released which pins pandas to be more than 0.24.0

**Comment by jethard** [comment]
Thanks!

**Comment by cerenaaa** [comment]
I have the updated version v0.11.1 but I'm still getting the same error (pandas 0.24.2). Any solutions?

Thanks,
C.

**Comment by CamDavidsonPilon** [comment]
Hm, can you post the output of `pip freeze`?

**Comment by cerenaaa** [comment]
Hi Cameron,

After uninstalling and reinstalling the package, it worked for me.

Thanks!
Ceren
