### ISSUE TITLE
BetaGeoFitter does not converge

### ISSUE THREAD

**Issue by jeevankumarr** [CamDavidsonPilon/lifetimes#258]
I'm trying to reproduce it with toy data, but here is the production output for now. Please bear with me

```
      fun: -6.155324384469124
 hess_inv: array([[ 34.14888093,  79.53184397, -34.43641272,   8.99720646],
       [ 79.53184397, 187.69978117, -81.28897645,  21.22093794],
       [-34.43641272, -81.28897645,  35.94186467,  -8.94397815],
       [  8.99720646,  21.22093794,  -8.94397815,   3.20465778]])
      jac: array([-0.97718067,  0.76784281,  0.3927777 , -0.31105668])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 131
      nit: 9
     njev: 119
   status: 2
  success: False
        x: array([ -4.92537396, -16.24881329,   7.21144836,  -2.16874824])
      fun: -8.66755561279924
 hess_inv: array([[ 36.74240768,  66.16563543, -38.41316997,  32.32570586],
       [ 66.16563543, 120.23837139, -69.99225472,  58.9051788 ],
       [-38.41316997, -69.99225472,  41.66052704, -34.20495602],
       [ 32.32570586,  58.9051788 , -34.20495602,  29.77336544]])
      jac: array([-0.98732629,  0.93300428,  0.17959895, -0.1395994 ])
  message: 'Desired error not necessarily achieved due to precision loss.'

```

**Comment by CamDavidsonPilon** [comment]
Hey @jeevankumarr, thanks for the report. Is is possible for you to send the dataset over (email is fine for me), _or_ can you answer the following:
1) what is the length of the dataset?
2) What is the maximum value of frequency? 

Also, does adding a small penalizer help? `BetaGeoFitter(penalizer=0.001)`?

**Comment by jeevankumarr** [comment]
@CamDavidsonPilon thanks for your quick response, i reverted to the previous version (0.10.1) and it seems to be working fine. I need more time to get back to you re the data - doing some backfills. 

Prior to creating the issue, i had added a small penalizer co-eff `0.001`, had the same issues.
