### ISSUE TITLE
Holdout data util method does not check for observation period end. 

### ISSUE THREAD

**Issue by benvandyke** [CamDavidsonPilon/lifetimes#26]
Hello Cam, great library, thanks for putting it together. I discovered a bug in the `util.calibration_and_holdout_data` function. When it creates the holdout aggregate, it does not limit for the `observation_period_end` parameter, only the `calibration_period_end` parameter. See line 55 in util.py. The result is that the holdout period is aggregated through the end of the dataset rather than the upper bound set in the parameter. 

In `util.summary_data_from_transaction_data` you have this code at line 102:

`transactions = transactions.ix[transactions[datetime_col] <= observation_period_end]`

Adding this line to the holdout util function will fix the problem.

**Comment by CamDavidsonPilon** [comment]
Thanks for reporting this bug, @benvandyke! I've fixed in the latest commit to master: 6410fb0
