### ISSUE TITLE
plot_calibration_purchases_vs_holdout_purchases taking for ever to run

### ISSUE THREAD

**Issue by amrishan** [CamDavidsonPilon/lifetimes#263]
![image](https://user-images.githubusercontent.com/36165834/56150244-12564700-5f74-11e9-84f2-fd36db3c37e8.png)

**Comment by amrishan** [comment]
I don't think the lambda function is necessary. It's looping each value to make a prediction.

**Comment by CamDavidsonPilon** [comment]
Riiight, this looks like a big perf win. Are you comfortable submitting a PR, or would you like to leave it to me?

**Comment by amrishan** [comment]
Sure, I would be happy to assist with the PR. Thanks for the awesome package @CamDavidsonPilon .

**Comment by amrishan** [comment]
> Riiight, this looks like a big perf win. Are you comfortable submitting a PR, or would you like to leave it to me?

Sure, I would be happy to assist with the PR. Thanks for the awesome package @CamDavidsonPilon .
