### ISSUE TITLE
Number of Active Customers Do Not Change Throughout Time

### ISSUE THREAD

**Issue by edenhuangSH** [CamDavidsonPilon/lifetimes#265]
Please see Section 4.1 of the Notebook for this issue: [(https://github.com/edenhuangSH/bgnbd_python/blob/master/BG_Eden_Huang.ipynb)]

The tables compare simulation results if how many customers are alive after 10 days, 1 year, 10 years and 100 years and how many purchases they have made in that time using the
modified BG model. For simplicity, I define “active customers” as those with the probability of being active greater than 0.5. I set the sample size of simulation as the size of the population and I want to compare the results based on the same population N across different time periods (t).

The table returns how many customers are alive after 10 days, 1 year, 10 years and 100 years and how many purchases they have made in that time using the
modified BG model. For simplicity, I define “active customers” as those with the probability of being active greater than 0.5.

What’s confusing to me is the LAST COLUMNs ON THE RIGHT – numbers of active customers are the SAME regardless of the time period. I tried on different cutoff probabilities (for “active”) and the numbers on this column are always the same. So basically, it tells me that the number of active customers is determined during the first time frame and won’t change afterward. 

For smaller sample sizes (n = 1000 or 100 etc.), the tables always return different counts, so I thought my simulation and modeling functions are correct.  

Do you think it’s possible or am I doing wrong or that's an issue with the model? Thank you in advance for the help!

**Comment by CamDavidsonPilon** [comment]
I can't open your notebook, but I imagine the problem is that you are using BGNBD which has a flaw that people with only one purchase have P(alive) = 1.0 - and these people will always be around. 

Try using a better model like BetaBinomial.
