### ISSUE TITLE
[Question]: Additional features for BG/NBD Model

### ISSUE THREAD

**Issue by goodhamgupta** [CamDavidsonPilon/lifetimes#267]
Hi Cameron,

Thanks a ton for creating this library! It has been really helpful in implementing CLV for me. 

As a general question, I would like to know if it's possible to include additional features in the BG/NBD model? For example, purchasing behaviour could be influenced by certain demographic features such as age groups, gender, etc. Are there any existing models that accommodate demographics as part of the CLV? If not, could you point me to some resources that show how these models can be modified to include additional demographic information?

Thanks again!

**Comment by CamDavidsonPilon** [comment]
Hello hello! Not yet, but it's on my roadmap to add that.

**Comment by goodhamgupta** [comment]
Ah that's great news! How do you plan on integrating it? If you have some minor tasks that can help towards implementing this, I would be very happy to help! :D Also, if you could point me towards some reading material towards this specific use-case that would be fantastic!

**Comment by andrewng88** [comment]
Just chiming to indicate that I'm also pretty interested  in demographic features of the model. 

Thank you once again for this opensouce library. Cheers.

**Comment by romanoww** [comment]
Also very interested, current absence would actually force me to use BTYDplus in R.

**Comment by psygo** [comment]
It is quite unfortunate that both me and him are kind of busy right now &mdash; though I don't know if I have enough expertise to implement everything people have suggested. I'm having much more trouble than expected with some infrastructural work, but, as soon as I can, I'll be going back to at least adding some more basic features to this library.

If you're interested in collaborating, you're more than welcome to. I've even written some [guidelines](https://github.com/CamDavidsonPilon/lifetimes/blob/master/CONTRIBUTING.md) (`CONTRIBUTING.md`) to help people interact more easily and efficiently.

**Comment by goodhamgupta** [comment]
I would like to pick this up. Thanks for the links @romanoww. I will go through them and raise a separate issue containing the implementation details.
