### ISSUE TITLE
customer_lifetime_value

### ISSUE THREAD

**Issue by zaret-rocket** [CamDavidsonPilon/lifetimes#27]
Hi @CamDavidsonPilon, thanks so much for this library.

I have a couple questions about ggf.customer_lifetime_value()

1) When I used it, it was outputting higher CLV than I expected. After looking at the function, it seems to me that each expected_revenues_period_x contains cumulative transactions predicted up to and including the month rather than just transactions predicted in that month.

(lifetimes/lifetimes/estimation.py:106):

``` python
lambda r: (m*transaction_prediction_model.predict(i, r['frequency'], r['recency'], r['T'])/(1+d)**(i/30)),
```

For my calculation, I changed it to

``` python
lambda r: (m*(transaction_prediction_model.predict(i, r['frequency'], r['recency'], r['T'])-transaction_prediction_model.predict(i-30, r['frequency'], r['recency'], r['T']))/(1+d)**(i/30)),
```

2) I noticed the default discount rate is 1 and the rate in the tutorial is 0.7. These strike me as high and make me wonder if I'm misunderstanding something. In most literature, I'm seeing annual discount rates between .05 and .15. I understand that the discount rate will vary depending on the situation, but I'm wondering why the default and the example use what seem like high rates to me.

**Comment by CamDavidsonPilon** [comment]
cc @luke14free any thoughts on this?

**Comment by statwonk** [comment]
Regarding point `2)`, I'm no finance expert, but my understanding of discount rate is that it's essentially [the interest rate that the company could borrow at](https://en.wikipedia.org/wiki/Discounted_cash_flow#Discount_rate). In that case 1 or 0.7 sounds like a typo unless parameterized as `1 - x`, so 0% or 30% respectively.

A bit of cursory research shows these rates for top-rated firms are close to [1%](https://www.federalreserve.gov/releases/cp/). Assuming that most users probably don't have a AA credit rating, does 2% sound like a fine default @CamDavidsonPilon? I'll look to see how the rate is parameterized.

**Comment by stochastic1** [comment]
It depends on the industry and business. Some impute a weighted average cost of capital which doesn't necessarily reflect any publicly-available source. I like 0.01 annualized for a default, so 0.01/(364/30) = ~0.0082 on a monthly basis. 

It would be useful to parameterize in the function call, or note in the **kwargs.

**Comment by minggli** [comment]
@CamDavidsonPilon , thanks Cameron for providing this great framework. I've looked into Fader et al 2005 and Fader and Hardie 2013. yet, it's not entirely clear the underlying utils._customer_lifetime_value (customer_lifetime_value calls). does it just predict the remaining spending potential of a customer or rather entire lifetime value of a customer. 

Below is the main reason:

Parameters
    ----------
    transaction_prediction_model:
        **the model to predict future transactions**, literature uses pareto/nbd but we can also use a different model like bg


print(ggf.customer_lifetime_value(
    **bgf, #the model to use to predict the number of future transactions**
    summary_with_money_value['frequency'],
    summary_with_money_value['recency'],
    summary_with_money_value['T'],
    summary_with_money_value['monetary_value'],
    time=12, # months
    discount_rate=0.01 # monthly discount rate ~ 12.7% annually
).head(10))
"""
customer_id
1      140.096211
2       18.943467
3       38.180574
4       38.180574
5       38.180574
6     1003.868107
7       28.109683
8       38.180574
9      167.418216
10      38.180574
Name: clv, dtype: float64
"""
