### ISSUE TITLE
How to Recognize if your data is fit for (this library's) Customer Segmentation and CLV?

### ISSUE THREAD

**Issue by psygo** [CamDavidsonPilon/lifetimes#271]
I'm trying to use this library with my data &mdash; which is real data and consists of more than 500,000 customers &mdash;, however I'm getting weird behavior with respect to the fitting of the distributions, more specifically, my `alpha` is way too large (approaching 320 without any penalty). If I put an *L2 Penalty* of 0.5, I can get a much smaller `alpha` (still very very big), but `a` and `b` get frighteningly small:

| parameter      | coef      | se(coef) | lower 95% bound | upper 95% bound |
|-------|-----------|----------|-----------------|-----------------|
| r     | 0.628972  | 0.000931 | 0.627148        | 0.630795        |
| alpha | 57.421640 | 0.148712 | 57.130166       | 57.713115       |
| a     | 0.002099  | 0.000076 | 0.001950        | 0.002247        |
| b     | 0.062845  | 0.001426 | 0.060050        | 0.065641 |

What is the intuition behind `r`, `alpha`, `a` and `b`? If you think that these questions are not adequate as a discussion on `github`, feel free to point me to another forum.

I suspect that this problem comes from wrong assumptions with respect to the distribution of my RF variables (perhaps, too skewed a frequency distribution). However, I haven't yet understood what those are specifically (are there any really?), since what I've found so far in the literature mostly discusses the assumptions of individual behavior (e.g. number of transactions of a customer follows a Poisson distribution). In my case, the histograms for `x`, `t_x`, `T` give me:

![rfm_lifetimes](https://user-images.githubusercontent.com/11823725/57307371-d0c04400-70ba-11e9-81db-fb555b86b43b.PNG)

Needless to say, my model fitting is pretty bad:

![model_pred 1](https://user-images.githubusercontent.com/11823725/57320975-95cc0980-70d6-11e9-9930-da8e85121cdd.PNG)

![model_pred 2](https://user-images.githubusercontent.com/11823725/57307625-4b895f00-70bb-11e9-9d4f-43da2db123c7.PNG)

Btw, I think you've forgot to place a Paypal link on your main page in order for us to donate money to you ;)

**Comment by psygo** [comment]
The histograms above were drawn considering only the customers with at least one repeat visit (>= 2 visits). If the one-timers are added, we get a very skewed distribution (1/5 of the customers are one-timers); nevertheless, none of the variations yield good models.

**Comment by psygo** [comment]
Maybe this problem comes from the fact that in my case the **daily transactions grow considerably as time goes on** (something I've only now found out; this is apparently a homologation DB)? --- which is not the usual case. 
When looking at the cumulative transactions graph, the model seems to deviate from the actual data after a while. Perhaps, the BG/NBD (and also the Pareto/NBD) model is not supposed to deal with such behavior?
Anyway, it is at least not half as bad as I imagined it to be --- although still quite bad.

![daily_transactions](https://user-images.githubusercontent.com/11823725/57473885-4537e600-7267-11e9-94d4-40dcb365f2db.jpg)
![cumulative_transactions](https://user-images.githubusercontent.com/11823725/57473899-4a953080-7267-11e9-90aa-d3efe2204204.jpg)

**Comment by hmikelee** [comment]
Dear Philippe,

I hope my comment below can help

I tested lifetimes in Feb with 3 retail related datasets that I could find on the internet before I apply my companies' data. In 2 cases, the forecast performances were quite well, but in one case the forecast result exhibited similar forecast performance that you showed. 
In the one case with a bad forecast, I noticed the frequency graph did not exhibit exponential like distribution so the forecast result was not good
![qt_fact_check_freq_440](https://user-images.githubusercontent.com/34959055/57515643-b5b53480-7345-11e9-8893-d4142f75a384.png)

But it looks like your frequency data is not the same as the case I encountered before. May I understand more detail about your use case and the background of your dataset?

In my case, when I use lifetimes with my company's dataset, forecast performance went well

hmikelee

**Comment by psygo** [comment]
@hmikelee thank you for your help.

I'm applying this library on a dataset composed of approximately 4 years of data of a company that sells beauty products. However, most of my studies comprise a 2 years span because this was also an homologation database, i.e., it served as a testing ground for the transition into our software. Even with the more conservative time span, the behavior of the distributions might not be usual enough to fit into the BG/NBD or Pareto/NBD model, I guess?

What *exact other specifications* of my dataset would you like to receive? I warn you, though, that I might not be able to disclose too much information.

From what I can see, the frequency shape of my data doesn't seem be an issue, as it was in your case. It does look exponential, albeit quite the steep one. On the other hand, after some thought, what does seem suspicious to me is the *recency shape*, which looks almost *bimodal*, something that usually happens when there is an *external phenomenon* influencing the data to go into some specific direction.

**Comment by sophia-wright-blue** [comment]
Hi @psygo , can you share some sample data and the code that you used? i'll try to replicate your results and compare the results to what I have obtained in the past;

**Comment by sophia-wright-blue** [comment]
thanks for sharing the data @psygo , i'm gonna try and take some time out to go over the results,

**Comment by sophia-wright-blue** [comment]
Hi @psygo , what version of lifetimes are you using?

**Comment by psygo** [comment]
@sophia-wright-blue , after running `lifetimes.__version__`, I get the `0.11.1`, which seems up to date with the [Lifetimes main page](https://github.com/CamDavidsonPilon/lifetimes) here on Github.

**Comment by psygo** [comment]
Since the beginning of my data is a very different compared to the rest, I've decided to start the calibration period a little bit later. This has given me much better results (`alpha` still has a value that's way too high: ~35), as seen in the graphs below (the Period Transactions graph is the only one that seems to have gotten worse).

However, whenever I try to plot the incremental transactions graph, I get **close to zero transactions at the beginning anyway**, even though it isn't a period where there were no transactions. I think there is something inside the `expected_cumulative_transactions()` function (called inside `plot_incremental_transactions()`) that *forces all clients back to zero frequency and, thus, somehow, their first purchases are not counted*. (I'm also getting a *warning*, but I think I had it before: `RuntimeWarning: invalid value encountered in log`)

Does anyone know how the `plot_incremental_transactions()` function works behind the scenes? It doesn't seem very clear, and there seems to be something I'm missing. (And it might be an indicator that I'm doing something else wrong actually, I don't know.)

![b5a_clv_rf_calibration_purch_vs_holdout_purch](https://user-images.githubusercontent.com/11823725/59371022-4357bb80-8d1a-11e9-919b-2bf98567b01b.jpg)
![b5a_clv_rf_cumulative_transactions](https://user-images.githubusercontent.com/11823725/59371024-4357bb80-8d1a-11e9-9cb3-195210adc972.jpg)
![b5a_clv_rf_incremental_transactions](https://user-images.githubusercontent.com/11823725/59371025-4357bb80-8d1a-11e9-94df-1a30e7009c7f.jpg)
![b5a_clv_rf_period_transactions](https://user-images.githubusercontent.com/11823725/59371026-4357bb80-8d1a-11e9-8506-a59c6b8e7dec.jpg)

**Comment by aprotopopov** [comment]
Your plots from last comments look pretty good maybe except the last one and cumulative transactions could fit better. According to `expected_cumulative_transactions` take a look at the #280 issue. Probably with those changes plots and results would be better.

**Comment by psygo** [comment]
The changes suggested in the interesting #280 issue didn't amount to much unfortunately, but thanks for the suggestion.

How would you suggest I fit my plots better more specifically? As far as I'm aware of, the only parameter that could amount to some change is the model's `L2 Penalty`, and I couldn't get much change by varying it, especially in the last graph.

I'm starting to believe the issue might actually be related to my assumptions about the dataset. Besides the fact that this is a homologation dataset, these specific clients' behavior will most likely differ from a strictly *non-contractual* one, because there is some periodicity to their purchases, since people do go to supermarkets on a regular basis. It seems inherently different to people who, for example, would buy DVDs, which is something more sporadic.

That would more or less explain why the model's fit is understanding that the clients are basically always *alive*. In the end, I might have to compare my results to simply using *contractual* formulas &mdash; which is something I've never studied T.T.
