### ISSUE TITLE
GammaGammaFitter customer_lifetime_value error

### ISSUE THREAD

**Issue by subhash27** [CamDavidsonPilon/lifetimes#272]
Hi,

I am trying to calculate `customer_lifetime_value` as described in the tutorial. I have the data directly in the required format and so I didn't use the utility functions. I tried 2 things:

1. When I specified the input parameters frequency, recency, etc as a list to the function `customer_lifetime_value`, I get the error `can't multiply sequence by non-int of type 'numpy.float64'`
1. Instead if I specify the input parameters as numpy arrays, I get the error  `'numpy.ndarray' object has no attribute 'index'`

I think the `customer_lifetime_value` function depends on two other functions (from the source code) which need the input in different forms.

Please let me know if I am wrong and the right way to specify the params without using utility functions.
Cheers.

**Comment by sophia-wright-blue** [comment]
Hi @subhash27 , can you try passing the input (frequency, recency, etc...) in a pandas dataframe? refer to https://lifetimes.readthedocs.io/en/latest/Quickstart.html

**Comment by Uysim** [comment]
I face the same problem then I try pandas and it work well.
