### ISSUE TITLE
Uncertainty Intervals for CLV

### ISSUE THREAD

**Issue by 99snowleopards** [CamDavidsonPilon/lifetimes#273]
thanks for releasing this amazing library @CamDavidsonPilon ! is it possible to use lifetimes to compute uncertainty intervals for CLV (so lower 95% bound and upper 95% bound for CLV, and not just the coefficients). I'd greatly appreciate any guidance to do this. thanks,

**Comment by 99snowleopards** [comment]
@aprotopopov , it'd help me out greatly if you can give any guidance on computing the uncertainty intervals for CLV, thanks,

**Comment by aprotopopov** [comment]
I think you could take a look at the #201 issue. And the code from @zscore for bootstrapping: https://gist.github.com/zscore/668047a90fee483eee7474611fba8d52
