### ISSUE TITLE
12 Month Customer Value prediction according to customer first 3 week transaction

### ISSUE THREAD

**Issue by tototototototo12** [CamDavidsonPilon/lifetimes#278]
Hi,

My customers work fast and make transactions in their first 3 weeks. After these 3 weeks, I need to calculate their value (CLV). Of course, I have many customers with a 12-month lifetime. How can I do it?

**Comment by psygo** [comment]
You mean project their extrapolate their CLV to 12 months with *only* 3 weeks of data?

I wouldn't recommend doing that, I don't think you can extrapolate that far with such a small dataset. But, if you still want to do it, take a look at the [Quickstart](https://lifetimes.readthedocs.io/en/latest/Quickstart.html) docs page. That tutorial should be enough.
