### ISSUE TITLE
Code in tutorial not working

### ISSUE THREAD

**Issue by paoloRais** [CamDavidsonPilon/lifetimes#28]
Thanks Cam for this great package, it is very useful.

I am currently going through the tutorial and I noticed something strange. When executing:

from lifetimes.plotting import plot_period_transactions
plot_period_transactions(bgf)

I get a chart which is significantly different from what you use in your page (it looks like a worse fit to me):
![repeat_transactions_weird](https://cloud.githubusercontent.com/assets/15232441/10853049/11145156-7f2c-11e5-9e35-bb69f16bf406.png)

Do you know what can be the reason?

Also, one other minor problem: the pip install gives you a different version of your package, in which the file cdnow_customers_transactions.csv is not present.

**Comment by CamDavidsonPilon** [comment]
Hmm, the algorithm in the background is random - perhaps you got unlucky? Try running it again, and please report back the findings.

**Comment by paoloRais** [comment]
I re-ran it several times, obtaining the same results.
I know it is unlikely, but can this strange behaviour be related to the fact that I am using Python 3.4 (while your tutorial seems to be in Python 2.7)?



I am also experiencing issues with this part of the tutorial:

from lifetimes.datasets import load_summary_data_with_monetary_value

summary_with_money_value = load_summary_data_with_monetary_value()
summary_with_money_value.head()
returning_customers_summary = summary_with_money_value[summary_with_money_value['frequency']>0]

returning_customers_summary.head()

I get an error:
ImportError: cannot import name 'load_summary_data_with_monetary_value'

When I try to import the file cdnow_customers_transactions.csv by hand, the result of returning_customers_summary.head() is:
             frequency  recency      T  monetary_value
customer_id                                           
1                    2    30.43  38.86           22.35
2                    1     1.71  38.86           11.77
6                    7    29.43  38.86           73.74
7                    1     5.00  38.86           11.77
9                    2    35.71  38.86           25.55

Which is consistent with the content of the file (but not with the tutorial).

**Comment by paoloRais** [comment]
I installed a separate Python 2.7 environment using Anaconda, and I still obtain the same graph. I wonder what the reason for this can be. I am still testing things and I will keep you updated.

**Comment by CamDavidsonPilon** [comment]
I can confirm I get the same thing, investigating now.

**Comment by CamDavidsonPilon** [comment]
The first issue should be solved in https://github.com/CamDavidsonPilon/lifetimes/commit/3eda4116a4f6cfb1dbec6062cb5f7a92ebb0268e

**Comment by CamDavidsonPilon** [comment]
I've upload this bug fix to PyPI too. I image the latest should also have `cdnow_customers_transactions.csv` - let me know if this is wrong.

**Comment by paoloRais** [comment]
Thank you!
