### ISSUE TITLE
plot_cumulative_transactions behaving as expected?

### ISSUE THREAD

**Issue by NudnikShpilkis** [CamDavidsonPilon/lifetimes#280]
I think there are a few bugs in the calculations for both the predicated and actual cumulative transactions in `expected_cumulative_transactions` that propagate to `plot_cumulative_transactions`.  I've recreated an example below using [cdnow_sample](http://www.brucehardie.com/datasets/CDNOW_sample.zip).

```python
from  datetime import datetime

import numpy as np
import pandas as pd

from lifetimes import ModifiedBetaGeoFitter
from lifetimes.utils import calibration_and_holdout_data, expected_cumulative_transactions
from lifetimes.plotting import *

import matplotlib.pyplot as plt

df= pd.read_csv("cdnow_sample.csv")
df['Date'] = pd.to_datetime(df["Date"])

df_rfm = calibration_and_holdout_data(df, 
                            customer_id_col="ID",
                            datetime_col="Date",
                            calibration_period_end=datetime(1997, 9, 30),
                            freq='7D',
                            monetary_value_col='Spend')

df_rfm.head()

mbg = ModifiedBetaGeoFitter(penalizer_coef=0.0).fit(df_rfm['frequency_cal'], df_rfm['recency_cal'], df_rfm['T_cal'])
mbg.summary
-----------------------------------------------------------------------------------------------------

coef | se(coef) | lower 95% bound | upper 95% bound
-- | -- | -- | --
0.524843 | 0.083268 | 0.361637 | 0.688048
6.183082 | 0.695620 | 4.819667 | 7.546497
0.891360 | 0.154790 | 0.587971 | 1.194748
1.614003 | 0.537495 | 0.560513 | 2.667493

plot_period_transactions(mbg, max_frequency=10)
```
![image](https://user-images.githubusercontent.com/17383024/59803664-2b53df00-92ba-11e9-97dd-930cbc6d70e3.png)

The plot below is generated using `plot_cumulative_transactions`.  The predicted transaction total is larger than the cumulative actual dataset after 1 period.
```python
plot_cumulative_transactions(mbg, 
                             transactions=data,
                             datetime_col="Date",
                             customer_id_col="ID",
                             t=10,
                             t_cal=5,
                             freq='7D')
```
![image](https://user-images.githubusercontent.com/17383024/59800157-dc0ab000-92b3-11e9-8ffc-167eae7d3d83.png)

I think there are two bugs in the calculation of `pred_cum_transactions`.  Firstly, `first_trans_size` calculated holds an entry for all dates in `first_transactions` regardless of period.  For example, `first_trans_size` produces values for "1997-01-02", "1997-01-03", etc. when those values should be included in the entry for "1997-01-01" since we have a period of "7D".   
```python
first_trans_size.head()
---------------------------------------------------------------
Date
1997-01-01    18
1997-01-02    22
1997-01-03    17
1997-01-04    20
1997-01-05    23
```
If we instead add another layer of aggregation, we get the following results.  Note that the entry for "1997-01-01" now includes the sum of all the events that had been in its period.
```python
first_trans_size = first_transactions.groupby(datetime_col).size().resample(freq).sum()
first_trans_size.head()
---------------------------------------------------------------
Date
1997-01-01    157
1997-01-08    164
1997-01-15    182
1997-01-22    193
1997-01-29    216
```
Secondly, `times = np.array([d.n for d in period - first_trans_size.index])` does not behave as expected.  Using the original code and period we get the following array.  Note that the first element of `first_trans_size` was "1997-01-01".  The code returns 49 as the difference between "1997-01-08" and "1997-01-01" when it should return 1.
```python
period = pd.to_datetime("1997-01-08")
times = np.array([d.n for d in period - first_trans_size.index])

times
---------------------------------------------------------------
array([  49,   42,   35,   28,   21,   14,    7,    0,   -7,  -14,  -21,
        -28,  -35,  -42,  -49,  -56,  -63,  -70,  -77,  -84,  -91,  -98,
       -105, -112, -119, -126, -133, -140, -147, -154, -161, -168, -175,
       -182, -189, -196, -203, -210, -217, -224, -231, -238, -245, -252,
       -259, -266, -273, -280, -287, -294, -301, -308, -315, -322, -329,
       -336, -343, -350, -357, -364, -371, -378, -385, -392, -399, -406,
       -413, -420, -427, -434, -441])
```
If we use the following code, with our earlier change, we get more sensical results.  Now the resulting array is as expected as the difference between "1997-01-08" and "1997-01-01" is 1.
```python
times = (period.to_timestamp() - first_trans_size.index.to_timestamp()) / np.timedelta64(1, freq)

times
---------------------------------------------------------------
Float64Index([1.0, 0.0, -1.0, -2.0, -3.0, -4.0, -5.0, -6.0, -7.0, -8.0, -9.0], dtype='float64', name='Date')

```

It also appears that the calculation for the actual cumulative transactions is incorrect.  By reindexing `act_trans`, only record the transactions that occur on the periods date not within the period.  Note, we should expect the entry for "1997-01-08" to equal 19, instead, it equals 3.
```python
act_trans = repeated_transactions.groupby(datetime_col).size()
act_trans.head(7)
---------------------------------------------------------------
Date
1997-01-08    3
1997-01-09    3
1997-01-10    1
1997-01-11    4
1997-01-12    1
1997-01-13    3
1997-01-14    4

act_trans.head(7).sum()
---------------------------------------------------------------
19

act_tracking_transactions = act_trans.reindex(date_periods, fill_value=0)
act_tracking_transactions.head()
---------------------------------------------------------------
1997-01-01     0
1997-01-08     3
1997-01-15     3
1997-01-22    10
1997-01-29     3
```
If we first reindex `act_trans` by all valid dates, then sum along the periods then reindex to the periods we get the following.
```python
#Needed in case the starting date is missing
valid_dates = pd.Series(repeated_and_first_transactions[datetime_col].unique()).sort_values()
act_trans = repeated_transactions.groupby(datetime_col).size().reindex(valid_dates, fill_value=0)
act_trans.head()
---------------------------------------------------------------
1997-01-01    0
1997-01-02    0
1997-01-03    0
1997-01-04    0
1997-01-05    0
1997-01-06    0
1997-01-07    0
1997-01-08    3
1997-01-09    3
1997-01-10    1
1997-01-11    4
1997-01-12    1
1997-01-13    3
1997-01-14    4

act_tracking_transactions = act_trans.resample(freq).sum().reindex(date_periods, fill_value=0)
act_tracking_transactions.head()
---------------------------------------------------------------
1997-01-01     0
1997-01-08    19
1997-01-15    23
1997-01-22    39
1997-01-29    38

```

Those changes in `expected_cumulative_transactions` give the following results.

![image](https://user-images.githubusercontent.com/17383024/59802405-0316b100-92b7-11e9-8940-81838a5eb205.png)

Full implementation of `expected_cumulative_transactions` with the suggested changes.
```python
def expected_cumulative_transactions(
    model,
    transactions,
    datetime_col,
    customer_id_col,
    t,
    datetime_format=None,
    freq="D",
    set_index_date=False,
    freq_multiplier=1,
):
    """
    Get expected and actual repeated cumulative transactions.
    Parameters
    ----------
    model:
        A fitted lifetimes model
    transactions: :obj: DataFrame
        a Pandas DataFrame containing the transactions history of the customer_id
    datetime_col: string
        the column in transactions that denotes the datetime the purchase was made.
    customer_id_col: string
        the column in transactions that denotes the customer_id
    t: int
        the number of time units since the begining of
        data for which we want to calculate cumulative transactions
    datetime_format: string, optional
        a string that represents the timestamp format. Useful if Pandas can't
        understand the provided format.
    freq: string, optional
        Default 'D' for days, 'W' for weeks, 'M' for months... etc. Full list here:
        http://pandas.pydata.org/pandas-docs/stable/timeseries.html#dateoffset-objects
    set_index_date: bool, optional
        when True set date as Pandas DataFrame index, default False - number of time units
    freq_multiplier: int, optional
        Default 1, could be use to get exact cumulative transactions predicted
        by model, i.e. model trained with freq='W', passed freq to
        expected_cumulative_transactions is freq='D', and freq_multiplier=7.
    Returns
    -------
    :obj: DataFrame
        A dataframe with columns actual, predicted
    """
    start_date = pd.to_datetime(transactions[datetime_col], format=datetime_format).min()
    start_period = start_date.to_period(freq)
    observation_period_end = start_period + t

    repeated_and_first_transactions = _find_first_transactions(
        transactions,
        customer_id_col,
        datetime_col,
        datetime_format=datetime_format,
        observation_period_end=observation_period_end,
        freq=freq,
    )

    first_trans_mask = repeated_and_first_transactions["first"]
    repeated_transactions = repeated_and_first_transactions[~first_trans_mask]
    first_transactions = repeated_and_first_transactions[first_trans_mask]

    date_range = pd.date_range(start_date, periods=t + 1, freq=freq)
    date_periods = date_range.to_period(freq)

    pred_cum_transactions = []
    first_trans_size = first_transactions.groupby(datetime_col).size()
    first_trans_size = first_trans_size.resample(freq).sum()
    for i, period in enumerate(date_periods):
        if i % freq_multiplier == 0 and i > 0:
            times = (period.to_timestamp() - first_trans_size.index.to_timestamp()) / np.timedelta64(1, freq)
            times = times[times > 0].astype(float) / freq_multiplier
            expected_trans_agg = model.expected_number_of_purchases_up_to_time(times)

            mask = first_trans_size.index < period
            expected_trans = sum(expected_trans_agg * first_trans_size[mask])
            pred_cum_transactions.append(expected_trans)

    valid_dates = pd.Series(repeated_and_first_transactions[datetime_col].unique()).sort_values()

    act_trans = repeated_transactions.groupby(datetime_col).size().reindex(valid_dates, fill_value=0)
    act_tracking_transactions = act_trans.resample(freq).sum().reindex(date_periods, fill_value=0)

    act_cum_transactions = []
    for j in range(1, t // freq_multiplier + 1):
        sum_trans = sum(act_tracking_transactions.iloc[: j * freq_multiplier])
        act_cum_transactions.append(sum_trans)

    if set_index_date:
        index = date_periods[freq_multiplier - 1 : -1 : freq_multiplier]
    else:
        index = range(0, t // freq_multiplier)

    df_cum_transactions = pd.DataFrame(
        {"actual": act_cum_transactions, "predicted": pred_cum_transactions}, index=index
    )

    return df_cum_transactions

**Comment by aprotopopov** [comment]
Hello @isaachaberman.
Thanks for pointing out on bugs. Would you mind to incorporate your changes in a pull request and add appropriate tests for `test_utils.py` for those situations?

**Comment by isaachaberman** [comment]
I can submit a pull request with the change to `expected_cumulative_transactions`, but I'm not sure I understand what you're current unit tests are doing.

**Comment by aprotopopov** [comment]
You could add your own tests and we could discuss it whether they are enough to cover functionality to prevent future bugs like ones you posted.

**Comment by psygo** [comment]
In my case, the modifications didn't alter anything, but I agree with @isaachaberman's suggestions.

The only thing I believe should be changed is this line:

```python
expected_trans_agg = mbg.expected_number_of_purchases_up_to_time(times)
```

It should be `model` I believe, instead of `mbg`, just a minor hard coding.

**Comment by isaachaberman** [comment]
@psygo Thanks for the bug catch!  You're correct, I accidentally hardcoded `mbg` instead of `model`.

I think overall there's a larger issue with how a lot of the data is calculated.  I don't think any the aggregation using period is working as expected, which affects `calibration_and_holdout_data`, `summary_data_from_transaction_data` and `expected_cumulative_transactions`.  As it stands, I think the functions are probably only trustworthy if used with a freq of `D`.  I'll try to post a few more examples and potential fixes I've come up with later.

**Comment by psygo** [comment]
I do agree that it is probably safer to limit ourselves to `D` frequencies. However, it might be that you found a simple bug in *only part of the code*. For example, one of the issues you encountered and fixed seems to be very close to these lines in the `summary_data_from_transaction_data` function of the [utils.py](https://github.com/CamDavidsonPilon/lifetimes/blob/3e93e805ccb9b4660bd2609a7a9491237029547e/lifetimes/utils.py) file:

```python
customers["T"] = (observation_period_end - customers["min"]) / np.timedelta64(1, freq) / freq_multiplier
customers["recency"] = (customers["max"] - customers["min"]) / np.timedelta64(1, freq) / freq_multiplier
```

At any rate, I think that the bugs you encountered (should) could become a pull request in both the function and the test files, as @aprotopopov suggested.

One suggestion that might help solve all of the aggregation problems in a better way (and which might be the source of other Github Issues, e.g., issue #224) is to create a specific callback function for it. It would even be more in tune with the *DRY* principle and leave the code more manageable, as this type of aggregation is appearing in multiple functions of the [utils.py](https://github.com/CamDavidsonPilon/lifetimes/blob/3e93e805ccb9b4660bd2609a7a9491237029547e/lifetimes/utils.py) file.

**Comment by isaachaberman** [comment]
I can work on a pull request later this week with my changes to this function and the other data manipulation functions.

One question I've been unsure of is the frequency calculation.  Should frequency always be calculated by day or can we use different `freq` to define it?  For instance, if we used `14D` periods and had a customer with two transactions `2019-01-01` and `2019-01-06`.  Then we'd be unable to model since our frequency would be `0` since both events occur in the first period, but our recency would be `>0` (`(2019-01-06 -  2019-01-01) / 14 = 0.35`) unless we rounded down.

**Comment by psygo** [comment]
To me, it makes more sense for intra-period visits to still count as visits. So, in your example, two visits would be counted, regardless of them being in the same time period. This is usually what is done when discretizing histograms.

With respect to recency, I would round it down, because both visits come from a time peiod that is now the discrete conjunction of others. It wouldn't make sense to have discretized the time axis and still count with the previous "continuous" time density.

However, it is possible that other standards might be useful for someone. So, if still in doubt, I would suggest to add new parameters to the new function. Two parameters will suffice: one for counting intra-period visits as more than one or not; and another for discretizing recency or not.

In my current project, for instance, we chose to count intra-day multiple visits to the supermarket as only one visit, which goes against what I've just said, but that was only because they were rare when compared to the rest of the data and it seemed more reasonable because it's only one day.

**Comment by isaachaberman** [comment]
@psygo I've coded up the changes to the functions we spoke about, but I haven't yet been able to code up all the unit tests.  Should I start a merge request so others can see my changes even if the tests aren't complete?

**Comment by psygo** [comment]
I think it's a good idea. It might save you time in the end if you have to make changes to the code anyway. The (Travis) CI tool will most likely not let you pass but then you can discuss with @aprotopopov  and @CamDavidsonPilon how to properly fit it into the code base later. In the end, first we fail the tests and then try to pass them anyway.

You could also try to code it, there is no (big) rush, it's a bit of a personal choice I guess.

**Comment by psygo** [comment]
You can also create a [`Draft Pull Request`](https://help.github.com/en/articles/about-pull-requests#draft-pull-requests) if you're unsure about what you're pulling.
