### ISSUE TITLE
Monetary_value issue

### ISSUE THREAD

**Issue by andrewng88** [CamDavidsonPilon/lifetimes#282]
I would like to clarify about Monetary Value. I read that it can be the total ( sum of qty x unit price ) but for lifetimes library we're using mean instead which is correct. Meaning total sales divided by unique date assuming date is not NULL. if NULL it wouldn't be considered,

I tried to do a manual calculation but I was not able to tally the Monetary Value as per image.

May I trouble you guys to help explain? Thanks in advance.

https://i.imgur.com/TprvkwG.png

**Comment by FadeoN** [comment]
As you can see here, First one will be excluded, so you should ignore 2011-06-19 in your calculations.

` # create an index of all the first purchases
        first_purchases = repeated_transactions[repeated_transactions["first"]].index
        # by setting the monetary_value cells of all the first purchases to NaN,
        # those values will be excluded from the mean value calculation
        repeated_transactions.loc[first_purchases, monetary_value_col] = np.nan
        customers["monetary_value"] = (
            repeated_transactions.groupby(customer_id_col)[monetary_value_col].mean().fillna(0)
        )`

**Comment by andrewng88** [comment]
Out of curiosity may I know why the first one is excluded in the calculation? Thanks :)

**Comment by FadeoN** [comment]
Because we exclude first one in frequency calculation.

`
customers["frequency"] = customers["count"] - 1
`

**Comment by andrewng88** [comment]
Thanks for the explanation. Cheers, happy TGIF!
