### ISSUE TITLE
MatplotlibDeprecationWarning in plot functions

### ISSUE THREAD

**Issue by Kara035** [CamDavidsonPilon/lifetimes#286]
Hi,

I'm getting the `MatplotlibDeprecationWarning` for `plot_incremental_transactions()` and `plot_cumulative_transactions()` functions. I'm not sure why there are *extra axes* for the plots as I had not created them. Any suggestions on how I can access only the latest axes instead of appending them?

![extra axes on the incremental plot](https://user-images.githubusercontent.com/43381551/60212216-ae32e780-982e-11e9-8bc4-be643599138a.png)

Thank you so much.

**Comment by psygo** [comment]
Could you also post the code instead of only an image?

The shapes and *heads* of the DataFrames would also help debugging.
