### ISSUE TITLE
How to use penalizer_coef correctly? How to evaluate GammaGamma fit?

### ISSUE THREAD

**Issue by myrthings** [CamDavidsonPilon/lifetimes#288]
I'm trying to build a model with own data and I would like know how to evaluate it.
I've found that changing penalizer_coef in GammaGammaFitter changes a lot the results for the CLV value: with higher value i get some negative values for monetary and clv, with a lower value -I cannot use 0 for the model fit- the values get higher an nonnegative -all of this without changing the model fit. How can I interpret this? How can I evaluate my model? Should the GammaGamma coef be related with the BetaGeo one? 

I will add some images of the results I'm getting.
penalizer_coef=0.001
Monetary:
<img width="925" alt="Captura de pantalla 2019-07-02 a las 10 57 47" src="https://user-images.githubusercontent.com/42479943/60499454-c6848580-9cb8-11e9-866e-ab079fe34318.png">
CLV:
<img width="939" alt="Captura de pantalla 2019-07-02 a las 10 57 56" src="https://user-images.githubusercontent.com/42479943/60499468-cdab9380-9cb8-11e9-8f08-19a2e081aa5e.png">

penalizer_coef=0.01
Monetary:
<img width="943" alt="Captura de pantalla 2019-07-02 a las 10 58 47" src="https://user-images.githubusercontent.com/42479943/60499495-db611900-9cb8-11e9-86a6-68aaba882964.png">
CLV:
<img width="251" alt="Captura de pantalla 2019-07-02 a las 11 00 13" src="https://user-images.githubusercontent.com/42479943/60499505-e156fa00-9cb8-11e9-812e-2daa0f9f03d1.png">
<img width="935" alt="Captura de pantalla 2019-07-02 a las 10 59 06" src="https://user-images.githubusercontent.com/42479943/60499539-f469ca00-9cb8-11e9-8d73-394e56e6dede.png">

Any advice? How can I evaluate it? Is it better as little as possible?
Thanks!

**Comment by psygo** [comment]
I've been sometimes working on a *Pull Request* about this for some weeks now.

The best I could come up with is to (visually) compare both the actual and the model's Gamma distribution of the average transaction value. Later, I found out that it is exactly one of the steps P. Fader and B. Hardie showed in their [The Gamma-Gamma Model of Monetary Value](http://brucehardie.com/notes/025/) paper (page 8, figure 3). Changing the penalizer's value does indeed change both the distribution's shape and mean.

**Comment by myrthings** [comment]
Really thanks for the answer.
I did it and I found the problem: my data don't follow the "usual" shape of a gamma distribution. Seeing it was really insightful, the unusual parameters really affected the model results but with the usual evaluations methods nothing seemed to be wrong. The data I was using is from a startup and maybe I'm lacking any assumptions made before using it.
Any way, thanks!

**Comment by psygo** [comment]
Cool that it helped, but I would recommend you post the distribution you've obtained here so others can evaluate and contribute to your conclusions. 

Besides that, indeed, perhaps your data won't fit into the Non-Contractual RFM use cases. I'm gonna try to put a non-exhaustive more specific list of use cases in the documentation soon. [Schmittlein's paper](https://www.jstor.org/stable/2631608?seq=1#page_scan_tab_contents) has a discussion on the topic and I have a question about a use case posted in this recent issue #294. Your use case might also be helpful to the list.

**Comment by myrthings** [comment]
Sure.
My present hypothesis is that happens because it's a travel startup. The cyclical periods are really long (+-1 year) and I have data from 2,5 years, so maybe it's not enough. It's also already growing (x2 more unique users every year).
**Some other insights**
- Total orders: 13687
- Percentage of users repeating: almost 10%
- Mean of days between repeated orders: 230+-100
- Frequency plot:
<img width="415" alt="Captura de pantalla 2019-07-08 a las 16 28 13" src="https://user-images.githubusercontent.com/42479943/60818185-6e102500-a19d-11e9-9d22-a10517852adf.png">
- Recency plot:
<img width="406" alt="Captura de pantalla 2019-07-08 a las 16 28 20" src="https://user-images.githubusercontent.com/42479943/60818190-71a3ac00-a19d-11e9-9109-f06c62bba23b.png">

**BG/NBD model**:  Gamma distribution for the transaction rate $\lambda$. The probability for going inactive $p%$ follow a Beta distribution. (y used model.parms to get the values and then plot them with scipy.stats)
- penalizer: 0.0
- params: beta: *a: 0.00, b: 2391.80*, gamma: *alpha: 1928.23 r: 0.70*
<img width="876" alt="Captura de pantalla 2019-07-08 a las 16 12 16" src="https://user-images.githubusercontent.com/42479943/60817286-a878c280-a19b-11e9-8854-1bb9eb390bee.png">

- penalizer: 0.0001
- params: beta: *a: 0.00, b: 0.01*, gamma: *alpha: 1721.19 , r: 0.63*
<img width="858" alt="Captura de pantalla 2019-07-08 a las 16 19 36" src="https://user-images.githubusercontent.com/42479943/60817565-33f25380-a19c-11e9-8f5e-29ef27518c49.png">

- penalizer: 0.01
- params: beta: *a: 0.03, alpha: 529.80*, gamma: *b: 0.05, r: 0.23*
<img width="863" alt="Captura de pantalla 2019-07-08 a las 16 08 19" src="https://user-images.githubusercontent.com/42479943/60817303-b0d0fd80-a19b-11e9-8198-966ff6bb6fb5.png">

**How it should look like (as I saw with others datasets)**
- params: beta: *a: 1.31, b: 1.96* gamma: *alpha: 25.33 , r: 0.09*
<img width="852" alt="Captura de pantalla 2019-07-08 a las 16 23 42" src="https://user-images.githubusercontent.com/42479943/60817865-c85cb600-a19c-11e9-88ba-4ccb2e739f87.png">
from which I get pinky plots: https://github.com/kpei/Customer-Analytics/blob/master/customer_zakka.ipynb

I'd like to upload a notebook in the next weeks with the "failure" and what I learned, because I find It could help someone. But since then maybe this summary is helpful. I will subscribe to the topic you mention too.
