### ISSUE TITLE
BetaGeoBetaBinomFitter stores T as n_periods

### ISSUE THREAD

**Issue by ralbertazzi** [CamDavidsonPilon/lifetimes#292]
Internally the `BetaGeoBetaBinomFitter` stores its data with column names `frequency`, `recency`, `n_periods`, while other fitters use `frequency`, `recency`, `T`.

https://github.com/CamDavidsonPilon/lifetimes/blob/71d97ba52e1d730cda70b771038a3dc4c42f310a/lifetimes/fitters/beta_geo_beta_binom_fitter.py#L164

This becomes a problem for example in the plotting utilities where `T` is expected and a `KeyError` gets raised.

**Comment by psygo** [comment]
I will take a look at it and see if that can be changed.

However, you can use something like `df.rename()` to change the name of the column and then work with the data as usual.
