### ISSUE TITLE
How to calculate p_alive for each Date for every customer? 

### ISSUE THREAD

**Issue by harshinielath** [CamDavidsonPilon/lifetimes#297]
So, I want to calculate `p_alive` for every transaction date of the customer history. I see the `calculate_alive_path()` function gives the output but I have a problem in giving the input columns. The function works absolutely fine if I give *transactions* and *age* for single customer but can not scale it up to all customers.

```python
calculate_alive_path(model, transactions, datetime_col, t, freq='D')
```

Here `t` -> if I give `df['T']` and `df[['Date','amount']]` in transactions, i get `NaN` values for some of the customers?

Any suggestions on how to make this work.

Please let me know if you need more details on the question.

**Comment by alexkyllo** [comment]
I needed to do this today (generate a P(Alive) for each customer for each date in the study period), and doing a `groupby` on customer then `apply`ing `calculate_alive_path` was too slow, so I just wrote a new function that re-implements  `calculate_alive_path` on a df with many customers in it. If there's any interest, I can open a PR to add this to the utils package.
