### ISSUE TITLE
Slow running summary_data_from_transaction_data

### ISSUE THREAD

**Issue by jmabrahams** [CamDavidsonPilon/lifetimes#30]
My data is not sorted by customer id, would it perform faster if my data comes pre-sorted?

**Comment by CamDavidsonPilon** [comment]
I've also experienced the function being slow, and haven't come up with a good solution unfortunately.

**Comment by jmabrahams** [comment]
Thanks, I'll let you know if I come up with anything! Closing this issue for now.

**Comment by psygo** [comment]
This shouldn't really have been closed... the problem still exists I think, though I would have to verify it again.
