### ISSUE TITLE
CBG/CNBD-K Python Implementation

### ISSUE THREAD

**Issue by NudnikShpilkis** [CamDavidsonPilon/lifetimes#301]
Has anyone come across or written up a Python implementation of the [CBG/CNBD-K model](https://sites.google.com/site/michaelplatzer/stochastic-models-of-noncontractual-consumer-relationships/StochasticModelsofNoncontractualConsumerRelationships.pdf?attredirects=0) or the [Pareto/GGG](http://www.reutterer.com/papers/platzer&reutterer_pareto-ggg_2016.pdf)?  

It seems like their among the cutting edge of transaction models but I'm unable to find a Python implementation.  I've found an[ R implementation](https://github.com/mplatzer/BTYDplus) written by the model authors, but nothing in Python.

Any leads are appreciated.

**Comment by psygo** [comment]
I was wondering about the *Pareto/GGG* also.

Maybe we could add *transpile* them into Python. I might try, but I'm not very familiar with R.

Sorry for being a bit absent the last week, but I'm kind of really busy with some infrastructure work at my job.

**Comment by isaachaberman** [comment]
@psygo Do you think it might be worth building the model with a GPU-capable package like Pyro or PyMC?  The implementation might be a little more foreign to many users but might be more powerful.

**Comment by psygo** [comment]
Should be worth it, but I would advocate for the implementation to also work with CPU-only hardware.

It's worth noting, though, that the fitting of the models in this library is not done with the freakish frequency of modern Machine Learning. Usually, people do it monthly or with even longer gaps &mdash; although in a development environment it would be nice to have something very fast.

Speaking of new feature suggestions, I would like to someday study and implement Monte Carlo methods for fitting the mixing the distributions, they should yield the most precise models. This is very briefly mentioned in issue #299.

**Comment by lrhadley** [comment]
I was wondering if anything came of adding Pareto/GGG to the package?  When I was searching on it, I kept ending up here.  We're currently using BG/NBD but want to explore the regularity factor this model.
