### ISSUE TITLE
There are customer_ids predicted to be None by the method `conditional_expected_number_of_purchases_up_to_time`

### ISSUE THREAD

**Issue by ea-niibo** [CamDavidsonPilon/lifetimes#302]
Does the method `conditional_expected_number_of_purchases_up_to_time(self, t, frequency, recency, T)` in the class [`BetaGeoFitter(BaseFitter)`](https://github.com/CamDavidsonPilon/lifetimes/blob/beta-geo-improvements/lifetimes/fitters/beta_geo_fitter.py) behave as expected? Since this method uses the natural logarithm function, it returns a `None` object if we use a negative number for logarithm function. The following code corresponds to that special case.

```python
x = frequency
r, alpha, a, b = self._unload_params('r', 'alpha', 'a', 'b')

_a = r + x
_b = b + x
_c = a + b + x - 1
_z = t / (alpha + T + t)
ln_hyp_term = np.log(hyp2f1(_a, _b, _c, _z))

# if the value is `inf`, we are using a different but equivalent
# formula to compute the function evaluation.
ln_hyp_term_alt = np.log(hyp2f1(_c - _a, _c - _b, _c, _z)) + \
    (_c - _a - _b) * np.log(1 - _z)
ln_hyp_term = where(np.isinf(ln_hyp_term), ln_hyp_term_alt, ln_hyp_term)
```

For example, we set parameters as following:

```python
frequency = 0
t = 30
x = frequency
recency = 0
T = 1

r = 0.11
alpha =  2.24
a =  0.31
b = 0.50
```

Then `ln_hyp_term` is going to be a `None` object, so this method returns `None` object in the end. *If and only if* `x` is positive number, then `np.exp(np.log(x)) = x`. However `hyp2f1(_a, _b, _c, _z)` *is* able to be negative number. So this is happens.

I guess that the reason why we use `np.log` method is to protect overflow. But I think strangely that `conditional_expected_number_of_purchases_up_to_time` returns `None` object.

**Comment by psygo** [comment]
There are some other Github issues about trying to fix that and even a *PR* (#206).

However, the reason for the existence of the `np.log()` operation is not necessarily to protect overflow, but rather a stage used in the *Maximum Likelihood* most of the time. We usually have a product that we want to maximize, which is not very clear in to do in mathematical terms. So we take the `log` of that and turn it into a sum, which is much easier to work with.

I don't know how to circumvent this issue. We would probably have to create a special case for when the `hyp2f1()` goes negative. I think I there is [Bruce Hardie note](http://brucehardie.com/notes/) talking about how to deal with this special case somewhere, but I'm not sure, let us know if you find something there.

**Comment by ea-niibo** [comment]
Thank you for your comments.

yes, off course `np.log()` is mostly used in the Maximum Likelihood Estimation (MLE).
But MLE is often used in something `fit` method.
I think that the `conditional_expected_number_of_purchases_up_to_time` method is not necessarily to use MLE, since BetaGeoFitter model has already defined the parameters `'r', 'alpha', 'a', 'b'`.

In fact, this function uses equation (10) from [2]:
```
    .. [2] Fader, Peter S., Bruce G.S. Hardie, and Ka Lok Lee (2005a),
       "Counting Your Customers the Easy Way: An Alternative to the
       Pareto/NBD Model," Marketing Science, 24 (2), 275-84.
```

According to this paper, the calculation to find the expectation has necessary for MLE, for example (6) and (7), but I think that there is no need to use MLE if we get the expectation.
So I think this method has no need to use `np.log`.

**Comment by psygo** [comment]
Ok, I'll take a more thorough look at it soon, but, if you feel like it, in the meantime, try coding a better solution and making a *pull request*. And I believe you are talking about the exact same thing as *PR* #206.
