### ISSUE TITLE
Understanding of results of fitters.beta_geo_fitter

### ISSUE THREAD

**Issue by manojbalaji1** [CamDavidsonPilon/lifetimes#303]
How to interpret the output of the method `probability_of_n_purchases_up_to_time` of module `fitters.beta_geo_fitter`? Is it possible to use it for customer level prediction?

**Comment by psygo** [comment]
That's the probability of observing `n` purchases up to specified `t` time units. It's averaged over the entire customer population, so it can't be used on individual customers, if that's what you meant.

More on that can be found in the [`docstrings` of the method](https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/fitters/beta_geo_fitter.py) and on this paper: [*"Counting Your Customers" the Easy Way: An Alternative to the Pareto/NBD Model*](http://brucehardie.com/papers/018/), by P. Fader, B. Hardie and K. L. Lee.
