### ISSUE TITLE
S hyperparameter evaluates to 0.00 leading to P(alive) = 1

### ISSUE THREAD

**Issue by cmichae4** [CamDavidsonPilon/lifetimes#304]
I'm trying to implement the Pareto/NBD model based on some transactional data I have. In 2/3 datasets the 's' parameter of mu's gamma distribution evaluates to 0, leading to some customers having a probability of being alive = 1, or very very close to that. This means that it takes a veery long time for them to 'die'.

Any thoughts on why this happens? Are there criteria on the data used in terms of average transactions, duration etc that my datasets may not be meeting? 

How would you recommend I approach this?

**Comment by psygo** [comment]
I don't know if this will be of big help but I had a similar problem that I posted on Issue #271.

I would suggest you **take a sample of your data and share it here** so other people can replicate your results. You could also **share your graphs** with us, sometimes it's enough to diagnose the problem.

In *Schmittlein et al. 1987's paper*, they mention that *half the customers should become inactive after*  `(2^(1/s) - 1)*beta` units of time. If *s* is small, then that goes to a really big number, which does agree with what you said. They also mention that the average death rate is `s/beta`, maybe this could help diagnosing a problem, what is your beta value?

As a guess for why the customers are kept alive, I would say that they have a high periodicity, i.e., they make purchases very frequently. But do they actually? If so, it might not be proper to use *Non-Contractual* models.
