### ISSUE TITLE
Import error: No module named 'lifetimes'

### ISSUE THREAD

**Issue by maria-ferreira-olx** [CamDavidsonPilon/lifetimes#305]
I fitted a model last week and it worked perfectly, but now this error appears:

```
No module named 'lifetimes'
```

**Comment by psygo** [comment]
Could you give us more info on your setup? Maybe your Python Version, your OS, the `lifetimes` version you installed, etc.

If you can, try installing it in a *virtual environment* and see if you can make it work there. For example, using `pipenv`:

```bash
pipenv install lifetimes
pipenv shell
python
>>> import lifetimes
>>> liftetimes.__version__
'0.11.1'
```

**Comment by maria-ferreira-olx** [comment]
Thank you very much for your answer, I did what you just said and worked!
