### ISSUE TITLE
Model predicts fewer purchases in holdout for higher purchases in calibration?

### ISSUE THREAD

**Issue by tmorenovasquez** [CamDavidsonPilon/lifetimes#307]
Trying to figure out what I'm seeing with my data. Here's a quick snippet of my code

```python
summary = lifetimes.utils.summary_data_from_transaction_data(
    df, 
    'user_id', 
    'transaction_date', 
    observation_period_end = '2018-12-31'
)
summary_cal_holdout = calibration_and_holdout_data(
    summary, 
    'user_id', 
    'transaction_date',
    calibration_period_end = '2018-09-30',
    observation_period_end = '2018-12-31'
)
bgf.fit(
    summary_cal_holdout['frequency_cal'], 
    summary_cal_holdout['recency_cal'], 
    summary_cal_holdout['T_cal']
)

plot_calibration_purchases_vs_holdout_purchases(
    bgf, 
    summary_cal_holdout
)
```

Everything runs fine, but my model is predicting fewer holdout purchases for users with 1 purchase in the calibration period versus 0 purchases in the calibration period.

![image](https://user-images.githubusercontent.com/25748357/62388242-c3d0b680-b52a-11e9-8c41-2f14f9f8cf7a.png)

Am I doing something wrong or can someone help me figure out what to make of this?

**Comment by psygo** [comment]
The `0` and `1` purchase customer groups represent the vast majority of the users. So, if you make a mistake there, you probably don't have a good model.

Try plotting the other graphs available in the `plotting` module. The `cumulative` and `incremental` plots should be very enlightening.

Another thing you can try if the fit is not good is to vary your model's *penalizer* coefficient. This usually helps a lot.
