### ISSUE TITLE
On the Development of MCMC Models

### ISSUE THREAD

**Issue by psygo** [CamDavidsonPilon/lifetimes#312]
Since this is a very frequently requested feature, this issue was created to foment the development of **MCMC** (Markov Chain Monte Carlo Methods) implementations of the so far analytical models inside the `lifetimes` library.

If you can, please collaborate with (non-exhaustive list that will be edited in the future):

- References
    - Other libraries' implementations.
        - [BTYDplus](https://github.com/mplatzer/BTYDplus).
- Articles
- Pseudo or Actual Code
- Other Issues with Related Content
    - #168

**Comment by 1dhiman** [comment]
[pydata Seattle 2017: Implementing and Training Predictive Customer Lifetime Value Models in Python](https://pyvideo.org/pydata-seattle-2017/implementing-and-training-predictive-customer-lifetime-value-models-in-python.html)
Found this talk insightful. Unfortunately the code has been recently removed from github.  

Will try to reproduce and add a notebook soon! 👍

**Comment by romanoww** [comment]
@1dhiman please post when you do!

**Comment by sophia-wright-blue** [comment]
@1dhiman , is the notebook at this repo the one that you are referring to?

https://github.com/jrgauthier01/oreilly-intro-to-predictive-clv

**Comment by sophia-wright-blue** [comment]
@psygo , can you provide more details on the MCMC functionality that you'd like to add as a feature?
