### ISSUE TITLE
Predicted LTV Too High

### ISSUE THREAD

**Issue by dmanhattan** [CamDavidsonPilon/lifetimes#313]
Hi Cameron,

Thanks for creating this great library!

I'm having a few problems with the values predicted using `customer_lifetime_value( )`.

I would expect the LTV to be a slightly discounted version of the `predicted purchases * average order value`, but as shown in the screen shot below it's actually coming out much higher:

![Screenshot 2019-08-26 at 12 59 19](https://user-images.githubusercontent.com/15791077/63708311-0ae85980-c802-11e9-8326-600dc0109f62.png)

In one example, a customer who has only spent $180 over 2 years is predicted to have a 12 month value of $2670.

Is there an error somewhere in the calulate being caused by the fix for Issue #180?

Cheers,

Duncan

**Comment by psygo** [comment]
This does seem pretty weird indeed.

> It seems like there must be an issue in the `customer_lifetime_value()` function that is perhaps not deducting the previous period as it iterates over time:

But isn't what the `transaction_prediction_model.predict(i - factor, frequency, recency, T)` term is doing? If anything, I would suspect the `(i / factor)` term. In my opinion, what's really strange is the `for` sum (`+=`): isn't the last prediction already the total? Why are we summing the in-period predictions if they were supposedly already accounted for (it seems to me that we are getting a future history of transactions for the customer and then wrongly summing it up)? Maybe you could try this and see if it gets better results?

I will have to do some more digging, but, unfortunately, I don't have much time for that right now (maybe in a week or two). 

At any rate, it is necessary that you check the fit of your *Gamma-Gamma distributions*. The first thing you could do is maybe check the *negative log likelihood* and see if by varying the `penalizer_coef` you can get a *small* value. Secondly, you should check if the model's gamma distribution of the `monetary_value` is close to the *real* `monetary_value` distribution, i.e., from your data. The `numpy` library has some functions to plot gamma distributions that may be of help. If the model's gamma distribution is far off to the right, it will give feed values much higher than the average `monetary_value` to the `customer_lifetime_value()` function, resulting in the weird behavior you've seen.

**Comment by ColtAllen** [comment]
I've a good idea of what's causing this, which I've summed up [here ](https://github.com/ColtAllen/btyd/issues/76 )and will be working on in the [`btyd` successor library](https://github.com/ColtAllen/btyd).
