### ISSUE TITLE
conditional_expected_average_profit by individual all the same?

### ISSUE THREAD

**Issue by jmabrahams** [CamDavidsonPilon/lifetimes#32]
Hi there, 

Again, thanks for the awesome program. When I try to run the conditional_expected_average_profit function on individual customers I get the same response. Below is the result applied to the CDNOW dataset following the tutorial. Am I misunderstanding how this function works? The descriptions says it will compute for a group of *one* or more customers...

This method computes the conditional expectation of the average profit per transaction
        for a group of one or more customers.

Thanks in advance!

![image](https://cloud.githubusercontent.com/assets/6683853/11223635/cc0e185a-8d25-11e5-82fb-8f6c0aa4ea7b.png)

**Comment by jmabrahams** [comment]
Notes: 
Python 3.4.3 |Anaconda 2.3.0 (64-bit)|

**Comment by CamDavidsonPilon** [comment]
@jmabrahams interesting, can you confirm that `returning_customers_summary['frequency']` are different values? Ditto with the other column. 

Also, can you please provide the parameters of that model, specifically the fitted values of `('p', 'q', 'v')`?

**Comment by jmabrahams** [comment]
In [18]:
ggf = GammaGammaFitter(penalizer_coef = 0)
ggf.fit(returning_customers_summary['frequency'], 
        returning_customers_summary['monetary_value'], iterative_fitting=50)

Out [18]

<lifetimes.GammaGammaFitter: fitted with 946 subjects, p: 6.25, q: 3.74, v: 15.45>

I can confirm that the frequency values vary.

**Comment by jmabrahams** [comment]
I tried applying the formula the long way and got an error on monetary value; any ideas would be appreciated. I can email you the ipython notebook:

p = 6.25
q = 3.74
v = 15.45
x = summary['frequency']
m = summary['monetary_value']
summary['predicted_profit'] = ((((q - 1) / (p * x + q - 1)) * (v * p / (q - 1))) + (p * x / (p * x + q - 1)) * summary['monetary_value'])


---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-29-e84f597a9922> in <module>()
      3 v = 15.45
      4 x = summary['frequency']
----> 5 m = summary['monetary_value']
      6 summary['predicted_profit'] = ((((q - 1) / (p * x + q - 1)) * (v * p / (q - 1))) + (p * x / (p * x + q - 1)) * summary['monetary_value'])

C:\Users\username\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas\core\frame.pyc in __getitem__(self, key)
   1912             return self._getitem_multilevel(key)
   1913         else:
-> 1914             return self._getitem_column(key)
   1915 
   1916     def _getitem_column(self, key):

C:\Users\username\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas\core\frame.pyc in _getitem_column(self, key)
   1919         # get column
   1920         if self.columns.is_unique:
-> 1921             return self._get_item_cache(key)
   1922 
   1923         # duplicate columns & possible reduce dimensionaility

C:\Users\username\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas\core\generic.pyc in _get_item_cache(self, item)
   1088         res = cache.get(item)
   1089         if res is None:
-> 1090             values = self._data.get(item)
   1091             res = self._box_item_values(item, values)
   1092             cache[item] = res

C:\Users\username\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas\core\internals.pyc in get(self, item, fastpath)
   3100 
   3101             if not isnull(item):
-> 3102                 loc = self.items.get_loc(item)
   3103             else:
   3104                 indexer = np.arange(len(self.items))[isnull(self.items)]

C:\Users\username\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas\core\index.pyc in get_loc(self, key, method, tolerance)
   1690                 raise ValueError('tolerance argument only valid if using pad, '
   1691                                  'backfill or nearest lookups')
-> 1692             return self._engine.get_loc(_values_from_object(key))
   1693 
   1694         indexer = self.get_indexer([key], method=method,

pandas\index.pyx in pandas.index.IndexEngine.get_loc (pandas\index.c:3979)()

pandas\index.pyx in pandas.index.IndexEngine.get_loc (pandas\index.c:3843)()

pandas\hashtable.pyx in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12265)()

pandas\hashtable.pyx in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12216)()

KeyError: 'monetary_value'

**Comment by jmabrahams** [comment]
Correction, but still got the same error:

p = 6.25
q = 3.74
v = 15.45
x = summary_with_money_value['frequency']
m = summary_with_money_value['monetary_value']
summary_with_money_value['predicted_profit'] = ((((q - 1) / (p * x + q - 1)) * (v * p / (q - 1))) + (p * x / (p * x + q - 1)) * summary['monetary_value'])

**Comment by romanzdk** [comment]
Hi, I still have the problem even after the manual calculation jmabrahams suggested.
    <lifetimes.GammaGammaFitter: fitted with 1077 subjects, p: 3.01, q: 8.14, v: 4032.24>
![image](https://user-images.githubusercontent.com/31843161/97886277-b0615c00-1d28-11eb-8859-511a5028df3e.png)
![image](https://user-images.githubusercontent.com/31843161/97886330-c5d68600-1d28-11eb-8c74-da592734038b.png)
