### ISSUE TITLE
How to include covariates in the model

### ISSUE THREAD

**Issue by shaddyab** [CamDavidsonPilon/lifetimes#323]
What are the best approaches to include covariate in the number of transaction and/or monetary value predictions? Are are there any plans to extend this package to incorporate such models?

Thank you!

**Comment by psygo** [comment]
> What are the best approaches to include covariate in the number of transaction and/or monetary value predictions?

I don't know.

> Are are there any plans to extend this package to incorporate such models?

There are no plans to include it in the near future. Feel free to make PRs.
