### ISSUE TITLE
How to use the weights argument

### ISSUE THREAD

**Issue by shaddyab** [CamDavidsonPilon/lifetimes#327]
How should I specify the weights argument when fitting a model.

For example what should be the weights array if I have the following data. Here, Count is the number of time each F/R/T pattern appears in my data

frequency_cal | recency_cal | T_cal | Count
0 | 0 | 181 | 423
0 | 0 | 182 | 410
0 | 0 | 183 | 665
0 | 0 | 184 | 607
0 | 0 | 185 | 695

**Comment by lgpreston75** [comment]
@shaddyab did you mange to solve this? I'm also looking for some guidance on how to use weights
