### ISSUE TITLE
BetaGeoFitter: RuntimeWarning: overflow encountered in double_scalars

### ISSUE THREAD

**Issue by clausherther** [CamDavidsonPilon/lifetimes#332]
Running this
```
from lifetimes.plotting import plot_frequency_recency_matrix

_, ax = plt.subplots(1, 1, figsize=(10, 8))
plot_frequency_recency_matrix(bgf);
```
on a `bgf` with parameters
`lifetimes.BetaGeoFitter: fitted with 2556392 subjects, a: 0.40, alpha: 50.16, b: 0.81, r: 0.10`
 
results in 
```
beta_geo_fitter.py:205: RuntimeWarning: overflow encountered in double_scalars
  denominator = 1 + (x > 0) * (a / (b + x - 1)) * ((alpha + T) / (alpha + recency)) ** (r + x)
```

The plot still shows up though.

**Comment by zerualem** [comment]
I get similar RuntimeWarnings when I use BetaGeomFitter.fit(), and when I check the result, it is a poor fit. The `bgf.summary` gives the coef statistics as NaN as show below.

`bgf.summary`

> 	coef	se(coef)	lower 95% bound	upper 95% bound
> 
> r	1.105171	NaN	NaN	NaN
> 
> alpha	1949.521499	NaN	NaN	NaN
> 
> a	1.105171	NaN	NaN	NaN
> 
> b	1.105171	NaN	NaN	NaN

Here is the link to my code:

[https://colab.research.google.com/drive/1KFumLFvRk51XzejJFQH9NZCVnepFXzlj](url)

Any reason why this happening?

**Comment by psygo** [comment]
Have you tried using a penalty coefficient? Sometimes it is the only of making the fit converge.

**Comment by zerualem** [comment]
Yes, I have tried different values for penalizer_coef from 0.0 to 0.1, and I get the same runtime warnings.

```python
from lifetimes import BetaGeoFitter

bgf = BetaGeoFitter(penalizer_coef=0.01)
bgf.fit(df_rfm['frequency'], df_rfm['recency'], df_rfm['T'])
```

> `C:\ProgramData\Anaconda3\lib\site-packages\autograd\tracer.py:48: RuntimeWarning: divide by zero encountered in log return f_raw(*args, **kwargs)

> C:\ProgramData\Anaconda3\lib\site-packages\autograd\numpy\numpy_vjps.py:34: RuntimeWarning: invalid value encountered in multiply defvjp(anp.multiply,    lambda ans, x, y : unbroadcast_f(x, lambda g: y * g),

> C:\ProgramData\Anaconda3\lib\site-packages\autograd\numpy\numpy_vjps.py:53: RuntimeWarning: divide by zero encountered in true_divide lambda ans, x, y : unbroadcast_f(y, lambda g: - g * x / y**2))

> C:\ProgramData\Anaconda3\lib\site-packages\autograd\numpy\numpy_vjps.py:53: RuntimeWarning: invalid value encountered in true_divide lambda ans, x, y : unbroadcast_f(y, lambda g: - g * x / y**2))
> C:\ProgramData\Anaconda3\lib\site-packages\autograd\core.py:212: RuntimeWarning: invalid value encountered in add def _add(self, x, y):  return x + y
> C:\ProgramData\Anaconda3\lib\site-packages\autograd\numpy\numpy_vjps.py:78: RuntimeWarning: divide by zero encountered in true_divide defvjp(anp.log,    lambda ans, x : lambda g: g / x)`

**Comment by psygo** [comment]
> Yes, I have tried different values for penalizer_coef from 0.0 to 0.1, and I get the same runtime warnings.

You might need to go higher. I would try going up to `0.5` jus to be sure that's not something related to the penalizer. If that doesn't solve it, you will perhaps have to analyze the distributions of your data more deeply. 

You could also share a sample (which has the same problem you're facing) of your data so others can try to help more accurately.

**Comment by zerualem** [comment]
> > Yes, I have tried different values for penalizer_coef from 0.0 to 0.1, and I get the same runtime warnings.
> 
> You might need to go higher. I would try going up to `0.5` jus to be sure that's not something related to the penalizer. If that doesn't solve it, you will perhaps have to analyze the distributions of your data more deeply.
> 
> You could also share a sample (which has the same problem you're facing) of your data so others can try to help more accurately.

I have tried high and low values of the penalizer_coef, but it didn't help. I think the model didn't "like" my data. For now, I got around it by using a weekly aggregated data instead of the original daily data.

**Comment by psygo** [comment]
> I think the model didn't "like" my data. For now, I got around it by using a weekly aggregated data instead of the original daily data.

Maybe the sales oscillated too much? Aggregating usually helps to smooth oscillations.

Try creating the `plot_incremental_transactions` graph to take a look at the results.

**Comment by soliverc** [comment]
Hi @zerualem , did you find a solution? Or was resampling by week the best solution?

**Comment by tutu86** [comment]
> > > Yes, I have tried different values for penalizer_coef from 0.0 to 0.1, and I get the same runtime warnings.
> > 
> > 
> > You might need to go higher. I would try going up to `0.5` jus to be sure that's not something related to the penalizer. If that doesn't solve it, you will perhaps have to analyze the distributions of your data more deeply.
> > You could also share a sample (which has the same problem you're facing) of your data so others can try to help more accurately.
> 
> I have tried high and low values of the penalizer_coef, but it didn't help. I think the model didn't "like" my data. For now, I got around it by using a weekly aggregated data instead of the original daily data.

Does did worked with the same data only weekly aggreagated? my data is so big that i wanted to be sure before trying =)

**Comment by zerualem** [comment]
I think the problem here is the issue of very very small number division. I can see why the model would work when I increase the time from daily to weekly or monthly. I found the following article to be very relevant  to the problem we were facing. May be the developers can implement the solution suggested  here. For now we just have to crease the aggregation time to overcome this issue.
The link to the article: [Overcoming the BG/NBD Model’s
#NUM! Error Problem ](http://brucehardie.com/notes/027/bgnbd_num_error.pdf)

**Comment by zerualem** [comment]
> Hi @zerualem , did you find a solution? Or was resampling by week the best solution?

For now, re-sampling is the only option for me. Read here also [ Overcoming the BG/NBD Model’s
#NUM! Error Problem](http://brucehardie.com/notes/027/bgnbd_num_error.pdf)

**Comment by extrospective** [comment]
@zerualem: the code link provided to google colab does not work when clicked as it an href pointing elsewhere.

**Comment by zerualem** [comment]
> @zerualem: the code link provided to google colab does not work when clicked as it an href pointing elsewhere.

@extrospective Here is the code

`python

from lifetimes.plotting import *
from lifetimes.utils import *
#from lifetimes.estimation import *
end_date = cust['Date'].max() + pd.Timedelta(days=1)
df_rfm = summary_data_from_transaction_data(cust, 'Customer', 'Date', monetary_value_col='Sales', observation_period_end=end_date)


from lifetimes import BetaGeoFitter

bgf = BetaGeoFitter()
bgf.fit(df_rfm['frequency'], df_rfm['recency'], df_rfm['T'])
`

**Comment by Shubham080597** [comment]
I am getting this error again and again please help out I have try the above things still getting the error  

C:\Users\shubham.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\autograd\numpy\numpy_vjps.py:75: RuntimeWarning: invalid value encountered in multiply
  defvjp(anp.exp,    lambda ans, x : lambda g: ans * g)
C:\Users\shubham.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\autograd\numpy\numpy_vjps.py:75: RuntimeWarning: invalid value encountered in multiply
  defvjp(anp.exp,    lambda ans, x : lambda g: ans * g)
C:\Users\shubham.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\autograd\numpy\numpy_vjps.py:75: RuntimeWarning: invalid value encountered in multiply
  defvjp(anp.exp,    lambda ans, x : lambda g: ans * g)
C:\Users\shubham.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\autograd\numpy\numpy_vjps.py:75: RuntimeWarning: invalid value encountered in multiply
  defvjp(anp.exp,    lambda ans, x : lambda g: ans * g)
C:\Users\shubham.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\autograd\numpy\numpy_vjps.py:75: RuntimeWarning: invalid value encountered in multiply
  defvjp(anp.exp,    lambda ans, x : lambda g: ans * g)
C:\Users\shubham.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\autograd\tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
C:\Users\shubham.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\autograd\tracer.py:48: RuntimeWarning: invalid value encountered in add
  return f_raw(*args, **kwargs)
C:\Users\shubham.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\autograd\numpy\numpy_vjps.py:75: RuntimeWarning: invalid value encountered in multiply
  defvjp(anp.exp,    lambda ans, x : lambda g: ans * g)
C:\Users\shubham.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\autograd\numpy\numpy_vjps.py:78: RuntimeWarning: divide by zero encountered in double_scalars
  defvjp(anp.log,    lambda ans, x : lambda g: g / x)
C:\Users\shubham.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\autograd\tracer.py:48: RuntimeWarning: divide by zero encountered in log
  return f_raw(*args, **kwargs)
C:\Users\shubham.kumar\AppData\Local\Continuum\anaconda3\lib\site-packages\autograd\tracer.py:48: RuntimeWarning: overflow encountered in power
  return f_raw(*args, **kwargs)
