### ISSUE TITLE
How to interpret bgf.summary

### ISSUE THREAD

**Issue by ZhengTzer** [CamDavidsonPilon/lifetimes#333]
Hi, I have 2 questions, please help me with some guidance:

1. **How to read `bgf.summary`? what does each column and row mean?**

    coef | se(coef) | lower 95% bound | upper 95% bound
    -- | -- | -- | --
    0.271124 | 0.003597 | 0.264073 | 0.278175
    156.815975 | 3.151111 | 150.639797 | 162.992154
    0.331748 | 0.014789 | 0.302761 | 0.360735
    1.176144 | 0.061768 | 1.055079 | 1.297209

2. **I've tried to change the `penalizer_coef`, below is set at zero, the more I increase it, the worse it is.**

    ![download](https://user-images.githubusercontent.com/20983125/68357932-e5f15a80-0151-11ea-83e8-efca1b28a1d0.png)

I need some guidance on closing the model's prediction gap. Which part do most beginners get wrong?

Thanks

**Comment by psygo** [comment]
> 1. How to read bgf.summary? what does each column and row mean?

The most important part is the first column, the coefficients themselves. The other columns refer to the errors around their estimation. Imagine each coefficient is a Gaussian distribution: `se(coef)` is the *standard error*, the sigma, it gives you an estimate as to how good your model conversion was. The lower and upper bounds are the range of values the coefficients are assuming under 95% confidence. If the range is too high, you might want to check for better convergence.

> 2. I've tried to change the penalizer_coef, below is set at zero, the more I increase it, the worse it is.

Usually, the `penalizer_coef` can vary somewhat comfortably from `0.001` to `0.5` &mdash; though it would be nicer to have it at max around `0.1`. How high did you go? Too high and the model migh basically become useless.

Also, I would say that you should focus on making your model fit well with the `0` and `1` groups of the *holdout vs calibration purchases graph*, as they represent 70-90% of the customers usually. There are other graphs that will indicate your model's performance also, try checking them out in conjunction with this graph.

**Comment by ZhengTzer** [comment]
i must have done something, but i have no clue where

for example:
i get the out from "summary_data_from_transaction_data" and cross check with my own RFM on one of the customer
```
summary_data_from_transaction_data
frequency              5.0
```
```
my own rfm
uniqueOrderID        7
```

1.) I understand the frequency have to minus 1, the customer have 7 purchase, therefore the frequency should be 6?

2.) the documentation explain the T, which I am confused

> T represents the age of the customer in whatever time units chosen (weekly, in the above dataset).

isn't it normal for data to be daily?
if my data is the usual daily data, the 'T' is daily, am i correct?

thanks

**Comment by ZhengTzer** [comment]
```you should focus on making your model fit well with the 0 and 1 groups of the holdout vs calibration purchases graph, as they represent 70-90% of the customers usually. ```

this is something I doesn't know, thanks

regard the previous question, the ```bgf.summary``` is for the total group,
as you recommend focus on ```0``` and ```1``` group, how?

can you suggest me some reading, as i really would love to understand what the first column really mean
thanks!

**Comment by psygo** [comment]
> Regarding the previous question, the `bgf.summary` is for the total group, as you recommend focus on `0` and `1` group, how?

I would say you should try to optimize the fit of the `plot_calibration_purchases_vs_holdout_purchases` on the `0` and `1` groups.

> Can you suggest me some reading? As I really would love to understand what the first column really mean.

Most of what I know comes from Prof. Fader's articles and [Prof. Bruce Hardie's website](http://brucehardie.com/).

**Comment by andrewng88** [comment]
@psygo Thanks for the penalizer_coef guideline.

[https://i.imgur.com/jxh86GV.png](url)
Pls see this image.
LHS no penalizer

So when I observe the 0,1 if the orange and blue is as close as possible it would be the best since the error is the least. Is there an output for an error so that I can use the penalizer as a hyperparameter than obtain the best value rather than looking at charts to compare

**Comment by ZhengTzer** [comment]
other than observing, which indicator in bgf.summary should we minimize in the coef column?
r
alpha
a
b

**Comment by GrowthJeff** [comment]
> Also, I would say that you should focus on making your model fit well with the `0` and `1` groups of the _holdout vs calibration purchases graph_, as they represent 70-90% of the customers usually. There are other graphs that will indicate your model's performance also, try checking them out in conjunction with this graph.

I found this very insightful. Thank you!
