### ISSUE TITLE
 doubts about  BG/NBD data shape, and parameters from conditional_expected_number function

### ISSUE THREAD

**Issue by wallacez1** [CamDavidsonPilon/lifetimes#336]
First of all, I dont have words to compliment and congratulate for this amazing work.

I have a couple doubts about the **BG/NBD model**

1.  Reading the docs, customers with one purchase should be given a recency of 0 which I did but when I tried to train my model I faced a lot of issues as:

    ```none
    RuntimeWarning: invalid value encountered in multiply
      defvjp(anp.exp,    lambda ans, x : lambda g: ans * g)

    RuntimeWarning: divide by zero encountered in log
    ```

    ```none
    The model did not converge. Try adding a larger penalizer to see if that helps convergence.
    ```

    In the end, I could only train my model after exclude customers with one purchase , why that so?

2.  In the `conditional_expected_number_of_purchases_up_to_time` function the `t` parameter refers to which unit of time? 

Again, thank you so much, sorry for my English, congratulations to your work from Brazil.

**Comment by clausherther** [comment]
> customers with one purchase should be given a recency of 0 

I think you meant **frequency** of 0?

**Comment by wallacez1** [comment]
> > customers with one purchase should be given a recency of 0
> 
> I think you meant **frequency** of 0?

hey clausherther

took from the docs 

> **recency** represents the age of the customer when they made their most recent purchases. This is equal to the duration between a customer’s first purchase and their latest purchase. (Thus if they have made only 1 purchase, the recency is 0.)

**Comment by psygo** [comment]
> In the end, I could only train my model after exclude customers with one purchase , why that so?

Using `recency = 0` for customers with only `1` purchase should be correct, maybe it's a problem with your dataset, I'm not sure. Perhaps you could share a sample of it containing the same problem?

> In the `conditional_expected_number_of_purchases_up_to_time` function the `t` parameter refers to which unit of time? 

**`t` is the unit of time of your dataset**. If you're using days, `t` will be in days. If you're using weeks, `t` will be in weeks.

**Comment by wallacez1** [comment]
frequency recency T
0         1.0      0.0  125.0
1         2.0      2.0   97.0
2         2.0     25.0   98.0
3         1.0      0.0   89.0
4         1.0      0.0   68.0
5         3.0     34.0   36.0
6         5.0     18.0   96.0
7         1.0      0.0  107.0
8         2.0     86.0   93.0
9         1.0      0.0   66.0
10        2.0     49.0   97.0
11        2.0     53.0   90.0
13        1.0      0.0   13.0
14        2.0     50.0   90.0
15        8.0     67.0   79.0
16        3.0     66.0   69.0
17        1.0      0.0   60.0
18        1.0      0.0  114.0

**frequency represents the number of repeat purchases the customer has made. This means that it’s one less than the total number of purchases. This is actually slightly wrong. It’s the count of time periods the customer had a purchase in** i got a little confuse with that definition

this is sample of my data, i took frequency as the **number of repeat purchases** that a customer has made and manually assign value 0 to recency.

**Comment by trantrikien239** [comment]
@wallacez1 Hi, I could be wrong but how could recency = 0 when frequency = 1?
As I understand frequency = 1 means the customer has done 2 purchases ->  There should be recency > 0 as the time between two purchases, isn't it?
Or maybe I misunderstand something. Happy to discuss more though :D

**Comment by thomasburgess** [comment]
I found that for my data, and frequency 0, `hyp2f1` can become negative which raises the warning when taking its log. It seems this happens when `|a+b|~=1`, which shrinks the denominator and thus grows terms in hyp2f1, so the negative results could come from some overflow. Increasing regularization with `penalizer_coeff` reduces the magnitude of `a` and `b` which removes the problem.

**Comment by ram83** [comment]
I am facing exactly the same issue. below are my definitions:
frequency is the number of purchases. ie. 1 if someone has made only 1 purchase
recency is 0, if frequency is 1
since a lot of our customers have made only 1 purchase, excluding them from this exercise is not an option for me.
@wallacez1 were you able to resolve this issue?
