### ISSUE TITLE
What to do with the Gamma-Gamma model when the independence assumption fails?

### ISSUE THREAD

**Issue by jnguyen32** [CamDavidsonPilon/lifetimes#337]
The Gamma-Gamma model says that we need to have the Pearson correlation between monetary value and frequency approximately equal zero. 

What do we do when it isn't the case? What's the alternative model that should be used in this situation?

**Comment by psygo** [comment]
I don't know, but, from what I remember, it is surprisingly very rare for that to *not* be the case.

If I were you, I would try to find out some more info on the topic in the literature. For example, [Prof. Bruce Hardie's website](http://brucehardie.com/notes/025/) is full of notes.

**Comment by kumarnav03** [comment]
How much Pearson correlation is acceptable between monetary value & frequency( Eg. in my use case correlation is 0.24)?
