### ISSUE TITLE
Individual error (client level)

### ISSUE THREAD

**Issue by intiveda** [CamDavidsonPilon/lifetimes#338]
Hello, 

I am trying to get an estimate of the error / accuracy at a client level. Trying to answer this question: "how good is my prediction?"

Is there any way to perform this? Perhaps retrieving the RSME of the regularisation?

Thank you in advance. 

Also, thank the developers for maintaining this library! 💟

**Comment by psygo** [comment]
You could compute the `RMSE` errors with respect to the `plot_cumulative_transactions` and `plot_incremental_transactions` graphs. That's something I wanted to do for a while now.

But keep in mind that these are statistical models. *They do not work wonders at the individual level*, their objective is to fit the distribution of customers. So, it is totally possible that you could make gross mistakes for most individuals while doing well on the global distribution &mdash; though that gets more and more unlikely as more data comes in.
