### ISSUE TITLE
Why does conditional_probability_alive return only a list of probabilities?

### ISSUE THREAD

**Issue by jnguyen32** [CamDavidsonPilon/lifetimes#341]
Quick question: How come the `conditional_probability_alive` doesn't return a dataframe that shows the customer ID with the probability? Is it safe to append it to the summary dataframe?

**Comment by psygo** [comment]
The *conditional* of `conditional_probability_alive ` comes from conditioning the probability of a customer being alive on RFM parameters, i.e., `recency`, `frequency` and `T`. Many different customers might have the same RFM parameters.

That is just a definition coming from theory and literature. You can create new submethods for the fitter if you want, or apply `conditional_probability_alive` to each customer with `pandas`'s `.apply` for example.

**Comment by saran-p** [comment]
"conditional_probability_alive"  computes the probability that a customer with history (frequency, recency, T) is currently alive.. 

Is there a method to find the probability that a customer will be alive after t units? for e.g. probability that a customer will be alive after 5 years
