### ISSUE TITLE
Frequency Calculation

### ISSUE THREAD

**Issue by Tabixe** [CamDavidsonPilon/lifetimes#344]
In your documentation you suggest this query:

```SQL
SELECT
  customer_id,
  COUNT(distinct date(transaction_at)) - 1 as frequency,
  datediff('day', MIN(transaction_at), MAX(transaction_at)) as recency,
  AVG(total_price) as monetary_value,
  datediff('day', CURRENT_DATE, MIN(transaction_at)) as T
FROM 
  orders
GROUP BY 
  customer_id
```

If the point is to not take into account the first purchase for the calculation of the Frequency, What happens when the two first purchases are in the same period? In that case, that period should be count and your query is not counting it.

I think that this should be the query:

```SQL
with orders AS (

SELECT
  customer_id,
  transaction_at,
  ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY transaction_at) as ranking
FROM 
  orders
GROUP BY 
  customer_id

),

freq AS (

SELECT
      customer_id,
      COUNT(DISTINCT date(transaction_at)) as frequency
FROM
      orders 
WHERE
      ranking <> 1
GROUP BY
      customer_id

),

other AS (

SELECT
  customer_id,
  datediff('day', MIN(transaction_at), MAX(transaction_at)) as recency,
  AVG(total_price) as monetary_value,
  datediff('day', CURRENT_DATE, MIN(transaction_at)) as T
FROM 
  orders
GROUP BY 
  customer_id

)

SELECT
  *
FROM
  other 
  LEFT JOIN freq USING (customer_id)
```

**Comment by Tabixe** [comment]
The same issue happens with your transformation from transactions data to frequency, recency and T data on your function  [`summary_data_from_transaction_data`](https://github.com/CamDavidsonPilon/lifetimes/blob/e197c1ca310adb31cd8775335ce5654cefc211ba/lifetimes/utils.py#L216).

````Python
# subtract 1 from count, as we ignore their first order.
    customers["frequency"] = customers["count"] - 1
````

**Comment by psygo** [comment]
I'm not sure if I understood it correctly. Do you mean we are not accounting for intra-period transactions as possibly more than 1 purchase?

If that's the case, it's considered normal. Usually, we simply group intra-period transactions as a single purchase. I think that could be a problem if your period is more than a day, but otherwise I don't think it's that relevant.

In any case, consider creating a new *PR*, if you think it's relevant.
