### ISSUE TITLE
Modelling Recurrent Events with Extra Features

### ISSUE THREAD

**Issue by indiana-nikel** [CamDavidsonPilon/lifetimes#346]
Hello,

I'm working on a project where I'm looking to predict the length of time until next purchase of a given customer. I'm finding this package extremely helpful for this using the pure sales figures ("recency", "frequency", "T"), but I'm curious about it's limitations.

I'd like to incorporate more information about my dataset:
* Demographic data (categorical or continuous; constant across time; ie. "income of neighborhood")
* Related events data (categorical or continuous; varying across time; ie. "number of interactions with customer support")
* Weighting the "sale" event (in the case that the value of the sale does not represent the magnitude of the sale)

I may have missed this reading through the documentation and referenced papers, but I'm curious if these types of information are able to be incorporated into the modelling procedure.

Best,
Indiana

**Comment by psygo** [comment]
As far as I know, the models here only deal with RFM, unfortunately. If you wish to add variables, my suggestion would be add a new layer to it that uses these results in conjunction with more modern data science approaches, like Neural Networks. You could create a Decision Tree that uses these two models as input to make a better decision, that's the only way I can see to incorporate categories into it.

The derivations of the models here are all made essentially analytically and then simulated and fitted using data and computing, which means that incorporating new variables is not so trivial. However, Monte Carlo models offer a more simplified approach to deriving new models analytically, which is something I have previously tried to discuss in Issue #312.
