### ISSUE TITLE
Unclear how monetary_value is calculated

### ISSUE THREAD

**Issue by ZhengTzer** [CamDavidsonPilon/lifetimes#347]
I had read through the documentation which stated:

```
This is equal to the sum of all a customer's purchases divided by the total number of purchases...
```

SQL:

```sql
AVG(total_price) as monetary_value,
```

I try to check back with my own data, `frequency = 3`, it's correct:

```python
data = [[236,'john'], [118,'john'], [236,'john'], [99,'john']]
df = pd.DataFrame(data, columns = ['sales', 'name'])
```

The average should be `172.25`, but why the `monetary_value` in `summary_data_from_transaction_data` shows `190.33`. Where does `190.33` come from?

Thanks a lot

**Comment by psygo** [comment]
I think there are 2 possibilities:

1. In the [calculation of mean for the `monetary_value`](https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/utils.py#L276), the first purchase is excluded, since it is not a repeat purchase (you could change this with your own code if you want...).
    ```python
    # by setting the monetary_value cells of all the first purchases to NaN,
    # those values will be excluded from the mean value calculation
    ```
1. Part of your data is being filtered out because it is outside of the specified date range.

**Comment by ZhengTzer** [comment]
ok, got it, thanks!

**Comment by utkarshgupta137** [comment]
Why is the monetary value of the first purchase not included while calculating the average monetary value? It doesn't make sense.

**Comment by utkarshgupta137** [comment]
Why is the monetary value of the first purchase not included when calculating the average monetary value? It doesn't make sense. I understand we're talking about repeat purchases, but first purchase monetary value should also be included while calculating the average monetary value.
It seems this behaviour was introduced in https://github.com/CamDavidsonPilon/lifetimes/commit/bd6b73e2f3ea92cbdce936015715a18a65d1e043, which is unrelated to the change it is making.
