### ISSUE TITLE
Bug in lifetimes.utils.calibration_and_holdout_data

### ISSUE THREAD

**Issue by nfmoore** [CamDavidsonPilon/lifetimes#348]
There is a bug in the `calibration_and_holdout_data` function. 

When running the following code block:

```python
from lifetimes.datasets import load_transaction_data
from lifetimes.utils import summary_data_from_transaction_data
from lifetimes.utils import calibration_and_holdout_data

transaction_data = load_transaction_data()


summary_cal_holdout = calibration_and_holdout_data(
    transaction_data, 'id', 'date',
    calibration_period_end='2014-09-01',
    observation_period_end='2014-12-31'
)
print(summary_cal_holdout.head())
```

This following error is produced:

```none
<ipython-input-1020-46fc86bc584d> in calibration_and_holdout_data(transactions, customer_id_col, datetime_col, calibration_period_end, observation_period_end, freq, datetime_format, monetary_value_col)
     65     combined_data.fillna(0, inplace=True)
     66 
---> 67     delta_time = (to_period(observation_period_end) - to_period(calibration_period_end)).n
     68     combined_data["duration_holdout"] = delta_time
     69 

AttributeError: 'int' object has no attribute 'n'
```

This occurs since `(to_period(observation_period_end) - to_period(calibration_period_end))` returns an integer. When you remove `n` the issue is resolved. I'm using version 0.25.3 of pandas.

**Comment by SUBHAMILA** [comment]
In Utils.py available in Lifetimes, 
the following changes can be made to avoid this error:

def calibration_and_holdout_data(
    transactions,
    customer_id_col,
    datetime_col,
    calibration_period_end,
    observation_period_end=None,
    freq="D",
    datetime_format=None,
    monetary_value_col=None,
):
   
    def to_period(d):
        return d.to_period(freq)

    if observation_period_end is None:
        observation_period_end = transactions[datetime_col].max()

    transaction_cols = [customer_id_col, datetime_col]
    if monetary_value_col:
        transaction_cols.append(monetary_value_col)
    transactions = transactions[transaction_cols].copy()

    transactions[datetime_col] = pd.to_datetime(transactions[datetime_col], format=datetime_format)
    observation_period_end = pd.to_datetime(observation_period_end, format=datetime_format)
    calibration_period_end = pd.to_datetime(calibration_period_end, format=datetime_format)

    # create calibration dataset
    calibration_transactions = transactions.loc[transactions[datetime_col] <= calibration_period_end]
    calibration_summary_data = summary_data_from_transaction_data(
        calibration_transactions,
        customer_id_col,
        datetime_col,
        datetime_format=datetime_format,
        observation_period_end=calibration_period_end,
        freq=freq,
        monetary_value_col=monetary_value_col,
    )
    calibration_summary_data.columns = [c + "_cal" for c in calibration_summary_data.columns]

    # create holdout dataset
    holdout_transactions = transactions.loc[
        (observation_period_end >= transactions[datetime_col]) & (transactions[datetime_col] > calibration_period_end)
    ]

    if holdout_transactions.empty:
        raise ValueError(
            "There is no data available. Check the `observation_period_end` and  `calibration_period_end` and confirm that values in `transactions` occur prior to those dates."
        )

    holdout_transactions[datetime_col] = holdout_transactions[datetime_col].map(to_period)
    holdout_summary_data = (
        holdout_transactions.groupby([customer_id_col, datetime_col], sort=False)
        .agg(lambda r: 1)
        .groupby(level=customer_id_col)
        .agg(["count"])
    )
    holdout_summary_data.columns = ["frequency_holdout"]
    if monetary_value_col:
        holdout_summary_data["monetary_value_holdout"] = holdout_transactions.groupby(customer_id_col)[
            monetary_value_col
        ].mean()

    combined_data = calibration_summary_data.join(holdout_summary_data, how="left")
    combined_data.fillna(0, inplace=True)

    delta_time = to_period(observation_period_end) - to_period(calibration_period_end)
    combined_data["duration_holdout"] = delta_time

    return combined_data

**Comment by psygo** [comment]
Please create a PR if you think this solves the problem.
