### ISSUE TITLE
doubt about bgf.conditional_expected_number_of_purchases_up_to_time return

### ISSUE THREAD

**Issue by wallacez1** [CamDavidsonPilon/lifetimes#349]
On the documentation this is the definition of the return to this method.

> Models expose a method that will predict a customer’s expected purchases in the next period using their history

this number represent how many purchases the customer will make in the period or the probability of the customer of buying on the period?

![image](https://user-images.githubusercontent.com/37086969/71772271-79af8f00-2f27-11ea-9f6d-45625258ef23.png)

im slightly confuse, because if represent the how many purchases, for example: the id **1516** has 0.71 of predict purchases what thats means?, i tought would be a integer number like the customer A will make X purchases on this period.

thank you so much in advance

**Comment by psygo** [comment]
It's the average number of purchases he will make in that period, which is a real number (`0` to `infinity`). For example, for ID `509`, it is expected that she will buy approximately `0.42` times.

The average of `1` and `2` is `1.5`, even though `1.5` is not an integer. This is perfectly valid in probability and when calculating averages.

The probability of a customer being alive or active is calculated by the method `conditional_probability_alive`.

https://github.com/CamDavidsonPilon/lifetimes/blob/e197c1ca310adb31cd8775335ce5654cefc211ba/lifetimes/fitters/beta_geo_fitter.py#L258
