### ISSUE TITLE
AttributeError: 'BetaGeoFitter' object has no attribute 'summary'/'param_' respectively

### ISSUE THREAD

**Issue by ObiWanFoley** [CamDavidsonPilon/lifetimes#350]
It appears that for some reason certain attributes are not being "loaded" (new to python...likely the incorrect jargon). When making a new LTV notebook and following the quick-start guide I can successfully call `.fit` and print `BetaGeoFitter`. After that the docs reference having access to the attributes `summary` and `param_` however when attempting to call `BetaGeoFitter.summary` and `BetaGeoFitter.param_` I get `AttributeError: 'BetaGeoFitter' object has no attribute 'summary' / 'param_'` respectively.

Running dir(BetaGeoFitter) gives me the following:

```
['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_negative_log_likelihood',
 '_unload_params',
 'conditional_expected_number_of_purchases_up_to_time',
 'conditional_probability_alive',
 'conditional_probability_alive_matrix',
 'expected_number_of_purchases_up_to_time',
 'fit',
 'load_model',
 'probability_of_n_purchases_up_to_time',
 'save_model']
```

of which summay and `param_` are missing. looking at the attributes present, I have no issues calling anything shown here.

I don't know if this is an issue with `__init__.py` but potentially having a local call to def summary(self) could alleviate the issue?? Like I said... I'm pretty new to Python so I could be way off.

**Comment by psygo** [comment]
This is strange. The `BetaGeoFitter` inherits the `BaseFitter` from `__init__.py`, which does have the `summary` property. It should work, and has worked for me in the not so far past.

https://github.com/CamDavidsonPilon/lifetimes/blob/e197c1ca310adb31cd8775335ce5654cefc211ba/lifetimes/fitters/__init__.py#L124

Maybe you could share your code here so we could try reproducing it locally. Are you using only the tutorial code?

**Comment by ObiWanFoley** [comment]
yes...in a local jupyter notebook. I initially was using my own dataset but was getting hung by not being able to check my alpha values so I tried with pure copy/paste of the tutorial code and got the same errors.

[Quickstart Copy](https://github.com/ObiWanFoley/issue-tracking/blob/master/lifetime_value-Copy1.ipynb)

**Comment by ObiWanFoley** [comment]
Just for reference...I figure you will ask anyway:
`!python --version
Python 3.6.9
`
and

`!pip list`
------------
`autograd (1.3)
backcall (0.1.0)
cycler (0.10.0)
decorator (4.4.1)
dill (0.3.1.1)
future (0.18.2)
ipython (7.11.1)
ipython-genutils (0.2.0)
jedi (0.15.2)
kiwisolver (1.1.0)
Lifetimes (0.11.1)
matplotlib (3.1.2)
nbextensions (0.1.0)
numpy (1.18.1)
pandas (0.25.3)
parso (0.5.2)
pexpect (4.7.0)
pickleshare (0.7.5)
pip (9.0.1)
pkg-resources (0.0.0)
prompt-toolkit (3.0.2)
ptyprocess (0.6.0)
Pygments (2.5.2)
pyparsing (2.4.6)
python-dateutil (2.8.1)
pytz (2019.3)
scipy (1.4.1)
setuptools (39.0.1)
six (1.13.0)
traitlets (4.3.3)
wcwidth (0.1.8)`

**Comment by psygo** [comment]
Very strange. When I get home, I'll see what I can do.

I would suggest downgrading the `lifetimes` a version or two and see what happens. It has helped me in the past when trying to work around some bugs.

**Comment by ObiWanFoley** [comment]
So i downgraded to 0.10.1 and then to 0.9.0 and same issue. Then I went back to 0.11.1 and `params_` magically appeared however `summary` still isn't being recognized. Looking through the change log and trying to call different attributes it also appears that `confidence_interval_`, `variance_matrix_` and `standard_errors_` are not being recognized as well. I looked through the source code and these are being built also referencing `__init__.py` however `params_` is now showing as being written within the fitter itself.

**Comment by psygo** [comment]
So... I had not used this library in a while and I changed my PC (Windows now) in the meantime. It had some versions of `Python` on it, which kind of complicated things, so I deleted all of them to start with a clean slate. Then:

1. Installed the latest version of `Python`: `3.8.1`.
1. Installed the `lifetimes` library using:
    ```cmd
    pip install --user lifetimes
    ```
1. Copied the code in the [Quickstart tutorial](https://lifetimes.readthedocs.io/en/latest/Quickstart.html) verbatim into a terminal to see how if it works with pure `Python`, no `Anaconda` or `Jupyter` stuff.
    - It did work. Good or bad news?
    ```python
    from lifetimes.datasets import load_cdnow_summary
    from lifetimes import BetaGeoFitter

    data = load_cdnow_summary(index_col=[0])
    bgf = BetaGeoFitter(penalizer_coef=0.0)
    bgf.fit(data['frequency'], data['recency'], data['T'])

    print(bgf)
    print(data.head())

    bgf.summary
    bgf.params_
    ```

Well, here is what I would suggest as options to solve your problem:

- Follow the procedure I mentioned and see if it works for you.
- Maybe go deeper into compatibility issues with `Anaconda` and/or `Jupyter`.
- I remember that, in the past, I got stuck with some compatibility problems with `pandas` for some reason. I think I had to downgrade it to `0.21` to make things work I believe.

**Comment by ObiWanFoley** [comment]
Awesome. I will try that out. I’m not using ‘Anaconda’ so that shouldn’t be an issue. Everything is in a virtualenv so I can mess around with some python versions of different libraries and see what I can get to work. I will also run it purely on the terminal (Ubuntu 18.04) and maybe in ‘vscode’ and see if it is maybe a JN issue. I really appreciate all the time you are spending on this...I’ll update tomorrow and add some closing comments with my final findings.

**Comment by ObiWanFoley** [comment]
I nuked the env that I was running this in and created a fresh evn with `python==3.6.9`. I installed `lifetimes==0.11.1` and followed the Quickstart Tutorial in the terminal line by line and had no issues. Was able to run `bgf.summary` and all of the new attributes with no issues.
I then installed JN using `pip install notebook`, again in the virtual environment, and ran through the same Quickstart Guide line by line. Again...no issues. Able to run all utilities and call all attributes with no errors. When I check my current environment vs the previous using `pip list` I found that I was using a version of notebook that I had previously installed using `pip install --user notebook` because I didn't see any of the dependencies installed in the previous `pip list`.

I think my next step is to look at the list above and install each library line by line into my virtual environment and see which one breaks it. 

All that to say it looks as though this is not a version issue or an issue with the library itself, but could be related to a package that I had installed and is potentially from a dependency installed in a recent install of `pip install --user notebook`.

Given the popularity of `Jupyter Notebook` there should likely be a note stating a minimum `notebook` version recommended which I will be glad to supply. If you don't think this is necessary then please feel free to close the comment.

**Comment by ObiWanFoley** [comment]
installed 3 separate versions of notebook and replicated the packages and versions as shown above and had no issues with running the full library. I will keep an eye on this and reopen the issue if it happens again. I will be sure to better outline the versions and libraries installed instantly if I run into this again.
