### ISSUE TITLE
Palive=1 

### ISSUE THREAD

**Issue by cristiano74** [CamDavidsonPilon/lifetimes#352]
Dear all,
 I'm using data of last 10 years: customers usually buy 3,4 times in the calibration period.  When I calculate the P(alive) I get **P(alive)=1** for almost all customers. I use ModifiedBetaGeoFitter(penalizer_coef=0.01)

Where I get wrong?

Any suggestions would be really appreciated.

**Comment by psygo** [comment]
I don't know if 10 years is advisable... I would filter your data to a more recent window, close to 2 years probably. Another thing you could try is increasing the `penalizer_coef`.

If there are too many customers doing recurrent purchases during these 10 years (unlikely, I know), then the model would probably be kind of correct to assume P(alive) = 1.

In any case, we would need to see your graphs to be able to help more effectively.
