### ISSUE TITLE
plot_period_transactions failed for BetaGeoBetaBinomFitter

### ISSUE THREAD

**Issue by hmikelee** [CamDavidsonPilon/lifetimes#354]
Dear Sir,

While testing BG/BB models, I came across the following error when calling `plot_period_transactions` to verify the fitting results

```py
TypeError: unsupported operand type(s) for +: 'int' and 'list'
```

Traceback below:

```py
TypeError                                 Traceback (most recent call last)
<ipython-input-30-4d245b7ff070> in <module>()
      2 bbf.fit(summary_monthly['frequency'], summary_monthly['recency'], summary_monthly['n_periods'])
      3 print(bbf)
----> 4 plot_period_transactions(bbf)
      5 
      6 for period in summary_monthly['n_periods'].unique():

~/anaconda3/lib/python3.6/site-packages/lifetimes/plotting.py in plot_period_transactions(model, max_frequency, title, xlabel, ylabel, **kwargs)
     59 
     60     n = model.data.shape[0]
---> 61     simulated_data = model.generate_new_data(size=n)
     62 
     63     model_counts = pd.DataFrame(model.data["frequency"].value_counts().sort_index().iloc[:max_frequency])

~/anaconda3/lib/python3.6/site-packages/lifetimes/fitters/beta_geo_beta_binom_fitter.py in <lambda>(size)
    167         self.generate_new_data = lambda size=1: beta_geometric_beta_binom_model(
    168             # Making a large array replicating n by n_custs having n.
--> 169             np.array(sum([n_] * n_cust for (n_, n_cust) in zip(n_periods, weights))),
    170             *self._unload_params("alpha", "beta", "gamma", "delta"),
    171             size=size

TypeError: unsupported operand type(s) for +: 'int' and 'list'
```

`BetaGeoBetaBinomFitter.fit` went ok

I am attaching the screenshot of the notebook below

![image](https://user-images.githubusercontent.com/34959055/73828505-520c5900-483c-11ea-90e9-abb3a7cccbe5.png)

**Comment by SUBHAMILA** [comment]
code with error : ` self.generate_new_data = lambda size=1: beta_geometric_beta_binom_model(
            # Making a large array replicating n by n_custs having n.
            np.array(sum([n_] * n_cust for (n_, n_cust) in zip(n_periods, weights))),
            *self._unload_params("alpha", "beta", "gamma", "delta"),
            size=size
        )` 
i think the following changes may solve  your problem .
try doing this : 
you get that error because one is integer value and other is list.

try this : 

` self.generate_new_data = lambda size=1: beta_geometric_beta_binom_model(
            # Making a large array replicating n by n_custs having n.
            np.array(sum([n_] * sum(n_cust) for (n_, n_cust) in zip(n_periods, weights))),
            *self._unload_params("alpha", "beta", "gamma", "delta"),
            size=size
        )`

**Comment by psygo** [comment]
@SUBHAMILA, [please use three backticks (`) for code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks), otherwise this is illegible.

**Comment by Trollgeir** [comment]
> code with error : ` self.generate_new_data = lambda size=1: beta_geometric_beta_binom_model( # Making a large array replicating n by n_custs having n. np.array(sum([n_] * n_cust for (n_, n_cust) in zip(n_periods, weights))), *self._unload_params("alpha", "beta", "gamma", "delta"), size=size )`
> i think the following changes may solve your problem .
> try doing this :
> you get that error because one is integer value and other is list.
> 
> try this :
> 
> ` self.generate_new_data = lambda size=1: beta_geometric_beta_binom_model( # Making a large array replicating n by n_custs having n. np.array(sum([n_] * sum(n_cust) for (n_, n_cust) in zip(n_periods, weights))), *self._unload_params("alpha", "beta", "gamma", "delta"), size=size )`

This did not work.

This did though:

> The solution that worked was to modify row 169 in beta_geo_beta_binom_fitter.py from  `np.array(sum([n_] * n_cust for (n_, n_cust) in zip(n_periods, weights)))` to `np.array(sum([[n_] * >n_cust for (n_, n_cust) in zip(n_periods, weights)], []))`

Credits to @cereusperuv  (https://github.com/CamDavidsonPilon/lifetimes/issues/259#issuecomment-480820040)
