### ISSUE TITLE
Pareto/GGG

### ISSUE THREAD

**Issue by chanansh** [CamDavidsonPilon/lifetimes#360]
Do you support the Pareto/GGG model?

See Pareto/GGG:

Platzer, Michael, and Thomas Reutterer, *Ticking Away the Moments: Timing Regularity Helps to Better Predict Customer Activity*, Marketing Science (2016).

[Implementation in R](https://github.com/mplatzer/BTYDplus).

**Comment by jonimatix** [comment]
This would be a great implementation as it proves to be very effective for non-subscription based scenarios.
