### ISSUE TITLE
Negative values from customer_lifetime_value

### ISSUE THREAD

**Issue by ywu-stats** [CamDavidsonPilon/lifetimes#362]
How can should I interpret the negative CLV from customer_lifetime_value?
I already turn on q_constrain on ggf.fit.
Thank you!

**Comment by psygo** [comment]
This is too broad a question and is mostly answered in the [docs website](https://lifetimes.readthedocs.io/en/latest/). Besides doing a quick search on Google, please take a look at the docs before posting questions here.
