### ISSUE TITLE
Piecewise Exponential cure model with random forest probabilities

### ISSUE THREAD

**Issue by SpirosFot** [CamDavidsonPilon/lifetimes#363]
Hi Cameron,

I would like your guidance regarding the following issue. 

I want to implement a cox like piecewise exponential model with probabilities given not by a logit but by a Random forest.

However I am having trouble understanding how the cumulative hazard function of the PE model should be defined and thus used as a baseline. 

Moreover, while as you have clearly documented for logistic probabilities we can go on like :

```none
p_1 = exp(dot(Xs["c_1"], params["c_1"]))
p_2 = exp(dot(Xs["c_2"], params["c_2"]))
p_3 = 1
p_1 = p_1 / (p_1 + p_2 + p_3)
p_2 = p_2/(p_1+p_2+p_3)
p_3 = p_3/(p_1+p_2+p_3)
```

However for Random Forests I run into trouble when trying to multiply the conditional survival functions with the Random forest probability dataframe. Any clue on how to circumvent that?

**Comment by CamDavidsonPilon** [comment]
I think this is the wrong repo
