### ISSUE TITLE
A justification for the `penalizer_coefficient`'s value

### ISSUE THREAD

**Issue by SUBHAMILA** [CamDavidsonPilon/lifetimes#365]
Can you justify the maths behind `penalizer_coefficient = 0.0`? 

Why is it that value and what range should it lie within?

**Comment by psygo** [comment]
> Can you justify the maths behind `penalizer_coefficient = 0.0`? 

`0` is equivalent to the vanilla model. Giving the user the vanilla model with anything other than non-null `penalizer_coefficient`s would be subtly lying to her.

> Why is it that value and what range should it lie within?

Difficult to state its range. It should probably depend on the problem domain. 

But I wouldn't fare too far out of `1`. Usually, penalizer coefficients in metrics are normalized, so going beyond `1` could mean that the penalization is bigger than the model and data themselves, which is basically the same as missing the point of modeling entirely.
