### ISSUE TITLE
Something like GridSearchCV

### ISSUE THREAD

**Issue by martingg92** [CamDavidsonPilon/lifetimes#386]
Hi everyone, somebody knows if there is a way to find the optimal penalizer coef ?? something like a gridsearch ???

I know that there is a way plotting the gamma distribution, but i have the doubt if there is a numerical combination. I have tried with differerent numbers of penalizer coef and studying the population mean, p, q, v and the negative log likehood and still dont find an answer. 

Here is an example.

![image](https://user-images.githubusercontent.com/42093381/88186143-d1cb8b80-cc02-11ea-9d02-689b617b3b82.png)

In my context, the  best CLV (in terms of magnitude) is when i use a penalizer coef of 0.09, but i want to program a way when we use this method to find an optimal. 

Thanks!!!

**Comment by Harsharajuu** [comment]
Hey 

Just one question how you finalized that 0.09 is the best pernalizer value for CLV..?
