### ISSUE TITLE
Getting black and white images when I use seaborn

### ISSUE THREAD

**Issue by springcoil** [CamDavidsonPilon/lifetimes#39]
Hi Cam,
When I use seaborn it ruins the frequency-recency plots and converts them all to black and white.

**Comment by CamDavidsonPilon** [comment]
Hm, can you post some repro code + what the bw images look like?

**Comment by praneethkumarpidugu** [comment]
I think you are using default seaborn color palletes which are black and white:
you could modify it to color palletets. Check this tutorial out: https://stanford.edu/~mwaskom/software/seaborn/tutorial/color_palettes.html
