### ISSUE TITLE
plot_history_alive not accepting datetime format

### ISSUE THREAD

**Issue by GrowthJeff** [CamDavidsonPilon/lifetimes#392]
Sorry for so opening up so many issues...

My transaction history looks like this:
id          date
XXXX   2019-06-29 18:36:32 

`summary_data_from_transactions` eats up no problem! But then when I attempt `plot_history_alive`  like so:
```
from lifetimes.plotting import plot_history_alive

id = XXXX
days_since_birth = 365
sp_trans = transactions.loc[transactions['id'] == id]
plot_history_alive(bgf, days_since_birth, sp_trans, 'date')
```

I get the error message `ConversionError: Failed to convert value(s) to axis units: '2019-06-29 18:36:32'` Am I a noob messing something up? I'll look to clean the data upstream and then see why it might be failing on this function. Any thoughts?

**Comment by GrowthJeff** [comment]
Update: I stripped the time element and still get this same error.

**Comment by SUBHAMILA** [comment]
from lifetimes.plotting import plot_history_alive
id = 35
days_since_birth = 200
sp_trans = transaction_data.loc[transaction_data['id'] == id]
plot_history_alive(bgf, days_since_birth, sp_trans, 'date')


This worked for me where date is a column in dataframe in the format of yy-mm-dd. Output will be somthing like this.
![image](https://user-images.githubusercontent.com/38394546/89604140-40a61700-d888-11ea-8bfa-8ca4594877a5.png)

Thanks.

**Comment by extrospective** [comment]
Please include updated sample code.
