### ISSUE TITLE
How to tell if my data is suitable for predicted number of purhcases?

### ISSUE THREAD

**Issue by soliverc** [CamDavidsonPilon/lifetimes#400]
I am getting terrible results for the `conditional_expected_number_of_purchases_up_to_time` function, predicting 31 days out. 

I'm trying out different penalizers for the `ModifiedBetaGeoFitter` and here are the results. Average frequency is 0.44. The errors are at least that big or bigger. Mean absolute percentage error is 200,000%

![image](https://user-images.githubusercontent.com/47222261/95307926-29cc7280-0881-11eb-83ff-cb68f25c3a03.png)

I don't think my dataset is anything out of the ordinary. Perhaps there are not enough purchases per customer? The time period is days. There are customers with only a handful of transactions in over a year. Could  that be the problem?

There are roughly 20,000 transactions, starting from Jan 2019 to now. 

![image](https://user-images.githubusercontent.com/47222261/95309283-d9561480-0882-11eb-9dd7-6d3e596cdc7e.png)

If anybody wants to inspect the data in more detail, here's a link:

https://drive.google.com/file/d/11s9f_r6VMDu0jXXZz52mFti1O2G28WLf/view?usp=sharing

**Comment by Harsharajuu** [comment]
Hi,

I am also trying to build CLV with similar set of transactions data and can you share the codes which you are used to get the above results for all the penalizer values the mse and mape 

That would be helpful
