### ISSUE TITLE
Data check for CLV and Best value for Penalizer for BG/NBD and Gamma-Gamma model 

### ISSUE THREAD

**Issue by Harsharajuu** [CamDavidsonPilon/lifetimes#403]
Hi Cameron,

I have transactional data set with nearly 15000 customers and their transactional data history for past 2 years and trying to predict CLV using BG/NBD OR MBG/NBD followed by Gamma-Gamma Model 

Below are the questions which I am seeking help

1. What the tests which i need to check with my dataset before i proceed using BGNBD model?
     As of now I have the correlation between frequency and monetary value which is -0.3 (Looks this is not highly correlated) 

2. How to arrive at the optimal cut off value for penalizer for model building

Thanks for the help in advance

**Comment by ayadav1** [comment]
+1

**Comment by ashlyrclark** [comment]
O
