### ISSUE TITLE
calculate_alive_path / plot_history_alive probabilities almost always equal to 1

### ISSUE THREAD

**Issue by Louva1** [CamDavidsonPilon/lifetimes#409]
Hello!

I am following the steps taking by: https://towardsdatascience.com/whats-a-customer-worth-8daf183f8a4f with the same data set. However, for the probabilities of being alive I only get values of 1, instead of the expected behaviour of slowly 'dying' after their last purchase. I used the following model:
<img width="459" alt="Screenshot 2020-12-03 at 16 00 24" src="https://user-images.githubusercontent.com/75436140/101045631-b8f3bf00-3580-11eb-8a91-c2b96998f602.png">
I do have many 1-time purchases, as can be seen from the recency histogram.
<img width="399" alt="Screenshot 2020-12-03 at 15 58 28" src="https://user-images.githubusercontent.com/75436140/101045754-cdd05280-3580-11eb-9005-93c6ec597ba1.png">
All the plot_history_alive graphs I get look like:
<img width="728" alt="Screenshot 2020-12-03 at 16 00 11" src="https://user-images.githubusercontent.com/75436140/101045906-ed677b00-3580-11eb-82eb-842a42578337.png">
Does someone know how this happens and why I get different results from TowardsDataScience with exactly the same steps and data?

Thank you in advance!

**Comment by roestigraben** [comment]
Hi,
I have exactly the same problem.
I think that this is an error. I hacked it by adding 'facked' 2nd transaction into the dataframe with exactly the same date as the first-time transaction. Then it follows the curve of dying alive probability.

I am currently looking into the source code to better understand.

BTW: There is yet another problem I have not understood. The alive probability is starting at ~65% which for me is not reflecting any intuition. It should start at 100% and quickly fall to lower levels as intuitively understood.
If you have any comments on this, I welcome them very much
