### ISSUE TITLE
summary_data_from_transaction_data() returns different result when monetary_value_col included

### ISSUE THREAD

**Issue by jackyckma** [CamDavidsonPilon/lifetimes#41]
Hi I found that summary_data_from_transaction_data() returns a different result when monetary_value_col is included. Specifically, when there are multiple transaction (of different price) in the same day, the result will be incorrect.

I chased the code and believe the cause is:
period_transactions = reduce_events_to_period(transactions, *select_columns).reset_index(level=select_columns[1:])

which will grouped the dataframe by *select_columns, and I think monetary_value_col should not be included.

So perhaps a modification is  
period_transactions = reduce_events_to_period(transactions, [customer_id_col, datetime_col]).reset_index(level=select_columns[1:])

While at the same time, (near the end of the function):
customers['monetary_value'] = period_transactions.groupby(level=customer_id_col)[monetary_value_col].mean()

should be changed to:
customers['monetary_value'] = transactions.groupby(customer_id_col)[monetary_value_col].mean()

**Comment by rhydomako** [comment]
I agree with @jackyckma -- see #40

**Comment by jackyckma** [comment]
It seems the above code can't really run. I modified a bit and tested on a branch and just submitted a pull request for your review.
