### ISSUE TITLE
Will LifeTimes support the R language BTYDplus package?

### ISSUE THREAD

**Issue by ArcherZX** [CamDavidsonPilon/lifetimes#413]
I can't find a Python package like BTYDplus

**Comment by isabellec23** [comment]
Following

**Comment by BBDS-Colt** [comment]
No; development on `lifetimes` ceased 3 years ago, and the most recent commit for BTYDPlus was in Jan 2021.

 `pymc-marketing` is the successor library, and we've discussed adapting the models from BTYDPlus:

https://github.com/pymc-labs/pymc-marketing/issues/91
