### ISSUE TITLE
lifetimes.utils.ConvergenceError: The model did not converge. Try adding a larger penalizer (...)

### ISSUE THREAD

**Issue by FakieKickflip** [CamDavidsonPilon/lifetimes#419]
Hi,

I just followed the tutorial of [towardsdatascience.com:](https://towardsdatascience.com/whats-a-customer-worth-8daf183f8a4f)

At the point: 

```
bgf = BetaGeoFitter(penalizer_coef=0.001)
bgf.fit(data['frequency'], data['recency'], data['T'])
```

I am running into a strange error: 

>  (...)python3.7/site-packages/lifetimes/fitters/beta_geo_fitter.py", line 143, in fit
    **kwargs
(...)python3.7/site-packages/lifetimes/fitters/__init__.py", line 119, in _fit
    """
lifetimes.utils.ConvergenceError: 
The model did not converge. Try adding a larger penalizer to see if that helps convergence.

Is there a solution for this issue?

**Comment by nesrinozcan** [comment]
Did you find a solution?

**Comment by dottieka** [comment]
Try grouping values together like it worked for me:
df_ = df.groupby(["frequency", "recency", "T"]).size().reset_index()

BetaGeoBetaBinomFitter().fit(df_['frequency'], df_['recency'], df_['T'], weights=df_[0])
