### ISSUE TITLE
Running conditional_expected_number_of_purchases_up_to_time on ParetoNBD model throws a pandas NotImplementedError

### ISSUE THREAD

**Issue by sam-lupton** [CamDavidsonPilon/lifetimes#420]
I tried this on several different standard transactional datasets, and all gave the same error, which seems to be due to pandas/scipy incompatibility. The traceback is below, but it's a pandas NotImplementedError, found when implementing conditional_expected_number_of_purchases_up_to_time on the ParetoNBD model. The method works fine for BetaGeo with this data, and more weirdly, even when I transform the data into exactly the same format as the load_cdnow_summary dataset, the load_cdnow_summary works and my data doesn't.

My code, and a sample of the data, is attached below (f is the summary dataset)

```
nbd = ParetoNBDFitter(penalizer_coef=0.01)
nbd.fit(f['frequency'], f['recency'], f['T'])
```

![image](https://user-images.githubusercontent.com/46453364/135496943-8e2e9a90-e65f-41b7-8669-c639df059ded.png)

`nbd.conditional_expected_number_of_purchases_up_to_time(1, f['frequency'], f['recency'], f['T'])`

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/var/folders/z7/h1rmk7f11kg5yg15rzg3xk8h0000gn/T/ipykernel_868/191803226.py in <module>
----> 1 nbd.conditional_expected_number_of_purchases_up_to_time(1, f['frequency'], f['recency'], f['T'])

~/Environments/ltv/lib/python3.8/site-packages/lifetimes/fitters/pareto_nbd_fitter.py in conditional_expected_number_of_purchases_up_to_time(self, t, frequency, recency, T)
    277         r, alpha, s, beta = params
    278 
--> 279         likelihood = self._conditional_log_likelihood(params, x, t_x, T)
    280         first_term = (
    281             gammaln(r + x) - gammaln(r) + r * log(alpha) + s * log(beta) - (r + x) * log(alpha + T) - s * log(beta + T)

~/Environments/ltv/lib/python3.8/site-packages/lifetimes/fitters/pareto_nbd_fitter.py in _conditional_log_likelihood(params, freq, rec, T)
    212 
    213         A_1 = gammaln(r + x) - gammaln(r) + r * log(alpha) + s * log(beta)
--> 214         log_A_0 = ParetoNBDFitter._log_A_0(params, x, rec, T)
    215 
    216         A_2 = logaddexp(-(r + x) * log(alpha + T) - s * log(beta + T), log(s) + log_A_0 - log(r_s_x))

~/Environments/ltv/lib/python3.8/site-packages/lifetimes/fitters/pareto_nbd_fitter.py in _log_A_0(params, freq, recency, age)
    179 
    180         rsf = r + s + freq
--> 181         p_1 = hyp2f1(rsf, t, rsf + 1.0, abs_alpha_beta / (max_of_alpha_beta + recency))
    182         q_1 = max_of_alpha_beta + recency
    183         p_2 = hyp2f1(rsf, t, rsf + 1.0, abs_alpha_beta / (max_of_alpha_beta + age))

~/Environments/ltv/lib/python3.8/site-packages/pandas/core/generic.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
   2027         self, ufunc: np.ufunc, method: str, *inputs: Any, **kwargs: Any
   2028     ):
-> 2029         return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
   2030 
   2031     # ideally we would define this to avoid the getattr checks, but

~/Environments/ltv/lib/python3.8/site-packages/pandas/core/arraylike.py in array_ufunc(self, ufunc, method, *inputs, **kwargs)
    290             # well. Previously this raised an internal ValueError. We might
    291             # support it someday, so raise a NotImplementedError.
--> 292             raise NotImplementedError(
    293                 "Cannot apply ufunc {} to mixed DataFrame and Series "
    294                 "inputs.".format(ufunc)

NotImplementedError: Cannot apply ufunc <ufunc 'hyp2f1'> to mixed DataFrame and Series inputs.
```

**Comment by sam-lupton** [comment]
Here's the .describe() of the dataset, in case you spot any patterns. Any help would be appreciated!

Here are the relevant versions:
pandas 1.3.0
scipy 1.7.0
lifetimes 0.11.3
![image](https://user-images.githubusercontent.com/46453364/135498923-2edf9175-0fe7-45a1-af10-1f31fc927075.png)

**Comment by sam-lupton** [comment]
**Update:** fixed this in the end by passing in ndarrays rather than pandas Series (which is as simple as using, for instance, `f['frequency'].values` rather than `f['frequency']` in my code above).

Ideally the function would work fine with pandas datatypes (like the rest of the package), but this is a workaround for now!

**Comment by nicknelson1021** [comment]
@sam-lupton, were you able to get the ParetoNBDFitter model to work with the customer_lifetime_value function provided by the GammaGammaFitter model? I can only get it to work with the BetaGeoFitter model and I think it's related to the above.
