### ISSUE TITLE
Any plan to integrate the periodic death opportunity (PDO) model? 

### ISSUE THREAD

**Issue by aabuabat** [CamDavidsonPilon/lifetimes#427]
Hi, 

First, thanks for the great efforts and amazing work. I have looked through the (well-written) documentation and I have not found other CLV variations models such as the periodic death opportunity (PDO), proposed [here](https://repository.upenn.edu/cgi/viewcontent.cgi?article=1343&context=fnce_papers). I highly doubt that you have not discussed the idea of integrating such models; my question is what is your viewpoint on not incorporating the PDO model with the lifetime library? 

Thanks

**Comment by ColtAllen** [comment]
Hey @aabuabat,

Active development in this library is proceeding in a [fork](https://github.com/ColtAllen/lifetimes) I've created.

My current priorities involve refactoring `lifetimes` to run on a more stable, actively maintained backend, but I saved the link to the paper you provided and made a note to evaluate this as a future addition. Thanks for sharing it!
