### ISSUE TITLE
Wrong monetary_value

### ISSUE THREAD

**Issue by skwskwskwskw** [CamDavidsonPilon/lifetimes#429]
![image](https://user-images.githubusercontent.com/7208012/166944376-6aaf3cc4-e456-41ef-94ac-bd5bf52f6842.png)

I can't really agree with the monetary value here. So if only single transaction happens, the first one is omitted? And monetary value = 0?

**Comment by similang** [comment]
![image](https://user-images.githubusercontent.com/7208012/166946003-a8aa0779-dd85-4053-beb3-3b96802d2ae1.png)

I also don't understand how in this case the monetary_value is calculated..... anyone can shed some lights?

**Comment by SSMK-wq** [comment]
@diallo-malick - Shouldn't it be 485 then in the screenshot? why is it shown as 486? which is 1 point higher than actual average?
