### ISSUE TITLE
potential error in calculating CLV

### ISSUE THREAD

**Issue by jackyckma** [CamDavidsonPilon/lifetimes#43]
I found an issue about the calculation of CLV. 

In customer_lifetime_value(), the discounted cash flow for each period is calculated as:

```
df['expected_revenues_period_'+str(i)] = df.apply(
    lambda r: (m*transaction_prediction_model.predict(i, r['frequency'], r['recency'], r['T'])/(1+d)**(i/30)),
    axis=1
    )
```

in which,
_i_ is th looping counter (in steps of 30), 
_m_ is self.conditional_expected_average_profit(),
_d_ is discount rate.
_transaction_prediction_model.predict()_ returns "conditional_expected_number_of_purchases_up_to_time"

It seems to me that _m_ should be the expected profit for individual customer instead of all the training records, and the discounted cash flow for a single period is `m * (predict(t) - predict(t-1)) / (1+d)**(i/30)`

May I propose to make such change:

```
df['monetary_value'] = monetary_value

for i in range(30, (time*30)+1, 30):
    df['expected_revenues_period_'+str(i)] = df.apply(
          lambda r: (r['monetary_value']*
              (transaction_prediction_model.predict(i, r['frequency'], r['recency'], r['T'])
               - transaction_prediction_model.predict(i - 30, r['frequency'], r['recency'], r['T'])) /(1+d)**(i/30)),
              axis=1
     )
```

**Comment by rhydomako** [comment]
I agree with your assessment @jackyckma, and I think it certainly needs to be `m * (predict(t) - predict(t-1)) / (1+d)**(i/30)`. I would also suggest a refactoring such that the calculation doesn't assume that the `T` period is in days and the discount factor `d` is in months, since there is no restriction on what period `T` is held as.

**Comment by CamDavidsonPilon** [comment]
:+1: makes sense to me

**Comment by jackyckma** [comment]
I have made the change in my fork version. Will submit a pull request after testing it.

**Comment by paoloRais** [comment]
It would be even better to replace the monetary value with the individual expected order value computed with the gamma/gamma model. I will add it as soon as I have some time!
