### ISSUE TITLE
How to interpret expected purchase orders in future

### ISSUE THREAD

**Issue by SSMK-wq** [CamDavidsonPilon/lifetimes#437]
I was reading your documentation and also an online tutorial about CLTV [here](https://towardsdatascience.com/whats-a-customer-worth-8daf183f8a4f)

I came to know that BG/NBD can help predict the future number of purchases made by a customer. Accordingly, I came across the below screenshot

![image](https://user-images.githubusercontent.com/30723825/199049930-d382ccf3-603e-4103-8194-eb22df413a7e.png)

But I don't understand why the future purchases/transactions is in decimal form.

Does it indicate any probability/likelihood to make purchase in next 10 days or the count of transactions that a customer will buy in the next 10 days?

For ex, How do we interpret the value 0.157 (in next 10 days) as a value for expected number of purchase transactions?

Does it mean less than 1 transaction? If yes, there is no use in it. or it should be read as 15? (0.15*100). I don't know whether we should multiply by 100

Let's say if we get 0.75 as predicted value, then it is still not useful or it is 75 transactions? (0.75*100)

I also referred your btyd documentation. So, does "conditional expected number of purrchase", "expected number of purchase" are all the same? What is the difference?

Can someone guide me on how can we interpret this correctly?

**Comment by CamDavidsonPilon** [comment]
It's the _expected value_ of the number of transactions, which need not be an integer. More about expected value as decimals here: https://stats.stackexchange.com/questions/378000/expected-value-decimal-or-whole-values

**Comment by SSMK-wq** [comment]
So, when we see 3.34 as an expected value, am i right to interpret it like
below - " customer id = 123, will purchase on average 3.34 times in the
next 10 days"?  - so, he may at least buy 3 times

Whereas if we see expected value as 0.157, does it mean his future purchase
count is low (<1) and we need not worry and ignore him

**Comment by CamDavidsonPilon** [comment]
> " customer id = 123, will purchase on average 3.34 times in the
next 10 days"? 

That's correct

> Whereas if we see expected value as 0.157, does it mean his future purchase
count is low (<1) and we need not worry and ignore him

Maybe! That depends on your business objective.
