### ISSUE TITLE
Unreachable code after fitting betageofitter model

### ISSUE THREAD

**Issue by iliaskior** [CamDavidsonPilon/lifetimes#441]
The code is unreachable under the fit function of BG-NBD model
lifetimes version = 0.11.3

![Screenshot_15](https://user-images.githubusercontent.com/89393090/221185096-4a2afc1d-c62e-4aa9-b533-4eab1365a500.png)

**Comment by ColtAllen** [comment]
Hey @iliaskior,

Development on the `lifetimes` project ceased nearly 3 years ago. Here's the link to the successor library, which should see a beta release in the next few months: https://github.com/pymc-labs/pymc-marketing

**Comment by iliaskior** [comment]
Hey @ColtAllen , 

Thank you very much!
