### ISSUE TITLE
How to get conditional probability alive for the next few periods?

### ISSUE THREAD

**Issue by rachelyee** [CamDavidsonPilon/lifetimes#446]
Hi, just wanted to find how can i get the probability alive for a few periods out. Conditional_probability_alive() only gets the current probability alive but i would like to get probability for a few periods out, like how it can be done in plot_history_alive. Is there a workaround for this?

**Comment by ColtAllen** [comment]
Hey @rachelyee, the best workaround for the `BetaGeoFitter` would be to increment the `T` array input into `conditional_probability_alive()`. This notebook contains an example for an individual customer:

https://www.pymc-marketing.io/en/stable/notebooks/clv/clv_quickstart.html#customer-probability-histories

`pymc-marketing` is the successor library to `lifetimes`, and it's worth mentioning the upcoming `ParetoNBDModel` has this capability by default.
