### ISSUE TITLE
Recency Definition 

### ISSUE THREAD

**Issue by HM9N** [CamDavidsonPilon/lifetimes#448]
Hello Everyone,

In many sources, the definition of recency is described as "indicating the time between the last consumption and the present." However, in Lifetimes, we use a different definition. In Lifetimes, recency represents the age of the customer at the time of their most recent purchase. Specifically, it is equal to the duration between a customer's first purchase and their latest purchase.

I'm curious to know if anyone can shed light on why this difference in definition exists. Any insights on the rationale behind this choice?

Thank you.

**Comment by ColtAllen** [comment]
Hey @HM9N,

Development on `lifetimes` has been discontinued; [pymc-marketing](https://github.com/pymc-labs/pymc-marketing) is the successor project.

To answer your question, the conventional definition of recency is used in RFM analysis, which is about segmenting customers based on their past purchase behavior. However, the models in `lifetimes` and now `pymc-marketing` are predictive in nature. A key component of these predictive models is the transaction rate. Modeling this requires knowing the time between each customer's first and last transactions. Hope this helps.
