### ISSUE TITLE
Lifetimes Model Application & interpretation

### ISSUE THREAD

**Issue by KollyT** [CamDavidsonPilon/lifetimes#453]
Hello, 

I am currently using the lifetimes package to try and determine which of our consumers are currently 'Alive' or 'Dead' based on their transactional information. I have successfully applied the model but wondered if you could give some guidance on how to interpret the outputs. I have two key questions:  

- When you have consumers that are deemed 95% alive versus others at 30% alive, is this score based on the individual consumer and their change in behaviour or is it in relation to the total population?

- If I wanted to identify lapsing consumers faster would a drop in the probability alive score from one period to the next be the best method? or just using their current prob alive score, i.e. anyone under 30% alive will be considered lapsing/lapsed?

I would really appreciate any help you can provide on the above.

**Comment by CamDavidsonPilon** [comment]
Hi sorry @KollyT, you posted this issue _right_ when I was archiving this repository. Archiving a repository is part of some project's lifecycle: the owner (me) might not have enough time, or expertise, or interest, in keeping up with a project. That's the case here. 

I suggest moving to a different library for your analysis. 

Anyways, I hope this sudden closing-and-archiving of your issue didn't sour your experience with Github or open-source - it was just some bad timing! Generally, welcome to Github!
