### ISSUE TITLE
plot_probability_alive_matrix give AttributeError: 'Spine' object has no attribute 'autoscale_None'

### ISSUE THREAD

**Issue by robertdefilippi** [CamDavidsonPilon/lifetimes#46]
I'm trying to recreate the example in on the main lifetimes page, but I'm using my own data.

I've cleaned my data and run the BetaGeoFilter correctly.

```
from lifetimes import BetaGeoFitter

bgf = BetaGeoFitter(penalizer_coef=0.0)
bgf.fit(df_merge_2['frequency'], df_merge_2['recency'], df_merge_2['t'])

print bgf

>> lifetimes.BetaGeoFitter: fitted with 3560 subjects, r: 0.29, alpha: 0.00, a: 0.66, b: 0.14
```

However when I run:

from lifetimes.plotting import plot_frequency_recency_matrix
or
from lifetimes.plotting import plot_probability_alive_matrix

I get the same error for both:

`AttributeError: 'Spine' object has no attribute 'autoscale_None'`

Any idea why this error would occur?

**Comment by CamDavidsonPilon** [comment]
Hey @chef1075, which version of matplotlib are you using?

**Comment by chef1075** [comment]
import matplotlib as plt plt.__version__
> '1.5.1'

On Thu, Feb 4, 2016 at 2:52 AM, Cameron Davidson-Pilon < notifications@github.com > wrote:
Hey @chef1075 , which version of matplotlib are you using?

—
Reply to this email directly or view it on GitHub .




Robert R. F. DeFilippi @rrfd +1 604 817 9657

**Comment by rhydomako** [comment]
Hi @chef1075, are version of lifetimes are you using? I think this issue is fixed in the dev repo, but is still present in 0.1.6.3, which is the most recent version in pypi.

**Comment by chef1075** [comment]
import lifetimes
>> lifetimes.__version__ 0.1.6.3
Would a copy of my data help? Maybe that is the issue.

On Thu, Feb 4, 2016 at 2:44 PM, Richard Hydomako < notifications@github.com > wrote:
Hi @chef1075 , are version of lifetimes are you using? I think this issue is fixed in the
dev repo, but is still present in 0.1.6.3, which is the most recent version in
pypi.

—
Reply to this email directly or view it on GitHub .




Robert R. F. DeFilippi @rrfd +1 604 817 9657

**Comment by CamDavidsonPilon** [comment]
I just now pushed 1.6.4 to pypi, so please update using
```
pip install --upgrade lifetimes
```
