### ISSUE TITLE
Transforming transactional data into summary data

### ISSUE THREAD

**Issue by izmendi** [CamDavidsonPilon/lifetimes#48]
Hello.-
I'm trying to transform the following transactional data into summary data...

Transactional data:
	date	id
0	08/03/2014	0
1	21/05/2014	1
2	14/03/2014	2
3	09/04/2014	2
4	21/05/2014	2

To transform transactional data into summary data:
`summary = summary_data_from_transaction_data(transaction_data, 'id', 'date', observation_period_end='31/12/2014')`

and I get the following matrix:
id	frequency	recency	T	
0	0	0	150
1	0	0	224
2	2	174	292

but If I do it manually I get the following one, 
id	frequency	recency	T
0	0	0	298
1	0	0	224
2	2	68	292

what I'm doing wrong? These have been my numbers ......
298 = 31/12/2014 - 08/03/2014
224 = 31/12/2014 - 21/05/2014
292 = 31/12/2014 - 14/03/2014
68 =  21/05/2014 - 14/03/2014

Thanks in advanced,
Izaskun

**Comment by rhydomako** [comment]
Hi @izmendi, the datetime conversion is ambiguous -- it looks like `summary_data_from_transaction_data` is taking the days as months and the months as days.

Try:
```
summary_data_from_transaction_data(
    transaction_data,
    'id',
    'date',
    datetime_format='%d/%m/%Y',
    observation_period_end='31/12/2014'
)
```

With the explicit datetime formatting, I get your expected result:

```
    frequency  recency    T
id                         
0           0        0  298
1           0        0  224
2           2       68  292
```

**Comment by izmendi** [comment]
Thank you very much, your help has been unvaluable :+1

**Comment by CamDavidsonPilon** [comment]
thanks @rhydomako!
