### ISSUE TITLE
pip install lifetimes error

### ISSUE THREAD

**Issue by Myoupp** [CamDavidsonPilon/lifetimes#54]
Hi,

i can not pip insall lifetimes module. i get the following error message:

runfile('C:/Users/az/.spyder2-py3/temp.py', wdir='C:/Users/az/.spyder2-py3')
  File "C:/Users/az/.spyder2-py3/temp.py", line 12
    pip install lifetimes
              ^
SyntaxError: invalid syntax

Any clue about this?

**Comment by CamDavidsonPilon** [comment]
Hm. Can you pip install other python Packages?

**Comment by Myoupp** [comment]
Apparentlely can not pip install any of them. i have tested with virtualenv it's not working either. 


runfile('C:/Users/az/.spyder2-py3/temp.py', wdir='C:/Users/az/.spyder2-py3')
  File "C:/Users/az/.spyder2-py3/temp.py", line 12
    pip install virtualenv
              ^
SyntaxError: invalid syntax

**Comment by CamDavidsonPilon** [comment]
So it's probably the way your python is setup. I can't help much, sorry =(

**Comment by Myoupp** [comment]
Do you have an idea please about what could be the problem? i am totally blocked :(

**Comment by CamDavidsonPilon** [comment]
Not even one =\

Maybe try stackoverflow? Or spyder documenation/support?
