### ISSUE TITLE
ModifiedBetaGeoFitter doens't converge

### ISSUE THREAD

**Issue by MarcoMene** [CamDavidsonPilon/lifetimes#55]
Hello,
I tried to fit a ModifiedBetaGeo model on some data generated by the model itself.
It doesn't give good results. I tried to modify the initial parameters but it basically never works.
It seems to have problems in fitting a and b parameters. They are always next to zero.

Here is the code to reproduce the issue:

import lifetimes.generate_data as gen
from lifetimes import estimation
from lifetimes.models import extract_frequencies

T = 40
r = 0.24
alpha = 4.41
a = 0.8
b = 2.43

data = gen.modified_beta_geometric_nbd_model(T, r, alpha, a, b, size=1000)
fitter = estimation.ModifiedBetaGeoFitter()
fitter.fit(data['frequency'],data['recency'],data['T'])
print "Library Fit"
print fitter.params_

**Comment by rhydomako** [comment]
Hi Marco,

I wasn't able to reproduce your findings. I ran a modified script to generate/fit a bunch of times:

```python
import matplotlib.pylab as plt
import pandas as pd

import lifetimes.generate_data as gen
from lifetimes import estimation

T = 40
r = 0.24
alpha = 4.41
a = 0.8
b = 2.43

fitter = estimation.ModifiedBetaGeoFitter()

params = []
for _ in range(500):
    data = gen.modified_beta_geometric_nbd_model(T, r, alpha, a, b, size=1000)
    fitter.fit(data['frequency'],data['recency'],data['T'])
    
    params.append(fitter._unload_params('r','alpha','a','b'))

df = pd.DataFrame(params, columns=['r','alpha','a','b'])

fig, axes = plt.subplots(nrows=2, ncols=2)
df.hist('r', bins=100, range=(0,1), ax=axes[0,0])
df.hist('alpha', bins=100, range=(2,7), ax=axes[0,1])
df.hist('a', bins=100, range=(0.2,4), ax=axes[1,0])
df.hist('b', bins=100, range=(0,10), ax=axes[1,1])
```

which produced the following distributions:

![download](https://cloud.githubusercontent.com/assets/2955572/14744398/a4caa69e-0874-11e6-806f-99d5c2166d7b.png)

I should note that I've clipped some outliers where sometimes the fitting failed and produced `a` and `b` params in the 10^6 range, but that happened something like 2 times in 500 trials.

I'm not sure why you're seeing so many fitted parameters close to zero...

**Comment by CamDavidsonPilon** [comment]
Great script @rhydomako. I tried this too on my system (using 0.2.2.1). Output below: 

<img width="1009" alt="screen shot 2016-10-12 at 19 41 07" src="https://cloud.githubusercontent.com/assets/884032/19331759/615cc5f4-90b4-11e6-8392-593a32e022ee.png">

I also get sometimes wild values for (a,b) (not shown here), but by adding a small `penalizer_coef=0.01`, the results are more sensible (below)

<img width="1016" alt="screen shot 2016-10-12 at 19 44 58" src="https://cloud.githubusercontent.com/assets/884032/19331758/61529f70-90b4-11e6-8daf-4fa8b3248116.png">


The max value of `a` in this simulation was 34.50
