### ISSUE TITLE
Aggregating transactional data neglects first-day purchases

### ISSUE THREAD

**Issue by MarcoMene** [CamDavidsonPilon/lifetimes#56]
Hello,
I want to point out an issue regarding the data aggregator:

```from lifetimes.utils import summary_data_from_transaction_data```

If you aggregate data with the Days (D) frequency (which is the default) the users that do purchase the first day, just after the install, result in zero frequency in the aggregated dataset.
So we are neglecting a possibly large fraction of purchasing users, considering them as non-purchasing.

If you want an example, consider this transactional data:
```id,date,monetary_value
1,2016-01-01 00:01:44,0.0
2,2016-01-01 00:01:50,0.0
1,2016-01-01 00:01:55,5.0
1,2016-01-01 00:01:58,5.0
2,2016-01-05 00:01:50,1.0
```
Run the aggregator on them:
``` from lifetimes.utils import summary_data_from_transaction_data
data = summary_data_from_transaction_data(transaction_data, 'id', 'date',monetary_value_col='monetary_value', observation_period_end='2016-04-08', freq='D')
print data.head()```
You'll get:
```
  frequency  recency     T  monetary_value
id                                          
1         0.0      0.0  98.0             0.0
2         1.0      4.0  98.0             1.0
```
Which is plain wrong in my opinion.
The purchases that user 1 does the first day are completely neglected.
How to fix this?

Cheers
Marco

**Comment by CamDavidsonPilon** [comment]
In the literature on the models used in lifetimes, they explicitly do not include the first transaction (this is their birth event). Frequency refers to repeat purchases. See http://mktg.uni-svishtov.bg/ivm/resources/counting_your_customers.pdf

**Comment by MarcoMene** [comment]
Hello, thanks for answering.
I actually considered this hypothesis. Looking at the paper here I got confused on this point:
http://www.brucehardie.com/papers/rfm_clv_2005-02-16.pdf
but reading it again, your point seems confirmed.
So this means that we have to completely neglect the first purchase? It seems to me a waste of info, since we have available the install information, the birth event.
Why not to consider at least the monetary value of the first purchase?
Thanks again
Marco

**Comment by CamDavidsonPilon** [comment]
In the BG/NBD and Pareto/NBD models, we don't use monetary value in the inference, so it's okay to ignore those values. However I disagree that we can we losing information: if a customer makes a purchase (even only one), they are recorded in the dataset. The transformation between frequency and #number of purchases is only a difference of 1, so no information is lost in that transformation.
