### ISSUE TITLE
id format in function:summary_data_from_transaction_data

### ISSUE THREAD

**Issue by davidlopezberzosa** [CamDavidsonPilon/lifetimes#58]
Hi,

I am trying to import some data and convert it to the right form using:summary_data_from_transaction_data.

However it seems that it does not allow IDs in string format (e.g. 8a583481da078d09a2ad3a1e04c1740c).
I believe it would be useful to allow non-numbers for instance to process customers ID which have previously hashed.

Best
David L.

**Comment by CamDavidsonPilon** [comment]
Interesting, I agree with you. Can you provide the error that is thrown?

**Comment by CamDavidsonPilon** [comment]
This doesn't appear to be happening in the latest master: https://github.com/CamDavidsonPilon/lifetimes/commit/ec7c0e27382dd9d0959df3ad5d515902dab7806c#diff-87010571bbeeee0b9a13279c493670f3R159

**Comment by aprotopopov** [comment]
I think we could close it as already fixed.
