### ISSUE TITLE
summary_data_from_transaction_data coerces the CustomerID to a float

### ISSUE THREAD

**Issue by Kevin-McIsaac** [CamDavidsonPilon/lifetimes#60]
The utility summary_data_from_transaction_data coerces the CustomerID to a float in line 182. I dont see the sense in this and it mean I've to coerce it back to its original format if I want to merge with other customer data.

**Comment by CamDavidsonPilon** [comment]
weird, good catch. Can you PR something to the library?

**Comment by CamDavidsonPilon** [comment]
This doesn't seem to be happening anymore https://github.com/CamDavidsonPilon/lifetimes/commit/ec7c0e27382dd9d0959df3ad5d515902dab7806c#diff-87010571bbeeee0b9a13279c493670f3R159
