### ISSUE TITLE
import error for name _zeta when running quickstart example

### ISSUE THREAD

**Issue by lyndb** [CamDavidsonPilon/lifetimes#64]
Using anaconda Python 3.4, and after having installed with pip, running the first quickstart example, 

from lifetimes.datasets import load_cdnow

results in:

---

ImportError                               Traceback (most recent call last)
<ipython-input-2-5b71bec70bc3> in <module>()
----> 1 from lifetimes.datasets import load_cdnow

/home/lynd/anaconda3/lib/python3.4/site-packages/lifetimes/**init**.py in <module>()
----> 1 from .estimation import BetaGeoFitter, ParetoNBDFitter, GammaGammaFitter, ModifiedBetaGeoFitter
      2 from .version import **version**
      3 
      4 **all** = ['BetaGeoFitter', 'ParetoNBDFitter', 'GammaGammaFitter', 'ModifiedBetaGeoFitter']

/home/lynd/anaconda3/lib/python3.4/site-packages/lifetimes/estimation.py in <module>()
      7 from pandas import DataFrame
      8 
----> 9 from scipy import special
     10 from scipy import misc
     11 

/home/lynd/anaconda3/lib/python3.4/site-packages/scipy/special/**init**.py in <module>()
    636 from ._ufuncs import *
    637 
--> 638 from .basic import *
    639 from . import specfun
    640 from . import orthogonal

/home/lynd/anaconda3/lib/python3.4/site-packages/scipy/special/basic.py in <module>()
     13                    where, mgrid, sin, place, issubdtype, extract,
     14                    less, inexact, nan, zeros, atleast_1d, sinc)
---> 15 from ._ufuncs import (ellipkm1, mathieu_a, mathieu_b, iv, jv, gamma,
     16                       psi, _zeta, hankel1, hankel2, yv, kv, _gammaln,
     17                       ndtri, errprint, poch, binom, hyp0f1)

ImportError: cannot import name '_zeta'

**Comment by grantog** [comment]
What was the resolution on not being able to import load_cdnow?
