### ISSUE TITLE
What is the time period for conditional_expected_number_of_purchases_up_to_time method?

### ISSUE THREAD

**Issue by steezeburger** [CamDavidsonPilon/lifetimes#65]
From the source

```
   """
   Calculate the expected number of repeat purchases up to time t for a randomly choose individual from
    the population, given they have purchase history (frequency, recency, T)

    Parameters:
        t: a scalar or array of times.
        frequency: a scalar: historical frequency of customer.
        recency: a scalar: historical recency of customer.
        T: a scalar: age of the customer.

    Returns: a scalar or array
    """
```

The docs say t is just one period of time. What is that period?

**Comment by CamDavidsonPilon** [comment]
It is up to your input data: that is, what is your unit of time in measures like recency? Does that answer your question?

**Comment by steezeburger** [comment]
I believe it's days, but to be honest not entirely sure where that comes from either. I guess you mean my data dictates the period. If I had weekly report data, then my period would be a week correct? 

This seems fine, but for some reason I'm getting probabilities higher than 1 when increasing `t`.

**Comment by CamDavidsonPilon** [comment]
>  If I had weekly report data, then my period would be a week correct?
that's correct

Keep in mind, this returns the expected number of purchases, which can be greater than 1.

**Comment by steezeburger** [comment]
Ah that's good to know! Thanks for the quick replies and the awesome library.
