### ISSUE TITLE
iterative_fitting not really iterative?

### ISSUE THREAD

**Issue by yanirs** [CamDavidsonPilon/lifetimes#76]
Reading through the code of `utils._fit`, it looks like the assignment to `params_init` in the end of the loop (https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/utils.py#L247) doesn't have any effect because `params_init` gets overwritten in the beginning of the loop (https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/utils.py#L240). Looks like line 240 should be outside the loop body.

I'd also give `params_init` a different name (`current_params`?) to make the difference between that variable and `initial_params` clearer.

**Comment by CamDavidsonPilon** [comment]
👍 good catch, I'll PR this now

**Comment by CamDavidsonPilon** [comment]
Fixed in https://github.com/CamDavidsonPilon/lifetimes/commit/97a5815bf4c5e015fc4e98389419106be180362f
