### ISSUE TITLE
summary_data_from_transaction_data implicitly requires Transaction Data to be sorted by date

### ISSUE THREAD

**Issue by aashanand** [CamDavidsonPilon/lifetimes#85]
The utility summary_data_from_transaction_data implicitly requires the input DataFrame to be sorted by the Datetime column in ascending order. Either this requirement should be explicitly stated in the documentation, or the utility itself should conduct the sort prior to summarization. Many transactional datasets (from Shopify's API, for example) come sorted in descending order of timestamps by default.

Minimal repro below. Notice the difference in `monetary_value` field for customer with ID 2.

```python
import pandas as pd
from lifetimes.utils import summary_data_from_transaction_data

# Replicating output from Readme.md under "Example using transactional datasets"
# https://github.com/CamDavidsonPilon/lifetimes#example-using-transactional-datasets
cust = pd.Series([0,1,2,2,2])
dates1 = pd.to_datetime(pd.Series(['2014-03-08 00:00:00',
                  '2014-05-21 00:00:00',
                  '2014-03-14 00:00:00',
                  '2014-04-09 00:00:00',
                  '2014-05-21 00:00:00']))
sales1 = pd.Series([10,20,10,20,25])
transaction_data1 = pd.DataFrame({'date': dates1, 'id': cust, 'sales': sales1})
summary1 = summary_data_from_transaction_data(transaction_data1, 'id', 'date', 'sales', observation_period_end='2014-12-31')
print(summary1)
```
        frequency  recency      T  monetary_value
    id                                           
    0         0.0      0.0  298.0             0.0
    1         0.0      0.0  224.0             0.0
    2         2.0     68.0  292.0            22.5
```python
# Now we just change the order of the 3rd and 5th transactions
dates2 = pd.to_datetime(pd.Series(['2014-03-08 00:00:00',
                  '2014-05-21 00:00:00',
                  '2014-05-21 00:00:00',
                  '2014-04-09 00:00:00',
                  '2014-03-14 00:00:00']))
sales2 = pd.Series([10,20,25,20,10])
transaction_data2 = pd.DataFrame({'date': dates2, 'id': cust, 'sales': sales2})
summary2 = summary_data_from_transaction_data(transaction_data2, 'id', 'date', 'sales', observation_period_end='2014-12-31')
print(summary2)
```
        frequency  recency      T  monetary_value
    id                                           
    0         0.0      0.0  298.0             0.0
    1         0.0      0.0  224.0             0.0
    2         2.0     68.0  292.0            15.0

**Comment by CamDavidsonPilon** [comment]
huh, lame. I'll get this fixed asap

**Comment by aashanand** [comment]
Should be sufficient to change line 113 in `lifetimes.utils`, in function `find_first_transactions` to:

```python
transactions = transactions[select_columns].sort(['datetime_col']).copy()
```

**Comment by CamDavidsonPilon** [comment]
Yes, I think so. Would you be interested in making that change?
