### ISSUE TITLE
Bug when there are multiple orders in same day

### ISSUE THREAD

**Issue by paoloRais** [CamDavidsonPilon/lifetimes#91]
The current functions to obtain summary data from transaction data do not work properly when there is more than one order per day. For example:

```
import pandas as pd
from lifetimes.utils import summary_data_from_transaction_data

test = [{'id': 1, 'date':'2012-01-06'},
        {'id': 1, 'date':'2012-01-06'}]
test = pd.DataFrame(test)
test['date'] = pd.to_datetime(test['date'])
summary = summary_data_from_transaction_data(test, 'id', 'date', observation_period_end='2012-12-31')
print(summary)


```
yields

frequency=1  recency=0      T=360, where frequency > recency. This is probably due to commit [ c05f88b ](https://github.com/CamDavidsonPilon/lifetimes/commit/08695a4eebd81510743404fef32e5a2dbf1ff01e).

To my knowledge, cases where frequency > recency will break the fitting procedure. I think that in the literature if there is more than one order during the same time unit, the second order is considered as a 'top up' and is merged with the first, i.e. the frequency is (number of unique dates) -1

**Comment by CamDavidsonPilon** [comment]
Yea, I think you are right. I'm going to revert my PR

**Comment by CamDavidsonPilon** [comment]
This was rolled back and a new version was released
