### ISSUE TITLE
ggf.customer_lifetime_value returns sum of CLV instead of CLV per customer_id

### ISSUE THREAD

**Issue by ronnyli** [CamDavidsonPilon/lifetimes#93]
Hi @CamDavidsonPilon, long time no see!

Just wanted to point out an issue in the Quickstart tutorial in the Gamma-gamma model section. When I run the example code for `ggf.customer_lifetime_value` I get a single value (`1992970.28649` to be exact) instead of a column containing one prediction per customer like in the docs. To get an output similar to the docs I needed to do a groupby on `customer_id` and then apply `ggf.customer_lifetime_value` to each chunk, which is incredibly slow.

Hope this was helpful, keep up the good work!

**Comment by ronnyli** [comment]
for anyone else with a similar issue check your version of `lifetimes` to see if it's lower than `0.2.0.0`
> `$ pip freeze | grep Life`
`Lifetimes==0.1.6.3`

My version was 0.1.6.3 so I updated to the [latest version](https://github.com/CamDavidsonPilon/lifetimes/blob/master/lifetimes/version.py) which is currently 0.7.0.0.

`pip install Lifetimes==0.7.0.0` fixed the problem

**Comment by CamDavidsonPilon** [comment]
🎉  phew! Easy bug =)
